<?php

declare(strict_types=1);

namespace Xterr\Espd\Codelist;

use Xterr\UBL\Xml\Mapping\CodelistMeta;

/**
 * @generated by php-ubl code generator — do not edit
 */
#[CodelistMeta(listID: 'boolean-gui-control-type', listAgencyID: 'TED-OP-ESPD', listVersionID: '4.1.0')]
enum BooleanGUIControl: string
{
    case CHECK_BOX_FALSE = 'CHECK_BOX_FALSE';
    case CHECK_BOX_TRUE = 'CHECK_BOX_TRUE';
    case CHECK_BOX_UNCHECKED = 'CHECK_BOX_UNCHECKED';
    case RADIO_BUTTON_FALSE = 'RADIO_BUTTON_FALSE';
    case RADIO_BUTTON_TRUE = 'RADIO_BUTTON_TRUE';
    case RADIO_BUTTON_UNSELECTED = 'RADIO_BUTTON_UNSELECTED';
}
