<?php

declare(strict_types=1);

namespace Xterr\Espd\Codelist;

use Xterr\UBL\Xml\Mapping\CodelistMeta;

/**
 * @generated by php-ubl code generator — do not edit
 */
#[CodelistMeta(
    listID: 'http://publications.europa.eu/resource/authority/docrefcontent-type',
    listAgencyID: 'OP',
    listVersionID: '20250924-0',
)]
enum Docrefcontent: string
{
    case TED_PIN = 'TED_PIN';
    case LOJPIN = 'LOJPIN';
    case TED_CN = 'TED_CN';
    case ROJCN = 'ROJCN';
    case ROJPIN = 'ROJPIN';
    case ESPD_REQUEST = 'ESPD_REQUEST';
    case NOJCN = 'NOJCN';
    case NOJPIN = 'NOJPIN';
    case LOJCN = 'LOJCN';
    case EPO_ACC_ESPD_REQUEST = 'epo-acc-espd-request';
}
