<?php

declare(strict_types=1);

namespace Xterr\Espd\Codelist;

use Xterr\UBL\Xml\Mapping\CodelistMeta;

/**
 * @generated by php-ubl code generator — do not edit
 */
#[CodelistMeta(listID: 'eoid-type', listAgencyID: 'TED-OP-ESPD', listVersionID: '4.1.0')]
enum EOID: string
{
    case BRIS = 'BRIS';
    case DUNS = 'DUNS';
    case LEI = 'LEI';
    case NATIONAL = 'NATIONAL';
    case VAT = 'VAT';
}
