<?php

declare(strict_types=1);

namespace Xterr\Espd\Codelist;

use Xterr\UBL\Xml\Mapping\CodelistMeta;

/**
 * @generated by php-ubl code generator — do not edit
 */
#[CodelistMeta(listID: 'property-group-type', listAgencyID: 'TED-OP-ESPD', listVersionID: '4.1.0')]
enum PropertyGroup: string
{
    case ON = 'ON*';
    case ONFALSE = 'ONFALSE';
    case ONTRUE = 'ONTRUE';
}
