<?php

declare(strict_types=1);

namespace Xterr\Espd\Enum;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * A utility type, not for public use
 */
enum formChoice: string
{
    case QUALIFIED = 'qualified';
    case UNQUALIFIED = 'unqualified';
}
