<?php

declare(strict_types=1);

namespace Xterr\Espd\Cbc;

use Xterr\UBL\Xml\Mapping\XmlAttribute;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;
use Xterr\UBL\Xml\Mapping\XmlValue;

/**
 * @generated by php-ubl code generator — do not edit
 */
#[XmlType(localName: 'QuantityType', namespace: Ns::CBC)]
final class Quantity
{
    #[XmlValue]
    private ?string $value = null;

    #[XmlAttribute(name: 'unitCode', required: false)]
    private ?string $unitCode = null;

    #[XmlAttribute(name: 'unitCodeListID', required: false)]
    private ?string $unitCodeListID = null;

    #[XmlAttribute(name: 'unitCodeListAgencyID', required: false)]
    private ?string $unitCodeListAgencyID = null;

    #[XmlAttribute(name: 'unitCodeListAgencyName', required: false)]
    private ?string $unitCodeListAgencyName = null;

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(?string $value = null): self
    {
        $this->value = $value;
        return $this;
    }

    public function getUnitCode(): ?string
    {
        return $this->unitCode;
    }

    public function setUnitCode(?string $unitCode = null): self
    {
        $this->unitCode = $unitCode;
        return $this;
    }

    public function getUnitCodeListID(): ?string
    {
        return $this->unitCodeListID;
    }

    public function setUnitCodeListID(?string $unitCodeListID = null): self
    {
        $this->unitCodeListID = $unitCodeListID;
        return $this;
    }

    public function getUnitCodeListAgencyID(): ?string
    {
        return $this->unitCodeListAgencyID;
    }

    public function setUnitCodeListAgencyID(?string $unitCodeListAgencyID = null): self
    {
        $this->unitCodeListAgencyID = $unitCodeListAgencyID;
        return $this;
    }

    public function getUnitCodeListAgencyName(): ?string
    {
        return $this->unitCodeListAgencyName;
    }

    public function setUnitCodeListAgencyName(?string $unitCodeListAgencyName = null): self
    {
        $this->unitCodeListAgencyName = $unitCodeListAgencyName;
        return $this;
    }

    public function __toString(): string
    {
        return (string) $this->value;
    }
}
