<?php

declare(strict_types=1);

namespace Xterr\Espd\Doc;

use DateTimeImmutable;
use Xterr\Espd\Cac\ContractingParty;
use Xterr\Espd\Cac\DocumentReference;
use Xterr\Espd\Cac\EconomicOperatorParty;
use Xterr\Espd\Cac\Evidence;
use Xterr\Espd\Cac\ProcurementProject;
use Xterr\Espd\Cac\ProcurementProjectLot;
use Xterr\Espd\Cac\Signature;
use Xterr\Espd\Cac\TenderingCriterion;
use Xterr\Espd\Cac\TenderingCriterionResponse;
use Xterr\Espd\Cac\UBLExtensions;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlRoot;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Qualification Application Response. Details
 *  A document issued by a procurement organization to notify an economic operator whether it has been admitted to or excluded from the tendering process.
 *  Qualification Application Response
 */
#[XmlType(
    localName: 'QualificationApplicationResponseType',
    namespace: 'urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationResponse-2',
)]
#[XmlRoot(
    localName: 'QualificationApplicationResponse',
    namespace: 'urn:oasis:names:specification:ubl:schema:xsd:QualificationApplicationResponse-2',
)]
final class QualificationApplicationResponse
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'UBLVersionID', namespace: Ns::CBC)]
    private ?Identifier $ublVersionID = null;

    #[XmlElement(name: 'CustomizationID', namespace: Ns::CBC)]
    private ?Identifier $customizationID = null;

    #[XmlElement(name: 'ProfileID', namespace: Ns::CBC)]
    private ?Identifier $profileID = null;

    #[XmlElement(name: 'ProfileExecutionID', namespace: Ns::CBC)]
    private ?Identifier $profileExecutionID = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'CopyIndicator', namespace: Ns::CBC)]
    private ?bool $copyIndicator = null;

    #[XmlElement(name: 'UUID', namespace: Ns::CBC)]
    private ?Identifier $uuid = null;

    #[XmlElement(name: 'ContractFolderID', namespace: Ns::CBC, required: true)]
    private Identifier $contractFolderID;

    /** @var list<Text> */
    #[XmlElement(name: 'ContractName', namespace: Ns::CBC, type: Text::class)]
    private array $contractNames = [];

    #[XmlElement(name: 'IssueDate', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $issueDate;

    #[XmlElement(name: 'IssueTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $issueTime = null;

    #[XmlElement(name: 'EconomicOperatorGroupName', namespace: Ns::CBC)]
    private ?Text $economicOperatorGroupName = null;

    #[XmlElement(name: 'VersionID', namespace: Ns::CBC)]
    private ?Identifier $versionID = null;

    #[XmlElement(name: 'PreviousVersionID', namespace: Ns::CBC)]
    private ?Identifier $previousVersionID = null;

    #[XmlElement(name: 'ProcedureCode', namespace: Ns::CBC)]
    private ?Code $procedureCode = null;

    #[XmlElement(name: 'QualificationApplicationTypeCode', namespace: Ns::CBC)]
    private ?Code $qualificationApplicationTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'WeightScoringMethodologyNote', namespace: Ns::CBC, type: Text::class)]
    private array $weightScoringMethodologyNotes = [];

    #[XmlElement(name: 'WeightingTypeCode', namespace: Ns::CBC)]
    private ?Code $weightingTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Note', namespace: Ns::CBC, type: Text::class)]
    private array $notes = [];

    /** @var list<ContractingParty> */
    #[XmlElement(name: 'ContractingParty', namespace: Ns::CAC, type: ContractingParty::class, required: true)]
    private array $contractingParties = [];

    /** @var list<EconomicOperatorParty> */
    #[XmlElement(name: 'EconomicOperatorParty', namespace: Ns::CAC, type: EconomicOperatorParty::class, required: true)]
    private array $economicOperatorParties = [];

    #[XmlElement(name: 'ProcurementProject', namespace: Ns::CAC)]
    private ?ProcurementProject $procurementProject = null;

    /** @var list<ProcurementProjectLot> */
    #[XmlElement(name: 'ProcurementProjectLot', namespace: Ns::CAC, type: ProcurementProjectLot::class)]
    private array $procurementProjectLots = [];

    /** @var list<TenderingCriterion> */
    #[XmlElement(name: 'TenderingCriterion', namespace: Ns::CAC, type: TenderingCriterion::class)]
    private array $tenderingCriterions = [];

    /** @var list<TenderingCriterionResponse> */
    #[XmlElement(name: 'TenderingCriterionResponse', namespace: Ns::CAC, type: TenderingCriterionResponse::class, required: true)]
    private array $tenderingCriterionResponses = [];

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'AdditionalDocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $additionalDocumentReferences = [];

    /** @var list<Evidence> */
    #[XmlElement(name: 'Evidence', namespace: Ns::CAC, type: Evidence::class)]
    private array $evidences = [];

    /** @var list<Signature> */
    #[XmlElement(name: 'Signature', namespace: Ns::CAC, type: Signature::class)]
    private array $signatures = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getUblVersionID(): ?Identifier
    {
        return $this->ublVersionID;
    }

    public function setUblVersionID(?Identifier $ublVersionID = null): self
    {
        $this->ublVersionID = $ublVersionID;
        return $this;
    }

    public function getCustomizationID(): ?Identifier
    {
        return $this->customizationID;
    }

    public function setCustomizationID(?Identifier $customizationID = null): self
    {
        $this->customizationID = $customizationID;
        return $this;
    }

    public function getProfileID(): ?Identifier
    {
        return $this->profileID;
    }

    public function setProfileID(?Identifier $profileID = null): self
    {
        $this->profileID = $profileID;
        return $this;
    }

    public function getProfileExecutionID(): ?Identifier
    {
        return $this->profileExecutionID;
    }

    public function setProfileExecutionID(?Identifier $profileExecutionID = null): self
    {
        $this->profileExecutionID = $profileExecutionID;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getCopyIndicator(): ?bool
    {
        return $this->copyIndicator;
    }

    public function setCopyIndicator(?bool $copyIndicator = null): self
    {
        $this->copyIndicator = $copyIndicator;
        return $this;
    }

    public function getUuid(): ?Identifier
    {
        return $this->uuid;
    }

    public function setUuid(?Identifier $uuid = null): self
    {
        $this->uuid = $uuid;
        return $this;
    }

    public function getContractFolderID(): Identifier
    {
        return $this->contractFolderID;
    }

    public function setContractFolderID(Identifier $contractFolderID): self
    {
        $this->contractFolderID = $contractFolderID;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getContractNames(): array
    {
        return $this->contractNames;
    }

    /**
     * @param list<Text> $contractNames
     */
    public function setContractNames(array $contractNames): self
    {
        self::validateContractNames($contractNames);
        $this->contractNames = $contractNames;
        return $this;
    }

    public function addToContractNames(Text $item): self
    {
        $this->contractNames[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateContractNames(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getIssueDate(): DateTimeImmutable
    {
        return $this->issueDate;
    }

    public function setIssueDate(DateTimeImmutable $issueDate): self
    {
        $this->issueDate = $issueDate;
        return $this;
    }

    public function getIssueTime(): ?DateTimeImmutable
    {
        return $this->issueTime;
    }

    public function setIssueTime(?DateTimeImmutable $issueTime = null): self
    {
        $this->issueTime = $issueTime;
        return $this;
    }

    public function getEconomicOperatorGroupName(): ?Text
    {
        return $this->economicOperatorGroupName;
    }

    public function setEconomicOperatorGroupName(?Text $economicOperatorGroupName = null): self
    {
        $this->economicOperatorGroupName = $economicOperatorGroupName;
        return $this;
    }

    public function getVersionID(): ?Identifier
    {
        return $this->versionID;
    }

    public function setVersionID(?Identifier $versionID = null): self
    {
        $this->versionID = $versionID;
        return $this;
    }

    public function getPreviousVersionID(): ?Identifier
    {
        return $this->previousVersionID;
    }

    public function setPreviousVersionID(?Identifier $previousVersionID = null): self
    {
        $this->previousVersionID = $previousVersionID;
        return $this;
    }

    public function getProcedureCode(): ?Code
    {
        return $this->procedureCode;
    }

    public function setProcedureCode(?Code $procedureCode = null): self
    {
        $this->procedureCode = $procedureCode;
        return $this;
    }

    public function getQualificationApplicationTypeCode(): ?Code
    {
        return $this->qualificationApplicationTypeCode;
    }

    public function setQualificationApplicationTypeCode(?Code $qualificationApplicationTypeCode = null): self
    {
        $this->qualificationApplicationTypeCode = $qualificationApplicationTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getWeightScoringMethodologyNotes(): array
    {
        return $this->weightScoringMethodologyNotes;
    }

    /**
     * @param list<Text> $weightScoringMethodologyNotes
     */
    public function setWeightScoringMethodologyNotes(array $weightScoringMethodologyNotes): self
    {
        self::validateWeightScoringMethodologyNotes($weightScoringMethodologyNotes);
        $this->weightScoringMethodologyNotes = $weightScoringMethodologyNotes;
        return $this;
    }

    public function addToWeightScoringMethodologyNotes(Text $item): self
    {
        $this->weightScoringMethodologyNotes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateWeightScoringMethodologyNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getWeightingTypeCode(): ?Code
    {
        return $this->weightingTypeCode;
    }

    public function setWeightingTypeCode(?Code $weightingTypeCode = null): self
    {
        $this->weightingTypeCode = $weightingTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getNotes(): array
    {
        return $this->notes;
    }

    /**
     * @param list<Text> $notes
     */
    public function setNotes(array $notes): self
    {
        self::validateNotes($notes);
        $this->notes = $notes;
        return $this;
    }

    public function addToNotes(Text $item): self
    {
        $this->notes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ContractingParty>
     */
    public function getContractingParties(): array
    {
        return $this->contractingParties;
    }

    /**
     * @param list<ContractingParty> $contractingParties
     */
    public function setContractingParties(array $contractingParties): self
    {
        self::validateContractingParties($contractingParties);
        $this->contractingParties = $contractingParties;
        return $this;
    }

    public function addToContractingParties(ContractingParty $item): self
    {
        $this->contractingParties[] = $item;
        return $this;
    }

    /**
     * @param list<ContractingParty> $values
     */
    private static function validateContractingParties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ContractingParty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ContractingParty, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<EconomicOperatorParty>
     */
    public function getEconomicOperatorParties(): array
    {
        return $this->economicOperatorParties;
    }

    /**
     * @param list<EconomicOperatorParty> $economicOperatorParties
     */
    public function setEconomicOperatorParties(array $economicOperatorParties): self
    {
        self::validateEconomicOperatorParties($economicOperatorParties);
        $this->economicOperatorParties = $economicOperatorParties;
        return $this;
    }

    public function addToEconomicOperatorParties(EconomicOperatorParty $item): self
    {
        $this->economicOperatorParties[] = $item;
        return $this;
    }

    /**
     * @param list<EconomicOperatorParty> $values
     */
    private static function validateEconomicOperatorParties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof EconomicOperatorParty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of EconomicOperatorParty, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getProcurementProject(): ?ProcurementProject
    {
        return $this->procurementProject;
    }

    public function setProcurementProject(?ProcurementProject $procurementProject = null): self
    {
        $this->procurementProject = $procurementProject;
        return $this;
    }

    /**
     * @return list<ProcurementProjectLot>
     */
    public function getProcurementProjectLots(): array
    {
        return $this->procurementProjectLots;
    }

    /**
     * @param list<ProcurementProjectLot> $procurementProjectLots
     */
    public function setProcurementProjectLots(array $procurementProjectLots): self
    {
        self::validateProcurementProjectLots($procurementProjectLots);
        $this->procurementProjectLots = $procurementProjectLots;
        return $this;
    }

    public function addToProcurementProjectLots(ProcurementProjectLot $item): self
    {
        $this->procurementProjectLots[] = $item;
        return $this;
    }

    /**
     * @param list<ProcurementProjectLot> $values
     */
    private static function validateProcurementProjectLots(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ProcurementProjectLot) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ProcurementProjectLot, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<TenderingCriterion>
     */
    public function getTenderingCriterions(): array
    {
        return $this->tenderingCriterions;
    }

    /**
     * @param list<TenderingCriterion> $tenderingCriterions
     */
    public function setTenderingCriterions(array $tenderingCriterions): self
    {
        self::validateTenderingCriterions($tenderingCriterions);
        $this->tenderingCriterions = $tenderingCriterions;
        return $this;
    }

    public function addToTenderingCriterions(TenderingCriterion $item): self
    {
        $this->tenderingCriterions[] = $item;
        return $this;
    }

    /**
     * @param list<TenderingCriterion> $values
     */
    private static function validateTenderingCriterions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TenderingCriterion) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TenderingCriterion, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<TenderingCriterionResponse>
     */
    public function getTenderingCriterionResponses(): array
    {
        return $this->tenderingCriterionResponses;
    }

    /**
     * @param list<TenderingCriterionResponse> $tenderingCriterionResponses
     */
    public function setTenderingCriterionResponses(array $tenderingCriterionResponses): self
    {
        self::validateTenderingCriterionResponses($tenderingCriterionResponses);
        $this->tenderingCriterionResponses = $tenderingCriterionResponses;
        return $this;
    }

    public function addToTenderingCriterionResponses(TenderingCriterionResponse $item): self
    {
        $this->tenderingCriterionResponses[] = $item;
        return $this;
    }

    /**
     * @param list<TenderingCriterionResponse> $values
     */
    private static function validateTenderingCriterionResponses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TenderingCriterionResponse) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TenderingCriterionResponse, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<DocumentReference>
     */
    public function getAdditionalDocumentReferences(): array
    {
        return $this->additionalDocumentReferences;
    }

    /**
     * @param list<DocumentReference> $additionalDocumentReferences
     */
    public function setAdditionalDocumentReferences(array $additionalDocumentReferences): self
    {
        self::validateAdditionalDocumentReferences($additionalDocumentReferences);
        $this->additionalDocumentReferences = $additionalDocumentReferences;
        return $this;
    }

    public function addToAdditionalDocumentReferences(DocumentReference $item): self
    {
        $this->additionalDocumentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateAdditionalDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Evidence>
     */
    public function getEvidences(): array
    {
        return $this->evidences;
    }

    /**
     * @param list<Evidence> $evidences
     */
    public function setEvidences(array $evidences): self
    {
        self::validateEvidences($evidences);
        $this->evidences = $evidences;
        return $this;
    }

    public function addToEvidences(Evidence $item): self
    {
        $this->evidences[] = $item;
        return $this;
    }

    /**
     * @param list<Evidence> $values
     */
    private static function validateEvidences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Evidence) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Evidence, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Signature>
     */
    public function getSignatures(): array
    {
        return $this->signatures;
    }

    /**
     * @param list<Signature> $signatures
     */
    public function setSignatures(array $signatures): self
    {
        self::validateSignatures($signatures);
        $this->signatures = $signatures;
        return $this;
    }

    public function addToSignatures(Signature $item): self
    {
        $this->signatures[] = $item;
        return $this;
    }

    /**
     * @param list<Signature> $values
     */
    private static function validateSignatures(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Signature) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Signature, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
