<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Activity Property. Details
 *  A class to define a name/value pair for a property of an inventory planning activity.
 *  Activity Property
 */
#[XmlType(localName: 'ActivityPropertyType', namespace: Ns::CAC)]
final class ActivityProperty
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC, required: true)]
    private Text $name;

    #[XmlElement(name: 'Value', namespace: Ns::CBC, required: true)]
    private Text $value;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getName(): Text
    {
        return $this->name;
    }

    public function setName(Text $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getValue(): Text
    {
        return $this->value;
    }

    public function setValue(Text $value): self
    {
        $this->value = $value;
        return $this;
    }
}
