<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\BinaryObject;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Attachment. Details
 *  A class to describe an attached document. An attachment can refer to an external document or be included with the document being exchanged.
 *  Attachment
 */
#[XmlType(localName: 'AttachmentType', namespace: Ns::CAC)]
final class Attachment
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'EmbeddedDocumentBinaryObject', namespace: Ns::CBC)]
    private ?BinaryObject $embeddedDocumentBinaryObject = null;

    #[XmlElement(name: 'EmbeddedDocument', namespace: Ns::CBC)]
    private ?Text $embeddedDocument = null;

    #[XmlElement(name: 'ExternalReference', namespace: Ns::CAC)]
    private ?ExternalReference $externalReference = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getEmbeddedDocumentBinaryObject(): ?BinaryObject
    {
        return $this->embeddedDocumentBinaryObject;
    }

    public function setEmbeddedDocumentBinaryObject(?BinaryObject $embeddedDocumentBinaryObject = null): self
    {
        $this->embeddedDocumentBinaryObject = $embeddedDocumentBinaryObject;
        return $this;
    }

    public function getEmbeddedDocument(): ?Text
    {
        return $this->embeddedDocument;
    }

    public function setEmbeddedDocument(?Text $embeddedDocument = null): self
    {
        $this->embeddedDocument = $embeddedDocument;
        return $this;
    }

    public function getExternalReference(): ?ExternalReference
    {
        return $this->externalReference;
    }

    public function setExternalReference(?ExternalReference $externalReference = null): self
    {
        $this->externalReference = $externalReference;
        return $this;
    }
}
