<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Attestation. Details
 *  A class describing an attestation made for an item
 *  Attestation
 */
#[XmlType(localName: 'AttestationType', namespace: Ns::CAC)]
final class Attestation
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Note', namespace: Ns::CBC, type: Text::class)]
    private array $notes = [];

    #[XmlElement(name: 'AcceptanceIndicator', namespace: Ns::CBC)]
    private ?bool $acceptanceIndicator = null;

    #[XmlElement(name: 'ValidityPeriod', namespace: Ns::CAC)]
    private ?Period $validityPeriod = null;

    #[XmlElement(name: 'IssuerParty', namespace: Ns::CAC)]
    private ?Party $issuerParty = null;

    /** @var list<AttestationLine> */
    #[XmlElement(name: 'AttestationLine', namespace: Ns::CAC, type: AttestationLine::class, required: true)]
    private array $attestationLines = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getNotes(): array
    {
        return $this->notes;
    }

    /**
     * @param list<Text> $notes
     */
    public function setNotes(array $notes): self
    {
        self::validateNotes($notes);
        $this->notes = $notes;
        return $this;
    }

    public function addToNotes(Text $item): self
    {
        $this->notes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getAcceptanceIndicator(): ?bool
    {
        return $this->acceptanceIndicator;
    }

    public function setAcceptanceIndicator(?bool $acceptanceIndicator = null): self
    {
        $this->acceptanceIndicator = $acceptanceIndicator;
        return $this;
    }

    public function getValidityPeriod(): ?Period
    {
        return $this->validityPeriod;
    }

    public function setValidityPeriod(?Period $validityPeriod = null): self
    {
        $this->validityPeriod = $validityPeriod;
        return $this;
    }

    public function getIssuerParty(): ?Party
    {
        return $this->issuerParty;
    }

    public function setIssuerParty(?Party $issuerParty = null): self
    {
        $this->issuerParty = $issuerParty;
        return $this;
    }

    /**
     * @return list<AttestationLine>
     */
    public function getAttestationLines(): array
    {
        return $this->attestationLines;
    }

    /**
     * @param list<AttestationLine> $attestationLines
     */
    public function setAttestationLines(array $attestationLines): self
    {
        self::validateAttestationLines($attestationLines);
        $this->attestationLines = $attestationLines;
        return $this;
    }

    public function addToAttestationLines(AttestationLine $item): self
    {
        $this->attestationLines[] = $item;
        return $this;
    }

    /**
     * @param list<AttestationLine> $values
     */
    private static function validateAttestationLines(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof AttestationLine) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of AttestationLine, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
