<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Auction Terms. Details
 *  A class to describe the terms to be fulfilled by tenderers if an auction is to be executed before the awarding of a tender.
 *  Auction Terms
 */
#[XmlType(localName: 'AuctionTermsType', namespace: Ns::CAC)]
final class AuctionTerms
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'AuctionConstraintIndicator', namespace: Ns::CBC)]
    private ?bool $auctionConstraintIndicator = null;

    /** @var list<Text> */
    #[XmlElement(name: 'JustificationDescription', namespace: Ns::CBC, type: Text::class)]
    private array $justificationDescriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'ProcessDescription', namespace: Ns::CBC, type: Text::class)]
    private array $processDescriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'ConditionsDescription', namespace: Ns::CBC, type: Text::class)]
    private array $conditionsDescriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'ElectronicDeviceDescription', namespace: Ns::CBC, type: Text::class)]
    private array $electronicDeviceDescriptions = [];

    #[XmlElement(name: 'AuctionURI', namespace: Ns::CBC)]
    private ?Identifier $auctionURI = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getAuctionConstraintIndicator(): ?bool
    {
        return $this->auctionConstraintIndicator;
    }

    public function setAuctionConstraintIndicator(?bool $auctionConstraintIndicator = null): self
    {
        $this->auctionConstraintIndicator = $auctionConstraintIndicator;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getJustificationDescriptions(): array
    {
        return $this->justificationDescriptions;
    }

    /**
     * @param list<Text> $justificationDescriptions
     */
    public function setJustificationDescriptions(array $justificationDescriptions): self
    {
        self::validateJustificationDescriptions($justificationDescriptions);
        $this->justificationDescriptions = $justificationDescriptions;
        return $this;
    }

    public function addToJustificationDescriptions(Text $item): self
    {
        $this->justificationDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateJustificationDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getProcessDescriptions(): array
    {
        return $this->processDescriptions;
    }

    /**
     * @param list<Text> $processDescriptions
     */
    public function setProcessDescriptions(array $processDescriptions): self
    {
        self::validateProcessDescriptions($processDescriptions);
        $this->processDescriptions = $processDescriptions;
        return $this;
    }

    public function addToProcessDescriptions(Text $item): self
    {
        $this->processDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateProcessDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getConditionsDescriptions(): array
    {
        return $this->conditionsDescriptions;
    }

    /**
     * @param list<Text> $conditionsDescriptions
     */
    public function setConditionsDescriptions(array $conditionsDescriptions): self
    {
        self::validateConditionsDescriptions($conditionsDescriptions);
        $this->conditionsDescriptions = $conditionsDescriptions;
        return $this;
    }

    public function addToConditionsDescriptions(Text $item): self
    {
        $this->conditionsDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateConditionsDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getElectronicDeviceDescriptions(): array
    {
        return $this->electronicDeviceDescriptions;
    }

    /**
     * @param list<Text> $electronicDeviceDescriptions
     */
    public function setElectronicDeviceDescriptions(array $electronicDeviceDescriptions): self
    {
        self::validateElectronicDeviceDescriptions($electronicDeviceDescriptions);
        $this->electronicDeviceDescriptions = $electronicDeviceDescriptions;
        return $this;
    }

    public function addToElectronicDeviceDescriptions(Text $item): self
    {
        $this->electronicDeviceDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateElectronicDeviceDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getAuctionURI(): ?Identifier
    {
        return $this->auctionURI;
    }

    public function setAuctionURI(?Identifier $auctionURI = null): self
    {
        $this->auctionURI = $auctionURI;
        return $this;
    }
}
