<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Billing Reference. Details
 *  A class to define a reference to a billing document.
 *  Billing Reference
 */
#[XmlType(localName: 'BillingReferenceType', namespace: Ns::CAC)]
final class BillingReference
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'InvoiceDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $invoiceDocumentReference = null;

    #[XmlElement(name: 'SelfBilledInvoiceDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $selfBilledInvoiceDocumentReference = null;

    #[XmlElement(name: 'CreditNoteDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $creditNoteDocumentReference = null;

    #[XmlElement(name: 'SelfBilledCreditNoteDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $selfBilledCreditNoteDocumentReference = null;

    #[XmlElement(name: 'DebitNoteDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $debitNoteDocumentReference = null;

    #[XmlElement(name: 'ReminderDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $reminderDocumentReference = null;

    #[XmlElement(name: 'AdditionalDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $additionalDocumentReference = null;

    /** @var list<BillingReferenceLine> */
    #[XmlElement(name: 'BillingReferenceLine', namespace: Ns::CAC, type: BillingReferenceLine::class)]
    private array $billingReferenceLines = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getInvoiceDocumentReference(): ?DocumentReference
    {
        return $this->invoiceDocumentReference;
    }

    public function setInvoiceDocumentReference(?DocumentReference $invoiceDocumentReference = null): self
    {
        $this->invoiceDocumentReference = $invoiceDocumentReference;
        return $this;
    }

    public function getSelfBilledInvoiceDocumentReference(): ?DocumentReference
    {
        return $this->selfBilledInvoiceDocumentReference;
    }

    public function setSelfBilledInvoiceDocumentReference(
        ?DocumentReference $selfBilledInvoiceDocumentReference = null,
    ): self {
        $this->selfBilledInvoiceDocumentReference = $selfBilledInvoiceDocumentReference;
        return $this;
    }

    public function getCreditNoteDocumentReference(): ?DocumentReference
    {
        return $this->creditNoteDocumentReference;
    }

    public function setCreditNoteDocumentReference(?DocumentReference $creditNoteDocumentReference = null): self
    {
        $this->creditNoteDocumentReference = $creditNoteDocumentReference;
        return $this;
    }

    public function getSelfBilledCreditNoteDocumentReference(): ?DocumentReference
    {
        return $this->selfBilledCreditNoteDocumentReference;
    }

    public function setSelfBilledCreditNoteDocumentReference(
        ?DocumentReference $selfBilledCreditNoteDocumentReference = null,
    ): self {
        $this->selfBilledCreditNoteDocumentReference = $selfBilledCreditNoteDocumentReference;
        return $this;
    }

    public function getDebitNoteDocumentReference(): ?DocumentReference
    {
        return $this->debitNoteDocumentReference;
    }

    public function setDebitNoteDocumentReference(?DocumentReference $debitNoteDocumentReference = null): self
    {
        $this->debitNoteDocumentReference = $debitNoteDocumentReference;
        return $this;
    }

    public function getReminderDocumentReference(): ?DocumentReference
    {
        return $this->reminderDocumentReference;
    }

    public function setReminderDocumentReference(?DocumentReference $reminderDocumentReference = null): self
    {
        $this->reminderDocumentReference = $reminderDocumentReference;
        return $this;
    }

    public function getAdditionalDocumentReference(): ?DocumentReference
    {
        return $this->additionalDocumentReference;
    }

    public function setAdditionalDocumentReference(?DocumentReference $additionalDocumentReference = null): self
    {
        $this->additionalDocumentReference = $additionalDocumentReference;
        return $this;
    }

    /**
     * @return list<BillingReferenceLine>
     */
    public function getBillingReferenceLines(): array
    {
        return $this->billingReferenceLines;
    }

    /**
     * @param list<BillingReferenceLine> $billingReferenceLines
     */
    public function setBillingReferenceLines(array $billingReferenceLines): self
    {
        self::validateBillingReferenceLines($billingReferenceLines);
        $this->billingReferenceLines = $billingReferenceLines;
        return $this;
    }

    public function addToBillingReferenceLines(BillingReferenceLine $item): self
    {
        $this->billingReferenceLines[] = $item;
        return $this;
    }

    /**
     * @param list<BillingReferenceLine> $values
     */
    private static function validateBillingReferenceLines(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof BillingReferenceLine) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of BillingReferenceLine, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
