<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Numeric;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Budget Account. Details
 *  A class to define a budget account.
 *  Budget Account
 */
#[XmlType(localName: 'BudgetAccountType', namespace: Ns::CAC)]
final class BudgetAccount
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'BudgetYearNumeric', namespace: Ns::CBC)]
    private ?Numeric $budgetYearNumeric = null;

    #[XmlElement(name: 'RequiredClassificationScheme', namespace: Ns::CAC)]
    private ?ClassificationScheme $requiredClassificationScheme = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getBudgetYearNumeric(): ?Numeric
    {
        return $this->budgetYearNumeric;
    }

    public function setBudgetYearNumeric(?Numeric $budgetYearNumeric = null): self
    {
        $this->budgetYearNumeric = $budgetYearNumeric;
        return $this;
    }

    public function getRequiredClassificationScheme(): ?ClassificationScheme
    {
        return $this->requiredClassificationScheme;
    }

    public function setRequiredClassificationScheme(?ClassificationScheme $requiredClassificationScheme = null): self
    {
        $this->requiredClassificationScheme = $requiredClassificationScheme;
        return $this;
    }
}
