<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Amount;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Capability. Details
 *  A class to describe a specific capability of an organization.
 *  Capability
 */
#[XmlType(localName: 'CapabilityType', namespace: Ns::CAC)]
final class Capability
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'CapabilityTypeCode', namespace: Ns::CBC)]
    private ?Code $capabilityTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'ValueAmount', namespace: Ns::CBC)]
    private ?Amount $valueAmount = null;

    #[XmlElement(name: 'ValueQuantity', namespace: Ns::CBC)]
    private ?Quantity $valueQuantity = null;

    /** @var list<EvidenceSupplied> */
    #[XmlElement(name: 'EvidenceSupplied', namespace: Ns::CAC, type: EvidenceSupplied::class)]
    private array $evidenceSupplieds = [];

    #[XmlElement(name: 'ValidityPeriod', namespace: Ns::CAC)]
    private ?Period $validityPeriod = null;

    #[XmlElement(name: 'WebSite', namespace: Ns::CAC)]
    private ?WebSite $webSite = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getCapabilityTypeCode(): ?Code
    {
        return $this->capabilityTypeCode;
    }

    public function setCapabilityTypeCode(?Code $capabilityTypeCode = null): self
    {
        $this->capabilityTypeCode = $capabilityTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getValueAmount(): ?Amount
    {
        return $this->valueAmount;
    }

    public function setValueAmount(?Amount $valueAmount = null): self
    {
        $this->valueAmount = $valueAmount;
        return $this;
    }

    public function getValueQuantity(): ?Quantity
    {
        return $this->valueQuantity;
    }

    public function setValueQuantity(?Quantity $valueQuantity = null): self
    {
        $this->valueQuantity = $valueQuantity;
        return $this;
    }

    /**
     * @return list<EvidenceSupplied>
     */
    public function getEvidenceSupplieds(): array
    {
        return $this->evidenceSupplieds;
    }

    /**
     * @param list<EvidenceSupplied> $evidenceSupplieds
     */
    public function setEvidenceSupplieds(array $evidenceSupplieds): self
    {
        self::validateEvidenceSupplieds($evidenceSupplieds);
        $this->evidenceSupplieds = $evidenceSupplieds;
        return $this;
    }

    public function addToEvidenceSupplieds(EvidenceSupplied $item): self
    {
        $this->evidenceSupplieds[] = $item;
        return $this;
    }

    /**
     * @param list<EvidenceSupplied> $values
     */
    private static function validateEvidenceSupplieds(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof EvidenceSupplied) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of EvidenceSupplied, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getValidityPeriod(): ?Period
    {
        return $this->validityPeriod;
    }

    public function setValidityPeriod(?Period $validityPeriod = null): self
    {
        $this->validityPeriod = $validityPeriod;
        return $this;
    }

    public function getWebSite(): ?WebSite
    {
        return $this->webSite;
    }

    public function setWebSite(?WebSite $webSite = null): self
    {
        $this->webSite = $webSite;
        return $this;
    }
}
