<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Catalogue Reference. Details
 *  A class to define a reference to a catalogue.
 *  Catalogue Reference
 */
#[XmlType(localName: 'CatalogueReferenceType', namespace: Ns::CAC)]
final class CatalogueReference
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'UUID', namespace: Ns::CBC)]
    private ?Identifier $uuid = null;

    #[XmlElement(name: 'IssueDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $issueDate = null;

    #[XmlElement(name: 'IssueTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $issueTime = null;

    #[XmlElement(name: 'RevisionDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $revisionDate = null;

    #[XmlElement(name: 'RevisionTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $revisionTime = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Note', namespace: Ns::CBC, type: Text::class)]
    private array $notes = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'VersionID', namespace: Ns::CBC)]
    private ?Identifier $versionID = null;

    #[XmlElement(name: 'PreviousVersionID', namespace: Ns::CBC)]
    private ?Identifier $previousVersionID = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getUuid(): ?Identifier
    {
        return $this->uuid;
    }

    public function setUuid(?Identifier $uuid = null): self
    {
        $this->uuid = $uuid;
        return $this;
    }

    public function getIssueDate(): ?DateTimeImmutable
    {
        return $this->issueDate;
    }

    public function setIssueDate(?DateTimeImmutable $issueDate = null): self
    {
        $this->issueDate = $issueDate;
        return $this;
    }

    public function getIssueTime(): ?DateTimeImmutable
    {
        return $this->issueTime;
    }

    public function setIssueTime(?DateTimeImmutable $issueTime = null): self
    {
        $this->issueTime = $issueTime;
        return $this;
    }

    public function getRevisionDate(): ?DateTimeImmutable
    {
        return $this->revisionDate;
    }

    public function setRevisionDate(?DateTimeImmutable $revisionDate = null): self
    {
        $this->revisionDate = $revisionDate;
        return $this;
    }

    public function getRevisionTime(): ?DateTimeImmutable
    {
        return $this->revisionTime;
    }

    public function setRevisionTime(?DateTimeImmutable $revisionTime = null): self
    {
        $this->revisionTime = $revisionTime;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getNotes(): array
    {
        return $this->notes;
    }

    /**
     * @param list<Text> $notes
     */
    public function setNotes(array $notes): self
    {
        self::validateNotes($notes);
        $this->notes = $notes;
        return $this;
    }

    public function addToNotes(Text $item): self
    {
        $this->notes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getVersionID(): ?Identifier
    {
        return $this->versionID;
    }

    public function setVersionID(?Identifier $versionID = null): self
    {
        $this->versionID = $versionID;
        return $this;
    }

    public function getPreviousVersionID(): ?Identifier
    {
        return $this->previousVersionID;
    }

    public function setPreviousVersionID(?Identifier $previousVersionID = null): self
    {
        $this->previousVersionID = $previousVersionID;
        return $this;
    }
}
