<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Catalogue Item Specification Update Line. Details
 *  A class to define a line describing the transaction that updates the specification of an item in a catalogue.
 *  Catalogue Item Specification Update Line
 */
#[XmlType(localName: 'CatalogueItemSpecificationUpdateLineType', namespace: Ns::CAC)]
final class CatalogueItemSpecificationUpdateLine
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'ContractorCustomerParty', namespace: Ns::CAC)]
    private ?CustomerParty $contractorCustomerParty = null;

    #[XmlElement(name: 'SellerSupplierParty', namespace: Ns::CAC)]
    private ?SupplierParty $sellerSupplierParty = null;

    #[XmlElement(name: 'Item', namespace: Ns::CAC, required: true)]
    private Item $item;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getContractorCustomerParty(): ?CustomerParty
    {
        return $this->contractorCustomerParty;
    }

    public function setContractorCustomerParty(?CustomerParty $contractorCustomerParty = null): self
    {
        $this->contractorCustomerParty = $contractorCustomerParty;
        return $this;
    }

    public function getSellerSupplierParty(): ?SupplierParty
    {
        return $this->sellerSupplierParty;
    }

    public function setSellerSupplierParty(?SupplierParty $sellerSupplierParty = null): self
    {
        $this->sellerSupplierParty = $sellerSupplierParty;
        return $this;
    }

    public function getItem(): Item
    {
        return $this->item;
    }

    public function setItem(Item $item): self
    {
        $this->item = $item;
        return $this;
    }
}
