<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Classification Category. Details
 *  A class to define a category within a classification scheme.
 *  Classification Category
 */
#[XmlType(localName: 'ClassificationCategoryType', namespace: Ns::CAC)]
final class ClassificationCategory
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'CodeValue', namespace: Ns::CBC)]
    private ?Text $codeValue = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    /** @var list<ClassificationCategory> */
    #[XmlElement(name: 'CategorizesClassificationCategory', namespace: Ns::CAC, type: ClassificationCategory::class)]
    private array $categorizesClassificationCategories = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getCodeValue(): ?Text
    {
        return $this->codeValue;
    }

    public function setCodeValue(?Text $codeValue = null): self
    {
        $this->codeValue = $codeValue;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ClassificationCategory>
     */
    public function getCategorizesClassificationCategories(): array
    {
        return $this->categorizesClassificationCategories;
    }

    /**
     * @param list<ClassificationCategory> $categorizesClassificationCategories
     */
    public function setCategorizesClassificationCategories(array $categorizesClassificationCategories): self
    {
        self::validateCategorizesClassificationCategories($categorizesClassificationCategories);
        $this->categorizesClassificationCategories = $categorizesClassificationCategories;
        return $this;
    }

    public function addToCategorizesClassificationCategories(ClassificationCategory $item): self
    {
        $this->categorizesClassificationCategories[] = $item;
        return $this;
    }

    /**
     * @param list<ClassificationCategory> $values
     */
    private static function validateCategorizesClassificationCategories(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ClassificationCategory) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ClassificationCategory, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
