<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Communication. Details
 *  A class to describe a means of communication.
 *  Communication
 */
#[XmlType(localName: 'CommunicationType', namespace: Ns::CAC)]
final class Communication
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ChannelCode', namespace: Ns::CBC)]
    private ?Code $channelCode = null;

    #[XmlElement(name: 'Channel', namespace: Ns::CBC)]
    private ?Text $channel = null;

    #[XmlElement(name: 'Value', namespace: Ns::CBC)]
    private ?Text $value = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getChannelCode(): ?Code
    {
        return $this->channelCode;
    }

    public function setChannelCode(?Code $channelCode = null): self
    {
        $this->channelCode = $channelCode;
        return $this;
    }

    public function getChannel(): ?Text
    {
        return $this->channel;
    }

    public function setChannel(?Text $channel = null): self
    {
        $this->channel = $channel;
        return $this;
    }

    public function getValue(): ?Text
    {
        return $this->value;
    }

    public function setValue(?Text $value = null): self
    {
        $this->value = $value;
        return $this;
    }
}
