<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Commodity Classification. Details
 *  A class to describe the classification of a commodity.
 *  Commodity Classification
 */
#[XmlType(localName: 'CommodityClassificationType', namespace: Ns::CAC)]
final class CommodityClassification
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'NatureCode', namespace: Ns::CBC)]
    private ?Code $natureCode = null;

    #[XmlElement(name: 'CargoTypeCode', namespace: Ns::CBC)]
    private ?Code $cargoTypeCode = null;

    #[XmlElement(name: 'CommodityCode', namespace: Ns::CBC)]
    private ?Code $commodityCode = null;

    #[XmlElement(name: 'ItemClassificationCode', namespace: Ns::CBC)]
    private ?Code $itemClassificationCode = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getNatureCode(): ?Code
    {
        return $this->natureCode;
    }

    public function setNatureCode(?Code $natureCode = null): self
    {
        $this->natureCode = $natureCode;
        return $this;
    }

    public function getCargoTypeCode(): ?Code
    {
        return $this->cargoTypeCode;
    }

    public function setCargoTypeCode(?Code $cargoTypeCode = null): self
    {
        $this->cargoTypeCode = $cargoTypeCode;
        return $this;
    }

    public function getCommodityCode(): ?Code
    {
        return $this->commodityCode;
    }

    public function setCommodityCode(?Code $commodityCode = null): self
    {
        $this->commodityCode = $commodityCode;
        return $this;
    }

    public function getItemClassificationCode(): ?Code
    {
        return $this->itemClassificationCode;
    }

    public function setItemClassificationCode(?Code $itemClassificationCode = null): self
    {
        $this->itemClassificationCode = $itemClassificationCode;
        return $this;
    }
}
