<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Numeric;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Consumption Report. Details
 *  A class to describe utility consumption, including details of the environment in which consumption takes place.
 *  Consumption Report
 */
#[XmlType(localName: 'ConsumptionReportType', namespace: Ns::CAC)]
final class ConsumptionReport
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'ConsumptionType', namespace: Ns::CBC)]
    private ?Text $consumptionType = null;

    #[XmlElement(name: 'ConsumptionTypeCode', namespace: Ns::CBC)]
    private ?Code $consumptionTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'TotalConsumedQuantity', namespace: Ns::CBC)]
    private ?Quantity $totalConsumedQuantity = null;

    #[XmlElement(name: 'BasicConsumedQuantity', namespace: Ns::CBC)]
    private ?Quantity $basicConsumedQuantity = null;

    #[XmlElement(name: 'ResidentOccupantsNumeric', namespace: Ns::CBC)]
    private ?Numeric $residentOccupantsNumeric = null;

    #[XmlElement(name: 'ConsumersEnergyLevelCode', namespace: Ns::CBC)]
    private ?Code $consumersEnergyLevelCode = null;

    #[XmlElement(name: 'ConsumersEnergyLevel', namespace: Ns::CBC)]
    private ?Text $consumersEnergyLevel = null;

    #[XmlElement(name: 'ResidenceType', namespace: Ns::CBC)]
    private ?Text $residenceType = null;

    #[XmlElement(name: 'ResidenceTypeCode', namespace: Ns::CBC)]
    private ?Code $residenceTypeCode = null;

    #[XmlElement(name: 'HeatingType', namespace: Ns::CBC)]
    private ?Text $heatingType = null;

    #[XmlElement(name: 'HeatingTypeCode', namespace: Ns::CBC)]
    private ?Code $heatingTypeCode = null;

    #[XmlElement(name: 'Period', namespace: Ns::CAC)]
    private ?Period $period = null;

    #[XmlElement(name: 'GuidanceDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $guidanceDocumentReference = null;

    #[XmlElement(name: 'DocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $documentReference = null;

    /** @var list<ConsumptionReportReference> */
    #[XmlElement(name: 'ConsumptionReportReference', namespace: Ns::CAC, type: ConsumptionReportReference::class)]
    private array $consumptionReportReferences = [];

    /** @var list<ConsumptionHistory> */
    #[XmlElement(name: 'ConsumptionHistory', namespace: Ns::CAC, type: ConsumptionHistory::class)]
    private array $consumptionHistories = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getConsumptionType(): ?Text
    {
        return $this->consumptionType;
    }

    public function setConsumptionType(?Text $consumptionType = null): self
    {
        $this->consumptionType = $consumptionType;
        return $this;
    }

    public function getConsumptionTypeCode(): ?Code
    {
        return $this->consumptionTypeCode;
    }

    public function setConsumptionTypeCode(?Code $consumptionTypeCode = null): self
    {
        $this->consumptionTypeCode = $consumptionTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getTotalConsumedQuantity(): ?Quantity
    {
        return $this->totalConsumedQuantity;
    }

    public function setTotalConsumedQuantity(?Quantity $totalConsumedQuantity = null): self
    {
        $this->totalConsumedQuantity = $totalConsumedQuantity;
        return $this;
    }

    public function getBasicConsumedQuantity(): ?Quantity
    {
        return $this->basicConsumedQuantity;
    }

    public function setBasicConsumedQuantity(?Quantity $basicConsumedQuantity = null): self
    {
        $this->basicConsumedQuantity = $basicConsumedQuantity;
        return $this;
    }

    public function getResidentOccupantsNumeric(): ?Numeric
    {
        return $this->residentOccupantsNumeric;
    }

    public function setResidentOccupantsNumeric(?Numeric $residentOccupantsNumeric = null): self
    {
        $this->residentOccupantsNumeric = $residentOccupantsNumeric;
        return $this;
    }

    public function getConsumersEnergyLevelCode(): ?Code
    {
        return $this->consumersEnergyLevelCode;
    }

    public function setConsumersEnergyLevelCode(?Code $consumersEnergyLevelCode = null): self
    {
        $this->consumersEnergyLevelCode = $consumersEnergyLevelCode;
        return $this;
    }

    public function getConsumersEnergyLevel(): ?Text
    {
        return $this->consumersEnergyLevel;
    }

    public function setConsumersEnergyLevel(?Text $consumersEnergyLevel = null): self
    {
        $this->consumersEnergyLevel = $consumersEnergyLevel;
        return $this;
    }

    public function getResidenceType(): ?Text
    {
        return $this->residenceType;
    }

    public function setResidenceType(?Text $residenceType = null): self
    {
        $this->residenceType = $residenceType;
        return $this;
    }

    public function getResidenceTypeCode(): ?Code
    {
        return $this->residenceTypeCode;
    }

    public function setResidenceTypeCode(?Code $residenceTypeCode = null): self
    {
        $this->residenceTypeCode = $residenceTypeCode;
        return $this;
    }

    public function getHeatingType(): ?Text
    {
        return $this->heatingType;
    }

    public function setHeatingType(?Text $heatingType = null): self
    {
        $this->heatingType = $heatingType;
        return $this;
    }

    public function getHeatingTypeCode(): ?Code
    {
        return $this->heatingTypeCode;
    }

    public function setHeatingTypeCode(?Code $heatingTypeCode = null): self
    {
        $this->heatingTypeCode = $heatingTypeCode;
        return $this;
    }

    public function getPeriod(): ?Period
    {
        return $this->period;
    }

    public function setPeriod(?Period $period = null): self
    {
        $this->period = $period;
        return $this;
    }

    public function getGuidanceDocumentReference(): ?DocumentReference
    {
        return $this->guidanceDocumentReference;
    }

    public function setGuidanceDocumentReference(?DocumentReference $guidanceDocumentReference = null): self
    {
        $this->guidanceDocumentReference = $guidanceDocumentReference;
        return $this;
    }

    public function getDocumentReference(): ?DocumentReference
    {
        return $this->documentReference;
    }

    public function setDocumentReference(?DocumentReference $documentReference = null): self
    {
        $this->documentReference = $documentReference;
        return $this;
    }

    /**
     * @return list<ConsumptionReportReference>
     */
    public function getConsumptionReportReferences(): array
    {
        return $this->consumptionReportReferences;
    }

    /**
     * @param list<ConsumptionReportReference> $consumptionReportReferences
     */
    public function setConsumptionReportReferences(array $consumptionReportReferences): self
    {
        self::validateConsumptionReportReferences($consumptionReportReferences);
        $this->consumptionReportReferences = $consumptionReportReferences;
        return $this;
    }

    public function addToConsumptionReportReferences(ConsumptionReportReference $item): self
    {
        $this->consumptionReportReferences[] = $item;
        return $this;
    }

    /**
     * @param list<ConsumptionReportReference> $values
     */
    private static function validateConsumptionReportReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ConsumptionReportReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ConsumptionReportReference, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ConsumptionHistory>
     */
    public function getConsumptionHistories(): array
    {
        return $this->consumptionHistories;
    }

    /**
     * @param list<ConsumptionHistory> $consumptionHistories
     */
    public function setConsumptionHistories(array $consumptionHistories): self
    {
        self::validateConsumptionHistories($consumptionHistories);
        $this->consumptionHistories = $consumptionHistories;
        return $this;
    }

    public function addToConsumptionHistories(ConsumptionHistory $item): self
    {
        $this->consumptionHistories[] = $item;
        return $this;
    }

    /**
     * @param list<ConsumptionHistory> $values
     */
    private static function validateConsumptionHistories(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ConsumptionHistory) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ConsumptionHistory, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
