<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Amount;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Measure;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Consignment. Details
 *  A class to describe an identifiable collection of one or more goods items to be transported between the consignor and the consignee. This information may be defined within a transport contract. A consignment may comprise more than one shipment (e.g., when consolidated by a freight forwarder).
 *  Consignment
 */
#[XmlType(localName: 'ConsignmentType', namespace: Ns::CAC)]
final class Consignment
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'CarrierAssignedID', namespace: Ns::CBC)]
    private ?Identifier $carrierAssignedID = null;

    #[XmlElement(name: 'ConsigneeAssignedID', namespace: Ns::CBC)]
    private ?Identifier $consigneeAssignedID = null;

    #[XmlElement(name: 'ConsignorAssignedID', namespace: Ns::CBC)]
    private ?Identifier $consignorAssignedID = null;

    #[XmlElement(name: 'FreightForwarderAssignedID', namespace: Ns::CBC)]
    private ?Identifier $freightForwarderAssignedID = null;

    #[XmlElement(name: 'BrokerAssignedID', namespace: Ns::CBC)]
    private ?Identifier $brokerAssignedID = null;

    #[XmlElement(name: 'ContractedCarrierAssignedID', namespace: Ns::CBC)]
    private ?Identifier $contractedCarrierAssignedID = null;

    #[XmlElement(name: 'PerformingCarrierAssignedID', namespace: Ns::CBC)]
    private ?Identifier $performingCarrierAssignedID = null;

    /** @var list<Text> */
    #[XmlElement(name: 'SummaryDescription', namespace: Ns::CBC, type: Text::class)]
    private array $summaryDescriptions = [];

    #[XmlElement(name: 'TotalInvoiceAmount', namespace: Ns::CBC)]
    private ?Amount $totalInvoiceAmount = null;

    #[XmlElement(name: 'DeclaredCustomsValueAmount', namespace: Ns::CBC)]
    private ?Amount $declaredCustomsValueAmount = null;

    /** @var list<Text> */
    #[XmlElement(name: 'TariffDescription', namespace: Ns::CBC, type: Text::class)]
    private array $tariffDescriptions = [];

    #[XmlElement(name: 'TariffCode', namespace: Ns::CBC)]
    private ?Code $tariffCode = null;

    #[XmlElement(name: 'InsurancePremiumAmount', namespace: Ns::CBC)]
    private ?Amount $insurancePremiumAmount = null;

    #[XmlElement(name: 'GrossWeightMeasure', namespace: Ns::CBC)]
    private ?Measure $grossWeightMeasure = null;

    #[XmlElement(name: 'NetWeightMeasure', namespace: Ns::CBC)]
    private ?Measure $netWeightMeasure = null;

    #[XmlElement(name: 'NetNetWeightMeasure', namespace: Ns::CBC)]
    private ?Measure $netNetWeightMeasure = null;

    #[XmlElement(name: 'ChargeableWeightMeasure', namespace: Ns::CBC)]
    private ?Measure $chargeableWeightMeasure = null;

    #[XmlElement(name: 'GrossVolumeMeasure', namespace: Ns::CBC)]
    private ?Measure $grossVolumeMeasure = null;

    #[XmlElement(name: 'NetVolumeMeasure', namespace: Ns::CBC)]
    private ?Measure $netVolumeMeasure = null;

    #[XmlElement(name: 'LoadingLengthMeasure', namespace: Ns::CBC)]
    private ?Measure $loadingLengthMeasure = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Remarks', namespace: Ns::CBC, type: Text::class)]
    private array $remarkses = [];

    #[XmlElement(name: 'HazardousRiskIndicator', namespace: Ns::CBC)]
    private ?bool $hazardousRiskIndicator = null;

    #[XmlElement(name: 'AnimalFoodIndicator', namespace: Ns::CBC)]
    private ?bool $animalFoodIndicator = null;

    #[XmlElement(name: 'HumanFoodIndicator', namespace: Ns::CBC)]
    private ?bool $humanFoodIndicator = null;

    #[XmlElement(name: 'LivestockIndicator', namespace: Ns::CBC)]
    private ?bool $livestockIndicator = null;

    #[XmlElement(name: 'BulkCargoIndicator', namespace: Ns::CBC)]
    private ?bool $bulkCargoIndicator = null;

    #[XmlElement(name: 'ContainerizedIndicator', namespace: Ns::CBC)]
    private ?bool $containerizedIndicator = null;

    #[XmlElement(name: 'GeneralCargoIndicator', namespace: Ns::CBC)]
    private ?bool $generalCargoIndicator = null;

    #[XmlElement(name: 'SpecialSecurityIndicator', namespace: Ns::CBC)]
    private ?bool $specialSecurityIndicator = null;

    #[XmlElement(name: 'ThirdPartyPayerIndicator', namespace: Ns::CBC)]
    private ?bool $thirdPartyPayerIndicator = null;

    /** @var list<Text> */
    #[XmlElement(name: 'CarrierServiceInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $carrierServiceInstructionses = [];

    /** @var list<Text> */
    #[XmlElement(name: 'CustomsClearanceServiceInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $customsClearanceServiceInstructionses = [];

    /** @var list<Text> */
    #[XmlElement(name: 'ForwarderServiceInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $forwarderServiceInstructionses = [];

    /** @var list<Text> */
    #[XmlElement(name: 'SpecialServiceInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $specialServiceInstructionses = [];

    #[XmlElement(name: 'SequenceID', namespace: Ns::CBC)]
    private ?Identifier $sequenceID = null;

    #[XmlElement(name: 'ShippingPriorityLevelCode', namespace: Ns::CBC)]
    private ?Code $shippingPriorityLevelCode = null;

    #[XmlElement(name: 'HandlingCode', namespace: Ns::CBC)]
    private ?Code $handlingCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'HandlingInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $handlingInstructionses = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Information', namespace: Ns::CBC, type: Text::class)]
    private array $informations = [];

    #[XmlElement(name: 'TotalGoodsItemQuantity', namespace: Ns::CBC)]
    private ?Quantity $totalGoodsItemQuantity = null;

    #[XmlElement(name: 'TotalTransportHandlingUnitQuantity', namespace: Ns::CBC)]
    private ?Quantity $totalTransportHandlingUnitQuantity = null;

    #[XmlElement(name: 'InsuranceValueAmount', namespace: Ns::CBC)]
    private ?Amount $insuranceValueAmount = null;

    #[XmlElement(name: 'DeclaredForCarriageValueAmount', namespace: Ns::CBC)]
    private ?Amount $declaredForCarriageValueAmount = null;

    #[XmlElement(name: 'DeclaredStatisticsValueAmount', namespace: Ns::CBC)]
    private ?Amount $declaredStatisticsValueAmount = null;

    #[XmlElement(name: 'FreeOnBoardValueAmount', namespace: Ns::CBC)]
    private ?Amount $freeOnBoardValueAmount = null;

    /** @var list<Text> */
    #[XmlElement(name: 'SpecialInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $specialInstructionses = [];

    #[XmlElement(name: 'SplitConsignmentIndicator', namespace: Ns::CBC)]
    private ?bool $splitConsignmentIndicator = null;

    /** @var list<Text> */
    #[XmlElement(name: 'DeliveryInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $deliveryInstructionses = [];

    #[XmlElement(name: 'ConsignmentQuantity', namespace: Ns::CBC)]
    private ?Quantity $consignmentQuantity = null;

    #[XmlElement(name: 'ConsolidatableIndicator', namespace: Ns::CBC)]
    private ?bool $consolidatableIndicator = null;

    /** @var list<Text> */
    #[XmlElement(name: 'HaulageInstructions', namespace: Ns::CBC, type: Text::class)]
    private array $haulageInstructionses = [];

    #[XmlElement(name: 'LoadingSequenceID', namespace: Ns::CBC)]
    private ?Identifier $loadingSequenceID = null;

    #[XmlElement(name: 'ChildConsignmentQuantity', namespace: Ns::CBC)]
    private ?Quantity $childConsignmentQuantity = null;

    #[XmlElement(name: 'TotalPackagesQuantity', namespace: Ns::CBC)]
    private ?Quantity $totalPackagesQuantity = null;

    /** @var list<Shipment> */
    #[XmlElement(name: 'ConsolidatedShipment', namespace: Ns::CAC, type: Shipment::class)]
    private array $consolidatedShipments = [];

    /** @var list<CustomsDeclaration> */
    #[XmlElement(name: 'CustomsDeclaration', namespace: Ns::CAC, type: CustomsDeclaration::class)]
    private array $customsDeclarations = [];

    #[XmlElement(name: 'RequestedPickupTransportEvent', namespace: Ns::CAC)]
    private ?TransportEvent $requestedPickupTransportEvent = null;

    #[XmlElement(name: 'RequestedDeliveryTransportEvent', namespace: Ns::CAC)]
    private ?TransportEvent $requestedDeliveryTransportEvent = null;

    #[XmlElement(name: 'PlannedPickupTransportEvent', namespace: Ns::CAC)]
    private ?TransportEvent $plannedPickupTransportEvent = null;

    #[XmlElement(name: 'PlannedDeliveryTransportEvent', namespace: Ns::CAC)]
    private ?TransportEvent $plannedDeliveryTransportEvent = null;

    #[XmlElement(name: 'ActualPickupTransportEvent', namespace: Ns::CAC)]
    private ?TransportEvent $actualPickupTransportEvent = null;

    #[XmlElement(name: 'ActualDeliveryTransportEvent', namespace: Ns::CAC)]
    private ?TransportEvent $actualDeliveryTransportEvent = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Status', namespace: Ns::CAC, type: Text::class)]
    private array $statuses = [];

    /** @var list<Consignment> */
    #[XmlElement(name: 'ChildConsignment', namespace: Ns::CAC, type: Consignment::class)]
    private array $childConsignments = [];

    #[XmlElement(name: 'ConsigneeParty', namespace: Ns::CAC)]
    private ?Party $consigneeParty = null;

    #[XmlElement(name: 'ExporterParty', namespace: Ns::CAC)]
    private ?Party $exporterParty = null;

    #[XmlElement(name: 'ConsignorParty', namespace: Ns::CAC)]
    private ?Party $consignorParty = null;

    #[XmlElement(name: 'ImporterParty', namespace: Ns::CAC)]
    private ?Party $importerParty = null;

    #[XmlElement(name: 'CarrierParty', namespace: Ns::CAC)]
    private ?Party $carrierParty = null;

    #[XmlElement(name: 'FreightForwarderParty', namespace: Ns::CAC)]
    private ?Party $freightForwarderParty = null;

    #[XmlElement(name: 'NotifyParty', namespace: Ns::CAC)]
    private ?Party $notifyParty = null;

    #[XmlElement(name: 'OriginalDespatchParty', namespace: Ns::CAC)]
    private ?Party $originalDespatchParty = null;

    #[XmlElement(name: 'FinalDeliveryParty', namespace: Ns::CAC)]
    private ?Party $finalDeliveryParty = null;

    #[XmlElement(name: 'PerformingCarrierParty', namespace: Ns::CAC)]
    private ?Party $performingCarrierParty = null;

    #[XmlElement(name: 'SubstituteCarrierParty', namespace: Ns::CAC)]
    private ?Party $substituteCarrierParty = null;

    #[XmlElement(name: 'LogisticsOperatorParty', namespace: Ns::CAC)]
    private ?Party $logisticsOperatorParty = null;

    #[XmlElement(name: 'TransportAdvisorParty', namespace: Ns::CAC)]
    private ?Party $transportAdvisorParty = null;

    #[XmlElement(name: 'HazardousItemNotificationParty', namespace: Ns::CAC)]
    private ?Party $hazardousItemNotificationParty = null;

    #[XmlElement(name: 'InsuranceParty', namespace: Ns::CAC)]
    private ?Party $insuranceParty = null;

    #[XmlElement(name: 'MortgageHolderParty', namespace: Ns::CAC)]
    private ?Party $mortgageHolderParty = null;

    #[XmlElement(name: 'BillOfLadingHolderParty', namespace: Ns::CAC)]
    private ?Party $billOfLadingHolderParty = null;

    #[XmlElement(name: 'OriginalDepartureCountry', namespace: Ns::CAC)]
    private ?Country $originalDepartureCountry = null;

    #[XmlElement(name: 'FinalDestinationCountry', namespace: Ns::CAC)]
    private ?Country $finalDestinationCountry = null;

    /** @var list<Country> */
    #[XmlElement(name: 'TransitCountry', namespace: Ns::CAC, type: Country::class)]
    private array $transitCountries = [];

    #[XmlElement(name: 'TransportContract', namespace: Ns::CAC)]
    private ?Contract $transportContract = null;

    /** @var list<TransportEvent> */
    #[XmlElement(name: 'TransportEvent', namespace: Ns::CAC, type: TransportEvent::class)]
    private array $transportEvents = [];

    #[XmlElement(name: 'OriginalDespatchTransportationService', namespace: Ns::CAC)]
    private ?TransportationService $originalDespatchTransportationService = null;

    #[XmlElement(name: 'FinalDeliveryTransportationService', namespace: Ns::CAC)]
    private ?TransportationService $finalDeliveryTransportationService = null;

    #[XmlElement(name: 'DeliveryTerms', namespace: Ns::CAC)]
    private ?DeliveryTerms $deliveryTerms = null;

    #[XmlElement(name: 'PaymentTerms', namespace: Ns::CAC)]
    private ?PaymentTerms $paymentTerms = null;

    #[XmlElement(name: 'CollectPaymentTerms', namespace: Ns::CAC)]
    private ?PaymentTerms $collectPaymentTerms = null;

    #[XmlElement(name: 'DisbursementPaymentTerms', namespace: Ns::CAC)]
    private ?PaymentTerms $disbursementPaymentTerms = null;

    #[XmlElement(name: 'PrepaidPaymentTerms', namespace: Ns::CAC)]
    private ?PaymentTerms $prepaidPaymentTerms = null;

    /** @var list<AllowanceCharge> */
    #[XmlElement(name: 'FreightAllowanceCharge', namespace: Ns::CAC, type: AllowanceCharge::class)]
    private array $freightAllowanceCharges = [];

    /** @var list<AllowanceCharge> */
    #[XmlElement(name: 'ExtraAllowanceCharge', namespace: Ns::CAC, type: AllowanceCharge::class)]
    private array $extraAllowanceCharges = [];

    /** @var list<ShipmentStage> */
    #[XmlElement(name: 'MainCarriageShipmentStage', namespace: Ns::CAC, type: ShipmentStage::class)]
    private array $mainCarriageShipmentStages = [];

    /** @var list<ShipmentStage> */
    #[XmlElement(name: 'PreCarriageShipmentStage', namespace: Ns::CAC, type: ShipmentStage::class)]
    private array $preCarriageShipmentStages = [];

    /** @var list<ShipmentStage> */
    #[XmlElement(name: 'OnCarriageShipmentStage', namespace: Ns::CAC, type: ShipmentStage::class)]
    private array $onCarriageShipmentStages = [];

    /** @var list<TransportHandlingUnit> */
    #[XmlElement(name: 'TransportHandlingUnit', namespace: Ns::CAC, type: TransportHandlingUnit::class)]
    private array $transportHandlingUnits = [];

    #[XmlElement(name: 'FirstArrivalPortLocation', namespace: Ns::CAC)]
    private ?Location $firstArrivalPortLocation = null;

    #[XmlElement(name: 'LastExitPortLocation', namespace: Ns::CAC)]
    private ?Location $lastExitPortLocation = null;

    #[XmlElement(name: 'OfficeOfEntryLocation', namespace: Ns::CAC)]
    private ?Location $officeOfEntryLocation = null;

    #[XmlElement(name: 'OfficeOfSubSequentiallyEntryLocation', namespace: Ns::CAC)]
    private ?Location $officeOfSubSequentiallyEntryLocation = null;

    #[XmlElement(name: 'OfficeOfExitLocation', namespace: Ns::CAC)]
    private ?Location $officeOfExitLocation = null;

    #[XmlElement(name: 'OfficeOfDepartureLocation', namespace: Ns::CAC)]
    private ?Location $officeOfDepartureLocation = null;

    #[XmlElement(name: 'OfficeOfDestinationLocation', namespace: Ns::CAC)]
    private ?Location $officeOfDestinationLocation = null;

    #[XmlElement(name: 'OfficeOfImportLocation', namespace: Ns::CAC)]
    private ?Location $officeOfImportLocation = null;

    #[XmlElement(name: 'OfficeOfExportLocation', namespace: Ns::CAC)]
    private ?Location $officeOfExportLocation = null;

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'DocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $documentReferences = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getCarrierAssignedID(): ?Identifier
    {
        return $this->carrierAssignedID;
    }

    public function setCarrierAssignedID(?Identifier $carrierAssignedID = null): self
    {
        $this->carrierAssignedID = $carrierAssignedID;
        return $this;
    }

    public function getConsigneeAssignedID(): ?Identifier
    {
        return $this->consigneeAssignedID;
    }

    public function setConsigneeAssignedID(?Identifier $consigneeAssignedID = null): self
    {
        $this->consigneeAssignedID = $consigneeAssignedID;
        return $this;
    }

    public function getConsignorAssignedID(): ?Identifier
    {
        return $this->consignorAssignedID;
    }

    public function setConsignorAssignedID(?Identifier $consignorAssignedID = null): self
    {
        $this->consignorAssignedID = $consignorAssignedID;
        return $this;
    }

    public function getFreightForwarderAssignedID(): ?Identifier
    {
        return $this->freightForwarderAssignedID;
    }

    public function setFreightForwarderAssignedID(?Identifier $freightForwarderAssignedID = null): self
    {
        $this->freightForwarderAssignedID = $freightForwarderAssignedID;
        return $this;
    }

    public function getBrokerAssignedID(): ?Identifier
    {
        return $this->brokerAssignedID;
    }

    public function setBrokerAssignedID(?Identifier $brokerAssignedID = null): self
    {
        $this->brokerAssignedID = $brokerAssignedID;
        return $this;
    }

    public function getContractedCarrierAssignedID(): ?Identifier
    {
        return $this->contractedCarrierAssignedID;
    }

    public function setContractedCarrierAssignedID(?Identifier $contractedCarrierAssignedID = null): self
    {
        $this->contractedCarrierAssignedID = $contractedCarrierAssignedID;
        return $this;
    }

    public function getPerformingCarrierAssignedID(): ?Identifier
    {
        return $this->performingCarrierAssignedID;
    }

    public function setPerformingCarrierAssignedID(?Identifier $performingCarrierAssignedID = null): self
    {
        $this->performingCarrierAssignedID = $performingCarrierAssignedID;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getSummaryDescriptions(): array
    {
        return $this->summaryDescriptions;
    }

    /**
     * @param list<Text> $summaryDescriptions
     */
    public function setSummaryDescriptions(array $summaryDescriptions): self
    {
        self::validateSummaryDescriptions($summaryDescriptions);
        $this->summaryDescriptions = $summaryDescriptions;
        return $this;
    }

    public function addToSummaryDescriptions(Text $item): self
    {
        $this->summaryDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateSummaryDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getTotalInvoiceAmount(): ?Amount
    {
        return $this->totalInvoiceAmount;
    }

    public function setTotalInvoiceAmount(?Amount $totalInvoiceAmount = null): self
    {
        $this->totalInvoiceAmount = $totalInvoiceAmount;
        return $this;
    }

    public function getDeclaredCustomsValueAmount(): ?Amount
    {
        return $this->declaredCustomsValueAmount;
    }

    public function setDeclaredCustomsValueAmount(?Amount $declaredCustomsValueAmount = null): self
    {
        $this->declaredCustomsValueAmount = $declaredCustomsValueAmount;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getTariffDescriptions(): array
    {
        return $this->tariffDescriptions;
    }

    /**
     * @param list<Text> $tariffDescriptions
     */
    public function setTariffDescriptions(array $tariffDescriptions): self
    {
        self::validateTariffDescriptions($tariffDescriptions);
        $this->tariffDescriptions = $tariffDescriptions;
        return $this;
    }

    public function addToTariffDescriptions(Text $item): self
    {
        $this->tariffDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateTariffDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getTariffCode(): ?Code
    {
        return $this->tariffCode;
    }

    public function setTariffCode(?Code $tariffCode = null): self
    {
        $this->tariffCode = $tariffCode;
        return $this;
    }

    public function getInsurancePremiumAmount(): ?Amount
    {
        return $this->insurancePremiumAmount;
    }

    public function setInsurancePremiumAmount(?Amount $insurancePremiumAmount = null): self
    {
        $this->insurancePremiumAmount = $insurancePremiumAmount;
        return $this;
    }

    public function getGrossWeightMeasure(): ?Measure
    {
        return $this->grossWeightMeasure;
    }

    public function setGrossWeightMeasure(?Measure $grossWeightMeasure = null): self
    {
        $this->grossWeightMeasure = $grossWeightMeasure;
        return $this;
    }

    public function getNetWeightMeasure(): ?Measure
    {
        return $this->netWeightMeasure;
    }

    public function setNetWeightMeasure(?Measure $netWeightMeasure = null): self
    {
        $this->netWeightMeasure = $netWeightMeasure;
        return $this;
    }

    public function getNetNetWeightMeasure(): ?Measure
    {
        return $this->netNetWeightMeasure;
    }

    public function setNetNetWeightMeasure(?Measure $netNetWeightMeasure = null): self
    {
        $this->netNetWeightMeasure = $netNetWeightMeasure;
        return $this;
    }

    public function getChargeableWeightMeasure(): ?Measure
    {
        return $this->chargeableWeightMeasure;
    }

    public function setChargeableWeightMeasure(?Measure $chargeableWeightMeasure = null): self
    {
        $this->chargeableWeightMeasure = $chargeableWeightMeasure;
        return $this;
    }

    public function getGrossVolumeMeasure(): ?Measure
    {
        return $this->grossVolumeMeasure;
    }

    public function setGrossVolumeMeasure(?Measure $grossVolumeMeasure = null): self
    {
        $this->grossVolumeMeasure = $grossVolumeMeasure;
        return $this;
    }

    public function getNetVolumeMeasure(): ?Measure
    {
        return $this->netVolumeMeasure;
    }

    public function setNetVolumeMeasure(?Measure $netVolumeMeasure = null): self
    {
        $this->netVolumeMeasure = $netVolumeMeasure;
        return $this;
    }

    public function getLoadingLengthMeasure(): ?Measure
    {
        return $this->loadingLengthMeasure;
    }

    public function setLoadingLengthMeasure(?Measure $loadingLengthMeasure = null): self
    {
        $this->loadingLengthMeasure = $loadingLengthMeasure;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getRemarkses(): array
    {
        return $this->remarkses;
    }

    /**
     * @param list<Text> $remarkses
     */
    public function setRemarkses(array $remarkses): self
    {
        self::validateRemarkses($remarkses);
        $this->remarkses = $remarkses;
        return $this;
    }

    public function addToRemarkses(Text $item): self
    {
        $this->remarkses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateRemarkses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getHazardousRiskIndicator(): ?bool
    {
        return $this->hazardousRiskIndicator;
    }

    public function setHazardousRiskIndicator(?bool $hazardousRiskIndicator = null): self
    {
        $this->hazardousRiskIndicator = $hazardousRiskIndicator;
        return $this;
    }

    public function getAnimalFoodIndicator(): ?bool
    {
        return $this->animalFoodIndicator;
    }

    public function setAnimalFoodIndicator(?bool $animalFoodIndicator = null): self
    {
        $this->animalFoodIndicator = $animalFoodIndicator;
        return $this;
    }

    public function getHumanFoodIndicator(): ?bool
    {
        return $this->humanFoodIndicator;
    }

    public function setHumanFoodIndicator(?bool $humanFoodIndicator = null): self
    {
        $this->humanFoodIndicator = $humanFoodIndicator;
        return $this;
    }

    public function getLivestockIndicator(): ?bool
    {
        return $this->livestockIndicator;
    }

    public function setLivestockIndicator(?bool $livestockIndicator = null): self
    {
        $this->livestockIndicator = $livestockIndicator;
        return $this;
    }

    public function getBulkCargoIndicator(): ?bool
    {
        return $this->bulkCargoIndicator;
    }

    public function setBulkCargoIndicator(?bool $bulkCargoIndicator = null): self
    {
        $this->bulkCargoIndicator = $bulkCargoIndicator;
        return $this;
    }

    public function getContainerizedIndicator(): ?bool
    {
        return $this->containerizedIndicator;
    }

    public function setContainerizedIndicator(?bool $containerizedIndicator = null): self
    {
        $this->containerizedIndicator = $containerizedIndicator;
        return $this;
    }

    public function getGeneralCargoIndicator(): ?bool
    {
        return $this->generalCargoIndicator;
    }

    public function setGeneralCargoIndicator(?bool $generalCargoIndicator = null): self
    {
        $this->generalCargoIndicator = $generalCargoIndicator;
        return $this;
    }

    public function getSpecialSecurityIndicator(): ?bool
    {
        return $this->specialSecurityIndicator;
    }

    public function setSpecialSecurityIndicator(?bool $specialSecurityIndicator = null): self
    {
        $this->specialSecurityIndicator = $specialSecurityIndicator;
        return $this;
    }

    public function getThirdPartyPayerIndicator(): ?bool
    {
        return $this->thirdPartyPayerIndicator;
    }

    public function setThirdPartyPayerIndicator(?bool $thirdPartyPayerIndicator = null): self
    {
        $this->thirdPartyPayerIndicator = $thirdPartyPayerIndicator;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getCarrierServiceInstructionses(): array
    {
        return $this->carrierServiceInstructionses;
    }

    /**
     * @param list<Text> $carrierServiceInstructionses
     */
    public function setCarrierServiceInstructionses(array $carrierServiceInstructionses): self
    {
        self::validateCarrierServiceInstructionses($carrierServiceInstructionses);
        $this->carrierServiceInstructionses = $carrierServiceInstructionses;
        return $this;
    }

    public function addToCarrierServiceInstructionses(Text $item): self
    {
        $this->carrierServiceInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateCarrierServiceInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getCustomsClearanceServiceInstructionses(): array
    {
        return $this->customsClearanceServiceInstructionses;
    }

    /**
     * @param list<Text> $customsClearanceServiceInstructionses
     */
    public function setCustomsClearanceServiceInstructionses(array $customsClearanceServiceInstructionses): self
    {
        self::validateCustomsClearanceServiceInstructionses($customsClearanceServiceInstructionses);
        $this->customsClearanceServiceInstructionses = $customsClearanceServiceInstructionses;
        return $this;
    }

    public function addToCustomsClearanceServiceInstructionses(Text $item): self
    {
        $this->customsClearanceServiceInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateCustomsClearanceServiceInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getForwarderServiceInstructionses(): array
    {
        return $this->forwarderServiceInstructionses;
    }

    /**
     * @param list<Text> $forwarderServiceInstructionses
     */
    public function setForwarderServiceInstructionses(array $forwarderServiceInstructionses): self
    {
        self::validateForwarderServiceInstructionses($forwarderServiceInstructionses);
        $this->forwarderServiceInstructionses = $forwarderServiceInstructionses;
        return $this;
    }

    public function addToForwarderServiceInstructionses(Text $item): self
    {
        $this->forwarderServiceInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateForwarderServiceInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getSpecialServiceInstructionses(): array
    {
        return $this->specialServiceInstructionses;
    }

    /**
     * @param list<Text> $specialServiceInstructionses
     */
    public function setSpecialServiceInstructionses(array $specialServiceInstructionses): self
    {
        self::validateSpecialServiceInstructionses($specialServiceInstructionses);
        $this->specialServiceInstructionses = $specialServiceInstructionses;
        return $this;
    }

    public function addToSpecialServiceInstructionses(Text $item): self
    {
        $this->specialServiceInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateSpecialServiceInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getSequenceID(): ?Identifier
    {
        return $this->sequenceID;
    }

    public function setSequenceID(?Identifier $sequenceID = null): self
    {
        $this->sequenceID = $sequenceID;
        return $this;
    }

    public function getShippingPriorityLevelCode(): ?Code
    {
        return $this->shippingPriorityLevelCode;
    }

    public function setShippingPriorityLevelCode(?Code $shippingPriorityLevelCode = null): self
    {
        $this->shippingPriorityLevelCode = $shippingPriorityLevelCode;
        return $this;
    }

    public function getHandlingCode(): ?Code
    {
        return $this->handlingCode;
    }

    public function setHandlingCode(?Code $handlingCode = null): self
    {
        $this->handlingCode = $handlingCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getHandlingInstructionses(): array
    {
        return $this->handlingInstructionses;
    }

    /**
     * @param list<Text> $handlingInstructionses
     */
    public function setHandlingInstructionses(array $handlingInstructionses): self
    {
        self::validateHandlingInstructionses($handlingInstructionses);
        $this->handlingInstructionses = $handlingInstructionses;
        return $this;
    }

    public function addToHandlingInstructionses(Text $item): self
    {
        $this->handlingInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateHandlingInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getInformations(): array
    {
        return $this->informations;
    }

    /**
     * @param list<Text> $informations
     */
    public function setInformations(array $informations): self
    {
        self::validateInformations($informations);
        $this->informations = $informations;
        return $this;
    }

    public function addToInformations(Text $item): self
    {
        $this->informations[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateInformations(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getTotalGoodsItemQuantity(): ?Quantity
    {
        return $this->totalGoodsItemQuantity;
    }

    public function setTotalGoodsItemQuantity(?Quantity $totalGoodsItemQuantity = null): self
    {
        $this->totalGoodsItemQuantity = $totalGoodsItemQuantity;
        return $this;
    }

    public function getTotalTransportHandlingUnitQuantity(): ?Quantity
    {
        return $this->totalTransportHandlingUnitQuantity;
    }

    public function setTotalTransportHandlingUnitQuantity(?Quantity $totalTransportHandlingUnitQuantity = null): self
    {
        $this->totalTransportHandlingUnitQuantity = $totalTransportHandlingUnitQuantity;
        return $this;
    }

    public function getInsuranceValueAmount(): ?Amount
    {
        return $this->insuranceValueAmount;
    }

    public function setInsuranceValueAmount(?Amount $insuranceValueAmount = null): self
    {
        $this->insuranceValueAmount = $insuranceValueAmount;
        return $this;
    }

    public function getDeclaredForCarriageValueAmount(): ?Amount
    {
        return $this->declaredForCarriageValueAmount;
    }

    public function setDeclaredForCarriageValueAmount(?Amount $declaredForCarriageValueAmount = null): self
    {
        $this->declaredForCarriageValueAmount = $declaredForCarriageValueAmount;
        return $this;
    }

    public function getDeclaredStatisticsValueAmount(): ?Amount
    {
        return $this->declaredStatisticsValueAmount;
    }

    public function setDeclaredStatisticsValueAmount(?Amount $declaredStatisticsValueAmount = null): self
    {
        $this->declaredStatisticsValueAmount = $declaredStatisticsValueAmount;
        return $this;
    }

    public function getFreeOnBoardValueAmount(): ?Amount
    {
        return $this->freeOnBoardValueAmount;
    }

    public function setFreeOnBoardValueAmount(?Amount $freeOnBoardValueAmount = null): self
    {
        $this->freeOnBoardValueAmount = $freeOnBoardValueAmount;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getSpecialInstructionses(): array
    {
        return $this->specialInstructionses;
    }

    /**
     * @param list<Text> $specialInstructionses
     */
    public function setSpecialInstructionses(array $specialInstructionses): self
    {
        self::validateSpecialInstructionses($specialInstructionses);
        $this->specialInstructionses = $specialInstructionses;
        return $this;
    }

    public function addToSpecialInstructionses(Text $item): self
    {
        $this->specialInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateSpecialInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getSplitConsignmentIndicator(): ?bool
    {
        return $this->splitConsignmentIndicator;
    }

    public function setSplitConsignmentIndicator(?bool $splitConsignmentIndicator = null): self
    {
        $this->splitConsignmentIndicator = $splitConsignmentIndicator;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDeliveryInstructionses(): array
    {
        return $this->deliveryInstructionses;
    }

    /**
     * @param list<Text> $deliveryInstructionses
     */
    public function setDeliveryInstructionses(array $deliveryInstructionses): self
    {
        self::validateDeliveryInstructionses($deliveryInstructionses);
        $this->deliveryInstructionses = $deliveryInstructionses;
        return $this;
    }

    public function addToDeliveryInstructionses(Text $item): self
    {
        $this->deliveryInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDeliveryInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getConsignmentQuantity(): ?Quantity
    {
        return $this->consignmentQuantity;
    }

    public function setConsignmentQuantity(?Quantity $consignmentQuantity = null): self
    {
        $this->consignmentQuantity = $consignmentQuantity;
        return $this;
    }

    public function getConsolidatableIndicator(): ?bool
    {
        return $this->consolidatableIndicator;
    }

    public function setConsolidatableIndicator(?bool $consolidatableIndicator = null): self
    {
        $this->consolidatableIndicator = $consolidatableIndicator;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getHaulageInstructionses(): array
    {
        return $this->haulageInstructionses;
    }

    /**
     * @param list<Text> $haulageInstructionses
     */
    public function setHaulageInstructionses(array $haulageInstructionses): self
    {
        self::validateHaulageInstructionses($haulageInstructionses);
        $this->haulageInstructionses = $haulageInstructionses;
        return $this;
    }

    public function addToHaulageInstructionses(Text $item): self
    {
        $this->haulageInstructionses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateHaulageInstructionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getLoadingSequenceID(): ?Identifier
    {
        return $this->loadingSequenceID;
    }

    public function setLoadingSequenceID(?Identifier $loadingSequenceID = null): self
    {
        $this->loadingSequenceID = $loadingSequenceID;
        return $this;
    }

    public function getChildConsignmentQuantity(): ?Quantity
    {
        return $this->childConsignmentQuantity;
    }

    public function setChildConsignmentQuantity(?Quantity $childConsignmentQuantity = null): self
    {
        $this->childConsignmentQuantity = $childConsignmentQuantity;
        return $this;
    }

    public function getTotalPackagesQuantity(): ?Quantity
    {
        return $this->totalPackagesQuantity;
    }

    public function setTotalPackagesQuantity(?Quantity $totalPackagesQuantity = null): self
    {
        $this->totalPackagesQuantity = $totalPackagesQuantity;
        return $this;
    }

    /**
     * @return list<Shipment>
     */
    public function getConsolidatedShipments(): array
    {
        return $this->consolidatedShipments;
    }

    /**
     * @param list<Shipment> $consolidatedShipments
     */
    public function setConsolidatedShipments(array $consolidatedShipments): self
    {
        self::validateConsolidatedShipments($consolidatedShipments);
        $this->consolidatedShipments = $consolidatedShipments;
        return $this;
    }

    public function addToConsolidatedShipments(Shipment $item): self
    {
        $this->consolidatedShipments[] = $item;
        return $this;
    }

    /**
     * @param list<Shipment> $values
     */
    private static function validateConsolidatedShipments(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Shipment) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Shipment, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<CustomsDeclaration>
     */
    public function getCustomsDeclarations(): array
    {
        return $this->customsDeclarations;
    }

    /**
     * @param list<CustomsDeclaration> $customsDeclarations
     */
    public function setCustomsDeclarations(array $customsDeclarations): self
    {
        self::validateCustomsDeclarations($customsDeclarations);
        $this->customsDeclarations = $customsDeclarations;
        return $this;
    }

    public function addToCustomsDeclarations(CustomsDeclaration $item): self
    {
        $this->customsDeclarations[] = $item;
        return $this;
    }

    /**
     * @param list<CustomsDeclaration> $values
     */
    private static function validateCustomsDeclarations(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof CustomsDeclaration) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of CustomsDeclaration, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getRequestedPickupTransportEvent(): ?TransportEvent
    {
        return $this->requestedPickupTransportEvent;
    }

    public function setRequestedPickupTransportEvent(?TransportEvent $requestedPickupTransportEvent = null): self
    {
        $this->requestedPickupTransportEvent = $requestedPickupTransportEvent;
        return $this;
    }

    public function getRequestedDeliveryTransportEvent(): ?TransportEvent
    {
        return $this->requestedDeliveryTransportEvent;
    }

    public function setRequestedDeliveryTransportEvent(?TransportEvent $requestedDeliveryTransportEvent = null): self
    {
        $this->requestedDeliveryTransportEvent = $requestedDeliveryTransportEvent;
        return $this;
    }

    public function getPlannedPickupTransportEvent(): ?TransportEvent
    {
        return $this->plannedPickupTransportEvent;
    }

    public function setPlannedPickupTransportEvent(?TransportEvent $plannedPickupTransportEvent = null): self
    {
        $this->plannedPickupTransportEvent = $plannedPickupTransportEvent;
        return $this;
    }

    public function getPlannedDeliveryTransportEvent(): ?TransportEvent
    {
        return $this->plannedDeliveryTransportEvent;
    }

    public function setPlannedDeliveryTransportEvent(?TransportEvent $plannedDeliveryTransportEvent = null): self
    {
        $this->plannedDeliveryTransportEvent = $plannedDeliveryTransportEvent;
        return $this;
    }

    public function getActualPickupTransportEvent(): ?TransportEvent
    {
        return $this->actualPickupTransportEvent;
    }

    public function setActualPickupTransportEvent(?TransportEvent $actualPickupTransportEvent = null): self
    {
        $this->actualPickupTransportEvent = $actualPickupTransportEvent;
        return $this;
    }

    public function getActualDeliveryTransportEvent(): ?TransportEvent
    {
        return $this->actualDeliveryTransportEvent;
    }

    public function setActualDeliveryTransportEvent(?TransportEvent $actualDeliveryTransportEvent = null): self
    {
        $this->actualDeliveryTransportEvent = $actualDeliveryTransportEvent;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getStatuses(): array
    {
        return $this->statuses;
    }

    /**
     * @param list<Text> $statuses
     */
    public function setStatuses(array $statuses): self
    {
        self::validateStatuses($statuses);
        $this->statuses = $statuses;
        return $this;
    }

    public function addToStatuses(Text $item): self
    {
        $this->statuses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateStatuses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Consignment>
     */
    public function getChildConsignments(): array
    {
        return $this->childConsignments;
    }

    /**
     * @param list<Consignment> $childConsignments
     */
    public function setChildConsignments(array $childConsignments): self
    {
        self::validateChildConsignments($childConsignments);
        $this->childConsignments = $childConsignments;
        return $this;
    }

    public function addToChildConsignments(Consignment $item): self
    {
        $this->childConsignments[] = $item;
        return $this;
    }

    /**
     * @param list<Consignment> $values
     */
    private static function validateChildConsignments(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Consignment) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Consignment, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getConsigneeParty(): ?Party
    {
        return $this->consigneeParty;
    }

    public function setConsigneeParty(?Party $consigneeParty = null): self
    {
        $this->consigneeParty = $consigneeParty;
        return $this;
    }

    public function getExporterParty(): ?Party
    {
        return $this->exporterParty;
    }

    public function setExporterParty(?Party $exporterParty = null): self
    {
        $this->exporterParty = $exporterParty;
        return $this;
    }

    public function getConsignorParty(): ?Party
    {
        return $this->consignorParty;
    }

    public function setConsignorParty(?Party $consignorParty = null): self
    {
        $this->consignorParty = $consignorParty;
        return $this;
    }

    public function getImporterParty(): ?Party
    {
        return $this->importerParty;
    }

    public function setImporterParty(?Party $importerParty = null): self
    {
        $this->importerParty = $importerParty;
        return $this;
    }

    public function getCarrierParty(): ?Party
    {
        return $this->carrierParty;
    }

    public function setCarrierParty(?Party $carrierParty = null): self
    {
        $this->carrierParty = $carrierParty;
        return $this;
    }

    public function getFreightForwarderParty(): ?Party
    {
        return $this->freightForwarderParty;
    }

    public function setFreightForwarderParty(?Party $freightForwarderParty = null): self
    {
        $this->freightForwarderParty = $freightForwarderParty;
        return $this;
    }

    public function getNotifyParty(): ?Party
    {
        return $this->notifyParty;
    }

    public function setNotifyParty(?Party $notifyParty = null): self
    {
        $this->notifyParty = $notifyParty;
        return $this;
    }

    public function getOriginalDespatchParty(): ?Party
    {
        return $this->originalDespatchParty;
    }

    public function setOriginalDespatchParty(?Party $originalDespatchParty = null): self
    {
        $this->originalDespatchParty = $originalDespatchParty;
        return $this;
    }

    public function getFinalDeliveryParty(): ?Party
    {
        return $this->finalDeliveryParty;
    }

    public function setFinalDeliveryParty(?Party $finalDeliveryParty = null): self
    {
        $this->finalDeliveryParty = $finalDeliveryParty;
        return $this;
    }

    public function getPerformingCarrierParty(): ?Party
    {
        return $this->performingCarrierParty;
    }

    public function setPerformingCarrierParty(?Party $performingCarrierParty = null): self
    {
        $this->performingCarrierParty = $performingCarrierParty;
        return $this;
    }

    public function getSubstituteCarrierParty(): ?Party
    {
        return $this->substituteCarrierParty;
    }

    public function setSubstituteCarrierParty(?Party $substituteCarrierParty = null): self
    {
        $this->substituteCarrierParty = $substituteCarrierParty;
        return $this;
    }

    public function getLogisticsOperatorParty(): ?Party
    {
        return $this->logisticsOperatorParty;
    }

    public function setLogisticsOperatorParty(?Party $logisticsOperatorParty = null): self
    {
        $this->logisticsOperatorParty = $logisticsOperatorParty;
        return $this;
    }

    public function getTransportAdvisorParty(): ?Party
    {
        return $this->transportAdvisorParty;
    }

    public function setTransportAdvisorParty(?Party $transportAdvisorParty = null): self
    {
        $this->transportAdvisorParty = $transportAdvisorParty;
        return $this;
    }

    public function getHazardousItemNotificationParty(): ?Party
    {
        return $this->hazardousItemNotificationParty;
    }

    public function setHazardousItemNotificationParty(?Party $hazardousItemNotificationParty = null): self
    {
        $this->hazardousItemNotificationParty = $hazardousItemNotificationParty;
        return $this;
    }

    public function getInsuranceParty(): ?Party
    {
        return $this->insuranceParty;
    }

    public function setInsuranceParty(?Party $insuranceParty = null): self
    {
        $this->insuranceParty = $insuranceParty;
        return $this;
    }

    public function getMortgageHolderParty(): ?Party
    {
        return $this->mortgageHolderParty;
    }

    public function setMortgageHolderParty(?Party $mortgageHolderParty = null): self
    {
        $this->mortgageHolderParty = $mortgageHolderParty;
        return $this;
    }

    public function getBillOfLadingHolderParty(): ?Party
    {
        return $this->billOfLadingHolderParty;
    }

    public function setBillOfLadingHolderParty(?Party $billOfLadingHolderParty = null): self
    {
        $this->billOfLadingHolderParty = $billOfLadingHolderParty;
        return $this;
    }

    public function getOriginalDepartureCountry(): ?Country
    {
        return $this->originalDepartureCountry;
    }

    public function setOriginalDepartureCountry(?Country $originalDepartureCountry = null): self
    {
        $this->originalDepartureCountry = $originalDepartureCountry;
        return $this;
    }

    public function getFinalDestinationCountry(): ?Country
    {
        return $this->finalDestinationCountry;
    }

    public function setFinalDestinationCountry(?Country $finalDestinationCountry = null): self
    {
        $this->finalDestinationCountry = $finalDestinationCountry;
        return $this;
    }

    /**
     * @return list<Country>
     */
    public function getTransitCountries(): array
    {
        return $this->transitCountries;
    }

    /**
     * @param list<Country> $transitCountries
     */
    public function setTransitCountries(array $transitCountries): self
    {
        self::validateTransitCountries($transitCountries);
        $this->transitCountries = $transitCountries;
        return $this;
    }

    public function addToTransitCountries(Country $item): self
    {
        $this->transitCountries[] = $item;
        return $this;
    }

    /**
     * @param list<Country> $values
     */
    private static function validateTransitCountries(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Country) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Country, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getTransportContract(): ?Contract
    {
        return $this->transportContract;
    }

    public function setTransportContract(?Contract $transportContract = null): self
    {
        $this->transportContract = $transportContract;
        return $this;
    }

    /**
     * @return list<TransportEvent>
     */
    public function getTransportEvents(): array
    {
        return $this->transportEvents;
    }

    /**
     * @param list<TransportEvent> $transportEvents
     */
    public function setTransportEvents(array $transportEvents): self
    {
        self::validateTransportEvents($transportEvents);
        $this->transportEvents = $transportEvents;
        return $this;
    }

    public function addToTransportEvents(TransportEvent $item): self
    {
        $this->transportEvents[] = $item;
        return $this;
    }

    /**
     * @param list<TransportEvent> $values
     */
    private static function validateTransportEvents(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TransportEvent) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TransportEvent, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getOriginalDespatchTransportationService(): ?TransportationService
    {
        return $this->originalDespatchTransportationService;
    }

    public function setOriginalDespatchTransportationService(
        ?TransportationService $originalDespatchTransportationService = null,
    ): self {
        $this->originalDespatchTransportationService = $originalDespatchTransportationService;
        return $this;
    }

    public function getFinalDeliveryTransportationService(): ?TransportationService
    {
        return $this->finalDeliveryTransportationService;
    }

    public function setFinalDeliveryTransportationService(
        ?TransportationService $finalDeliveryTransportationService = null,
    ): self {
        $this->finalDeliveryTransportationService = $finalDeliveryTransportationService;
        return $this;
    }

    public function getDeliveryTerms(): ?DeliveryTerms
    {
        return $this->deliveryTerms;
    }

    public function setDeliveryTerms(?DeliveryTerms $deliveryTerms = null): self
    {
        $this->deliveryTerms = $deliveryTerms;
        return $this;
    }

    public function getPaymentTerms(): ?PaymentTerms
    {
        return $this->paymentTerms;
    }

    public function setPaymentTerms(?PaymentTerms $paymentTerms = null): self
    {
        $this->paymentTerms = $paymentTerms;
        return $this;
    }

    public function getCollectPaymentTerms(): ?PaymentTerms
    {
        return $this->collectPaymentTerms;
    }

    public function setCollectPaymentTerms(?PaymentTerms $collectPaymentTerms = null): self
    {
        $this->collectPaymentTerms = $collectPaymentTerms;
        return $this;
    }

    public function getDisbursementPaymentTerms(): ?PaymentTerms
    {
        return $this->disbursementPaymentTerms;
    }

    public function setDisbursementPaymentTerms(?PaymentTerms $disbursementPaymentTerms = null): self
    {
        $this->disbursementPaymentTerms = $disbursementPaymentTerms;
        return $this;
    }

    public function getPrepaidPaymentTerms(): ?PaymentTerms
    {
        return $this->prepaidPaymentTerms;
    }

    public function setPrepaidPaymentTerms(?PaymentTerms $prepaidPaymentTerms = null): self
    {
        $this->prepaidPaymentTerms = $prepaidPaymentTerms;
        return $this;
    }

    /**
     * @return list<AllowanceCharge>
     */
    public function getFreightAllowanceCharges(): array
    {
        return $this->freightAllowanceCharges;
    }

    /**
     * @param list<AllowanceCharge> $freightAllowanceCharges
     */
    public function setFreightAllowanceCharges(array $freightAllowanceCharges): self
    {
        self::validateFreightAllowanceCharges($freightAllowanceCharges);
        $this->freightAllowanceCharges = $freightAllowanceCharges;
        return $this;
    }

    public function addToFreightAllowanceCharges(AllowanceCharge $item): self
    {
        $this->freightAllowanceCharges[] = $item;
        return $this;
    }

    /**
     * @param list<AllowanceCharge> $values
     */
    private static function validateFreightAllowanceCharges(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof AllowanceCharge) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of AllowanceCharge, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<AllowanceCharge>
     */
    public function getExtraAllowanceCharges(): array
    {
        return $this->extraAllowanceCharges;
    }

    /**
     * @param list<AllowanceCharge> $extraAllowanceCharges
     */
    public function setExtraAllowanceCharges(array $extraAllowanceCharges): self
    {
        self::validateExtraAllowanceCharges($extraAllowanceCharges);
        $this->extraAllowanceCharges = $extraAllowanceCharges;
        return $this;
    }

    public function addToExtraAllowanceCharges(AllowanceCharge $item): self
    {
        $this->extraAllowanceCharges[] = $item;
        return $this;
    }

    /**
     * @param list<AllowanceCharge> $values
     */
    private static function validateExtraAllowanceCharges(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof AllowanceCharge) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of AllowanceCharge, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ShipmentStage>
     */
    public function getMainCarriageShipmentStages(): array
    {
        return $this->mainCarriageShipmentStages;
    }

    /**
     * @param list<ShipmentStage> $mainCarriageShipmentStages
     */
    public function setMainCarriageShipmentStages(array $mainCarriageShipmentStages): self
    {
        self::validateMainCarriageShipmentStages($mainCarriageShipmentStages);
        $this->mainCarriageShipmentStages = $mainCarriageShipmentStages;
        return $this;
    }

    public function addToMainCarriageShipmentStages(ShipmentStage $item): self
    {
        $this->mainCarriageShipmentStages[] = $item;
        return $this;
    }

    /**
     * @param list<ShipmentStage> $values
     */
    private static function validateMainCarriageShipmentStages(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ShipmentStage) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ShipmentStage, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ShipmentStage>
     */
    public function getPreCarriageShipmentStages(): array
    {
        return $this->preCarriageShipmentStages;
    }

    /**
     * @param list<ShipmentStage> $preCarriageShipmentStages
     */
    public function setPreCarriageShipmentStages(array $preCarriageShipmentStages): self
    {
        self::validatePreCarriageShipmentStages($preCarriageShipmentStages);
        $this->preCarriageShipmentStages = $preCarriageShipmentStages;
        return $this;
    }

    public function addToPreCarriageShipmentStages(ShipmentStage $item): self
    {
        $this->preCarriageShipmentStages[] = $item;
        return $this;
    }

    /**
     * @param list<ShipmentStage> $values
     */
    private static function validatePreCarriageShipmentStages(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ShipmentStage) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ShipmentStage, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ShipmentStage>
     */
    public function getOnCarriageShipmentStages(): array
    {
        return $this->onCarriageShipmentStages;
    }

    /**
     * @param list<ShipmentStage> $onCarriageShipmentStages
     */
    public function setOnCarriageShipmentStages(array $onCarriageShipmentStages): self
    {
        self::validateOnCarriageShipmentStages($onCarriageShipmentStages);
        $this->onCarriageShipmentStages = $onCarriageShipmentStages;
        return $this;
    }

    public function addToOnCarriageShipmentStages(ShipmentStage $item): self
    {
        $this->onCarriageShipmentStages[] = $item;
        return $this;
    }

    /**
     * @param list<ShipmentStage> $values
     */
    private static function validateOnCarriageShipmentStages(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ShipmentStage) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ShipmentStage, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<TransportHandlingUnit>
     */
    public function getTransportHandlingUnits(): array
    {
        return $this->transportHandlingUnits;
    }

    /**
     * @param list<TransportHandlingUnit> $transportHandlingUnits
     */
    public function setTransportHandlingUnits(array $transportHandlingUnits): self
    {
        self::validateTransportHandlingUnits($transportHandlingUnits);
        $this->transportHandlingUnits = $transportHandlingUnits;
        return $this;
    }

    public function addToTransportHandlingUnits(TransportHandlingUnit $item): self
    {
        $this->transportHandlingUnits[] = $item;
        return $this;
    }

    /**
     * @param list<TransportHandlingUnit> $values
     */
    private static function validateTransportHandlingUnits(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TransportHandlingUnit) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TransportHandlingUnit, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getFirstArrivalPortLocation(): ?Location
    {
        return $this->firstArrivalPortLocation;
    }

    public function setFirstArrivalPortLocation(?Location $firstArrivalPortLocation = null): self
    {
        $this->firstArrivalPortLocation = $firstArrivalPortLocation;
        return $this;
    }

    public function getLastExitPortLocation(): ?Location
    {
        return $this->lastExitPortLocation;
    }

    public function setLastExitPortLocation(?Location $lastExitPortLocation = null): self
    {
        $this->lastExitPortLocation = $lastExitPortLocation;
        return $this;
    }

    public function getOfficeOfEntryLocation(): ?Location
    {
        return $this->officeOfEntryLocation;
    }

    public function setOfficeOfEntryLocation(?Location $officeOfEntryLocation = null): self
    {
        $this->officeOfEntryLocation = $officeOfEntryLocation;
        return $this;
    }

    public function getOfficeOfSubSequentiallyEntryLocation(): ?Location
    {
        return $this->officeOfSubSequentiallyEntryLocation;
    }

    public function setOfficeOfSubSequentiallyEntryLocation(
        ?Location $officeOfSubSequentiallyEntryLocation = null,
    ): self {
        $this->officeOfSubSequentiallyEntryLocation = $officeOfSubSequentiallyEntryLocation;
        return $this;
    }

    public function getOfficeOfExitLocation(): ?Location
    {
        return $this->officeOfExitLocation;
    }

    public function setOfficeOfExitLocation(?Location $officeOfExitLocation = null): self
    {
        $this->officeOfExitLocation = $officeOfExitLocation;
        return $this;
    }

    public function getOfficeOfDepartureLocation(): ?Location
    {
        return $this->officeOfDepartureLocation;
    }

    public function setOfficeOfDepartureLocation(?Location $officeOfDepartureLocation = null): self
    {
        $this->officeOfDepartureLocation = $officeOfDepartureLocation;
        return $this;
    }

    public function getOfficeOfDestinationLocation(): ?Location
    {
        return $this->officeOfDestinationLocation;
    }

    public function setOfficeOfDestinationLocation(?Location $officeOfDestinationLocation = null): self
    {
        $this->officeOfDestinationLocation = $officeOfDestinationLocation;
        return $this;
    }

    public function getOfficeOfImportLocation(): ?Location
    {
        return $this->officeOfImportLocation;
    }

    public function setOfficeOfImportLocation(?Location $officeOfImportLocation = null): self
    {
        $this->officeOfImportLocation = $officeOfImportLocation;
        return $this;
    }

    public function getOfficeOfExportLocation(): ?Location
    {
        return $this->officeOfExportLocation;
    }

    public function setOfficeOfExportLocation(?Location $officeOfExportLocation = null): self
    {
        $this->officeOfExportLocation = $officeOfExportLocation;
        return $this;
    }

    /**
     * @return list<DocumentReference>
     */
    public function getDocumentReferences(): array
    {
        return $this->documentReferences;
    }

    /**
     * @param list<DocumentReference> $documentReferences
     */
    public function setDocumentReferences(array $documentReferences): self
    {
        self::validateDocumentReferences($documentReferences);
        $this->documentReferences = $documentReferences;
        return $this;
    }

    public function addToDocumentReferences(DocumentReference $item): self
    {
        $this->documentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
