<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Consumption Point. Details
 *  A class to define the point of consumption for a utility, such as a meter.
 *  Consumption Point
 */
#[XmlType(localName: 'ConsumptionPointType', namespace: Ns::CAC)]
final class ConsumptionPoint
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'SubscriberID', namespace: Ns::CBC)]
    private ?Identifier $subscriberID = null;

    #[XmlElement(name: 'SubscriberType', namespace: Ns::CBC)]
    private ?Text $subscriberType = null;

    #[XmlElement(name: 'SubscriberTypeCode', namespace: Ns::CBC)]
    private ?Code $subscriberTypeCode = null;

    #[XmlElement(name: 'TotalDeliveredQuantity', namespace: Ns::CBC)]
    private ?Quantity $totalDeliveredQuantity = null;

    #[XmlElement(name: 'Address', namespace: Ns::CAC)]
    private ?Address $address = null;

    #[XmlElement(name: 'WebSiteAccess', namespace: Ns::CAC)]
    private ?WebSiteAccess $webSiteAccess = null;

    /** @var list<Meter> */
    #[XmlElement(name: 'UtilityMeter', namespace: Ns::CAC, type: Meter::class)]
    private array $utilityMeters = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getSubscriberID(): ?Identifier
    {
        return $this->subscriberID;
    }

    public function setSubscriberID(?Identifier $subscriberID = null): self
    {
        $this->subscriberID = $subscriberID;
        return $this;
    }

    public function getSubscriberType(): ?Text
    {
        return $this->subscriberType;
    }

    public function setSubscriberType(?Text $subscriberType = null): self
    {
        $this->subscriberType = $subscriberType;
        return $this;
    }

    public function getSubscriberTypeCode(): ?Code
    {
        return $this->subscriberTypeCode;
    }

    public function setSubscriberTypeCode(?Code $subscriberTypeCode = null): self
    {
        $this->subscriberTypeCode = $subscriberTypeCode;
        return $this;
    }

    public function getTotalDeliveredQuantity(): ?Quantity
    {
        return $this->totalDeliveredQuantity;
    }

    public function setTotalDeliveredQuantity(?Quantity $totalDeliveredQuantity = null): self
    {
        $this->totalDeliveredQuantity = $totalDeliveredQuantity;
        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address = null): self
    {
        $this->address = $address;
        return $this;
    }

    public function getWebSiteAccess(): ?WebSiteAccess
    {
        return $this->webSiteAccess;
    }

    public function setWebSiteAccess(?WebSiteAccess $webSiteAccess = null): self
    {
        $this->webSiteAccess = $webSiteAccess;
        return $this;
    }

    /**
     * @return list<Meter>
     */
    public function getUtilityMeters(): array
    {
        return $this->utilityMeters;
    }

    /**
     * @param list<Meter> $utilityMeters
     */
    public function setUtilityMeters(array $utilityMeters): self
    {
        self::validateUtilityMeters($utilityMeters);
        $this->utilityMeters = $utilityMeters;
        return $this;
    }

    public function addToUtilityMeters(Meter $item): self
    {
        $this->utilityMeters[] = $item;
        return $this;
    }

    /**
     * @param list<Meter> $values
     */
    private static function validateUtilityMeters(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Meter) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Meter, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
