<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Contact. Details
 *  A class to describe a contactable person or department in an organization.
 *  Contact
 */
#[XmlType(localName: 'ContactType', namespace: Ns::CAC)]
final class Contact
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'JobTitle', namespace: Ns::CBC)]
    private ?Text $jobTitle = null;

    #[XmlElement(name: 'Department', namespace: Ns::CBC)]
    private ?Text $department = null;

    #[XmlElement(name: 'Telephone', namespace: Ns::CBC)]
    private ?Text $telephone = null;

    #[XmlElement(name: 'Telefax', namespace: Ns::CBC)]
    private ?Text $telefax = null;

    #[XmlElement(name: 'ElectronicMail', namespace: Ns::CBC)]
    private ?Text $electronicMail = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Note', namespace: Ns::CBC, type: Text::class)]
    private array $notes = [];

    /** @var list<Communication> */
    #[XmlElement(name: 'OtherCommunication', namespace: Ns::CAC, type: Communication::class)]
    private array $otherCommunications = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getJobTitle(): ?Text
    {
        return $this->jobTitle;
    }

    public function setJobTitle(?Text $jobTitle = null): self
    {
        $this->jobTitle = $jobTitle;
        return $this;
    }

    public function getDepartment(): ?Text
    {
        return $this->department;
    }

    public function setDepartment(?Text $department = null): self
    {
        $this->department = $department;
        return $this;
    }

    public function getTelephone(): ?Text
    {
        return $this->telephone;
    }

    public function setTelephone(?Text $telephone = null): self
    {
        $this->telephone = $telephone;
        return $this;
    }

    public function getTelefax(): ?Text
    {
        return $this->telefax;
    }

    public function setTelefax(?Text $telefax = null): self
    {
        $this->telefax = $telefax;
        return $this;
    }

    public function getElectronicMail(): ?Text
    {
        return $this->electronicMail;
    }

    public function setElectronicMail(?Text $electronicMail = null): self
    {
        $this->electronicMail = $electronicMail;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getNotes(): array
    {
        return $this->notes;
    }

    /**
     * @param list<Text> $notes
     */
    public function setNotes(array $notes): self
    {
        self::validateNotes($notes);
        $this->notes = $notes;
        return $this;
    }

    public function addToNotes(Text $item): self
    {
        $this->notes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Communication>
     */
    public function getOtherCommunications(): array
    {
        return $this->otherCommunications;
    }

    /**
     * @param list<Communication> $otherCommunications
     */
    public function setOtherCommunications(array $otherCommunications): self
    {
        self::validateOtherCommunications($otherCommunications);
        $this->otherCommunications = $otherCommunications;
        return $this;
    }

    public function addToOtherCommunications(Communication $item): self
    {
        $this->otherCommunications[] = $item;
        return $this;
    }

    /**
     * @param list<Communication> $values
     */
    private static function validateOtherCommunications(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Communication) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Communication, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
