<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Contracting System. Details
 *  A class to describe the contracting system. If the procedure is individual (nonrepetitive), this class should not be used.
 *  Contracting System
 */
#[XmlType(localName: 'ContractingSystemType', namespace: Ns::CAC)]
final class ContractingSystem
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'ContractingSystemTypeCode', namespace: Ns::CBC)]
    private ?Code $contractingSystemTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getContractingSystemTypeCode(): ?Code
    {
        return $this->contractingSystemTypeCode;
    }

    public function setContractingSystemTypeCode(?Code $contractingSystemTypeCode = null): self
    {
        $this->contractingSystemTypeCode = $contractingSystemTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
