<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Contracting Party Type. Details
 *  The type of contracting party that is independent of its role.
 *  Contracting Party Type
 */
#[XmlType(localName: 'ContractingPartyTypeType', namespace: Ns::CAC)]
final class ContractingPartyType
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'PartyTypeCode', namespace: Ns::CBC)]
    private ?Code $partyTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'PartyType', namespace: Ns::CBC, type: Text::class)]
    private array $partyTypes = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getPartyTypeCode(): ?Code
    {
        return $this->partyTypeCode;
    }

    public function setPartyTypeCode(?Code $partyTypeCode = null): self
    {
        $this->partyTypeCode = $partyTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getPartyTypes(): array
    {
        return $this->partyTypes;
    }

    /**
     * @param list<Text> $partyTypes
     */
    public function setPartyTypes(array $partyTypes): self
    {
        self::validatePartyTypes($partyTypes);
        $this->partyTypes = $partyTypes;
        return $this;
    }

    public function addToPartyTypes(Text $item): self
    {
        $this->partyTypes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validatePartyTypes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
