<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Contracting Party. Details
 *  A class to describe an individual, a group, or a body having a procurement role in a tendering process.
 *  Contracting Party
 */
#[XmlType(localName: 'ContractingPartyType', namespace: Ns::CAC)]
final class ContractingParty
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'BuyerProfileURI', namespace: Ns::CBC)]
    private ?Identifier $buyerProfileURI = null;

    /** @var list<ContractingPartyType> */
    #[XmlElement(name: 'ContractingPartyType', namespace: Ns::CAC, type: ContractingPartyType::class)]
    private array $contractingPartyTypes = [];

    /** @var list<ContractingActivity> */
    #[XmlElement(name: 'ContractingActivity', namespace: Ns::CAC, type: ContractingActivity::class)]
    private array $contractingActivities = [];

    #[XmlElement(name: 'ContractingRepresentationType', namespace: Ns::CAC)]
    private ?ContractingRepresentationType $contractingRepresentationType = null;

    #[XmlElement(name: 'Party', namespace: Ns::CAC, required: true)]
    private Party $party;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getBuyerProfileURI(): ?Identifier
    {
        return $this->buyerProfileURI;
    }

    public function setBuyerProfileURI(?Identifier $buyerProfileURI = null): self
    {
        $this->buyerProfileURI = $buyerProfileURI;
        return $this;
    }

    /**
     * @return list<ContractingPartyType>
     */
    public function getContractingPartyTypes(): array
    {
        return $this->contractingPartyTypes;
    }

    /**
     * @param list<ContractingPartyType> $contractingPartyTypes
     */
    public function setContractingPartyTypes(array $contractingPartyTypes): self
    {
        self::validateContractingPartyTypes($contractingPartyTypes);
        $this->contractingPartyTypes = $contractingPartyTypes;
        return $this;
    }

    public function addToContractingPartyTypes(ContractingPartyType $item): self
    {
        $this->contractingPartyTypes[] = $item;
        return $this;
    }

    /**
     * @param list<ContractingPartyType> $values
     */
    private static function validateContractingPartyTypes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ContractingPartyType) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ContractingPartyType, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ContractingActivity>
     */
    public function getContractingActivities(): array
    {
        return $this->contractingActivities;
    }

    /**
     * @param list<ContractingActivity> $contractingActivities
     */
    public function setContractingActivities(array $contractingActivities): self
    {
        self::validateContractingActivities($contractingActivities);
        $this->contractingActivities = $contractingActivities;
        return $this;
    }

    public function addToContractingActivities(ContractingActivity $item): self
    {
        $this->contractingActivities[] = $item;
        return $this;
    }

    /**
     * @param list<ContractingActivity> $values
     */
    private static function validateContractingActivities(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ContractingActivity) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ContractingActivity, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getContractingRepresentationType(): ?ContractingRepresentationType
    {
        return $this->contractingRepresentationType;
    }

    public function setContractingRepresentationType(
        ?ContractingRepresentationType $contractingRepresentationType = null,
    ): self {
        $this->contractingRepresentationType = $contractingRepresentationType;
        return $this;
    }

    public function getParty(): Party
    {
        return $this->party;
    }

    public function setParty(Party $party): self
    {
        $this->party = $party;
        return $this;
    }
}
