<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Corporate Registration Scheme. Details
 *  A class to describe a scheme for corporate registration.
 *  Corporate Registration Scheme
 */
#[XmlType(localName: 'CorporateRegistrationSchemeType', namespace: Ns::CAC)]
final class CorporateRegistrationScheme
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'CorporateRegistrationTypeCode', namespace: Ns::CBC)]
    private ?Code $corporateRegistrationTypeCode = null;

    /** @var list<Address> */
    #[XmlElement(name: 'JurisdictionRegionAddress', namespace: Ns::CAC, type: Address::class)]
    private array $jurisdictionRegionAddresses = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getCorporateRegistrationTypeCode(): ?Code
    {
        return $this->corporateRegistrationTypeCode;
    }

    public function setCorporateRegistrationTypeCode(?Code $corporateRegistrationTypeCode = null): self
    {
        $this->corporateRegistrationTypeCode = $corporateRegistrationTypeCode;
        return $this;
    }

    /**
     * @return list<Address>
     */
    public function getJurisdictionRegionAddresses(): array
    {
        return $this->jurisdictionRegionAddresses;
    }

    /**
     * @param list<Address> $jurisdictionRegionAddresses
     */
    public function setJurisdictionRegionAddresses(array $jurisdictionRegionAddresses): self
    {
        self::validateJurisdictionRegionAddresses($jurisdictionRegionAddresses);
        $this->jurisdictionRegionAddresses = $jurisdictionRegionAddresses;
        return $this;
    }

    public function addToJurisdictionRegionAddresses(Address $item): self
    {
        $this->jurisdictionRegionAddresses[] = $item;
        return $this;
    }

    /**
     * @param list<Address> $values
     */
    private static function validateJurisdictionRegionAddresses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Address) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Address, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
