<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Text;
use Xterr\Espd\Codelist\CountryCode;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Country. Details
 *  A class to describe a country.
 *  Country
 */
#[XmlType(localName: 'CountryType', namespace: Ns::CAC)]
final class Country
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'IdentificationCode', namespace: Ns::CBC)]
    private ?CountryCode $identificationCode = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getIdentificationCode(): ?CountryCode
    {
        return $this->identificationCode;
    }

    public function setIdentificationCode(?CountryCode $identificationCode = null): self
    {
        $this->identificationCode = $identificationCode;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }
}
