<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Customs Declaration. Details
 *  A class describing identifiers or references relating to customs procedures.
 *  Customs Declaration
 *  Movement Reference Number, Local Reference Number
 */
#[XmlType(localName: 'CustomsDeclarationType', namespace: Ns::CAC)]
final class CustomsDeclaration
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'ValidityPeriod', namespace: Ns::CAC)]
    private ?Period $validityPeriod = null;

    #[XmlElement(name: 'ApplicableTerritoryAddress', namespace: Ns::CAC)]
    private ?Address $applicableTerritoryAddress = null;

    #[XmlElement(name: 'Shipment', namespace: Ns::CAC)]
    private ?Shipment $shipment = null;

    #[XmlElement(name: 'CustomsExitOfficeLocation', namespace: Ns::CAC)]
    private ?Location $customsExitOfficeLocation = null;

    #[XmlElement(name: 'IssuerParty', namespace: Ns::CAC)]
    private ?Party $issuerParty = null;

    #[XmlElement(name: 'ConsignorParty', namespace: Ns::CAC)]
    private ?Party $consignorParty = null;

    #[XmlElement(name: 'ConsigneeParty', namespace: Ns::CAC)]
    private ?Party $consigneeParty = null;

    #[XmlElement(name: 'FreightForwarderParty', namespace: Ns::CAC)]
    private ?Party $freightForwarderParty = null;

    #[XmlElement(name: 'CustomsParty', namespace: Ns::CAC)]
    private ?Party $customsParty = null;

    #[XmlElement(name: 'PreviousCustomsDeclaration', namespace: Ns::CAC)]
    private ?CustomsDeclaration $previousCustomsDeclaration = null;

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'AdditionalDocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $additionalDocumentReferences = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getValidityPeriod(): ?Period
    {
        return $this->validityPeriod;
    }

    public function setValidityPeriod(?Period $validityPeriod = null): self
    {
        $this->validityPeriod = $validityPeriod;
        return $this;
    }

    public function getApplicableTerritoryAddress(): ?Address
    {
        return $this->applicableTerritoryAddress;
    }

    public function setApplicableTerritoryAddress(?Address $applicableTerritoryAddress = null): self
    {
        $this->applicableTerritoryAddress = $applicableTerritoryAddress;
        return $this;
    }

    public function getShipment(): ?Shipment
    {
        return $this->shipment;
    }

    public function setShipment(?Shipment $shipment = null): self
    {
        $this->shipment = $shipment;
        return $this;
    }

    public function getCustomsExitOfficeLocation(): ?Location
    {
        return $this->customsExitOfficeLocation;
    }

    public function setCustomsExitOfficeLocation(?Location $customsExitOfficeLocation = null): self
    {
        $this->customsExitOfficeLocation = $customsExitOfficeLocation;
        return $this;
    }

    public function getIssuerParty(): ?Party
    {
        return $this->issuerParty;
    }

    public function setIssuerParty(?Party $issuerParty = null): self
    {
        $this->issuerParty = $issuerParty;
        return $this;
    }

    public function getConsignorParty(): ?Party
    {
        return $this->consignorParty;
    }

    public function setConsignorParty(?Party $consignorParty = null): self
    {
        $this->consignorParty = $consignorParty;
        return $this;
    }

    public function getConsigneeParty(): ?Party
    {
        return $this->consigneeParty;
    }

    public function setConsigneeParty(?Party $consigneeParty = null): self
    {
        $this->consigneeParty = $consigneeParty;
        return $this;
    }

    public function getFreightForwarderParty(): ?Party
    {
        return $this->freightForwarderParty;
    }

    public function setFreightForwarderParty(?Party $freightForwarderParty = null): self
    {
        $this->freightForwarderParty = $freightForwarderParty;
        return $this;
    }

    public function getCustomsParty(): ?Party
    {
        return $this->customsParty;
    }

    public function setCustomsParty(?Party $customsParty = null): self
    {
        $this->customsParty = $customsParty;
        return $this;
    }

    public function getPreviousCustomsDeclaration(): ?CustomsDeclaration
    {
        return $this->previousCustomsDeclaration;
    }

    public function setPreviousCustomsDeclaration(?CustomsDeclaration $previousCustomsDeclaration = null): self
    {
        $this->previousCustomsDeclaration = $previousCustomsDeclaration;
        return $this;
    }

    /**
     * @return list<DocumentReference>
     */
    public function getAdditionalDocumentReferences(): array
    {
        return $this->additionalDocumentReferences;
    }

    /**
     * @param list<DocumentReference> $additionalDocumentReferences
     */
    public function setAdditionalDocumentReferences(array $additionalDocumentReferences): self
    {
        self::validateAdditionalDocumentReferences($additionalDocumentReferences);
        $this->additionalDocumentReferences = $additionalDocumentReferences;
        return $this;
    }

    public function addToAdditionalDocumentReferences(DocumentReference $item): self
    {
        $this->additionalDocumentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateAdditionalDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
