<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Digital Agreement Terms. Details
 *  A class to describe the terms and conditions of a digital agreement.
 *  Digital Agreement Terms
 *  Trading Partner Agreement Terms
 */
#[XmlType(localName: 'DigitalAgreementTermsType', namespace: Ns::CAC)]
final class DigitalAgreementTerms
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class, required: true)]
    private array $descriptions = [];

    #[XmlElement(name: 'ValidityPeriod', namespace: Ns::CAC)]
    private ?Period $validityPeriod = null;

    #[XmlElement(name: 'AdoptionPeriod', namespace: Ns::CAC)]
    private ?Period $adoptionPeriod = null;

    /** @var list<ServiceLevelAgreement> */
    #[XmlElement(name: 'ServiceLevelAgreement', namespace: Ns::CAC, type: ServiceLevelAgreement::class)]
    private array $serviceLevelAgreements = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getValidityPeriod(): ?Period
    {
        return $this->validityPeriod;
    }

    public function setValidityPeriod(?Period $validityPeriod = null): self
    {
        $this->validityPeriod = $validityPeriod;
        return $this;
    }

    public function getAdoptionPeriod(): ?Period
    {
        return $this->adoptionPeriod;
    }

    public function setAdoptionPeriod(?Period $adoptionPeriod = null): self
    {
        $this->adoptionPeriod = $adoptionPeriod;
        return $this;
    }

    /**
     * @return list<ServiceLevelAgreement>
     */
    public function getServiceLevelAgreements(): array
    {
        return $this->serviceLevelAgreements;
    }

    /**
     * @param list<ServiceLevelAgreement> $serviceLevelAgreements
     */
    public function setServiceLevelAgreements(array $serviceLevelAgreements): self
    {
        self::validateServiceLevelAgreements($serviceLevelAgreements);
        $this->serviceLevelAgreements = $serviceLevelAgreements;
        return $this;
    }

    public function addToServiceLevelAgreements(ServiceLevelAgreement $item): self
    {
        $this->serviceLevelAgreements[] = $item;
        return $this;
    }

    /**
     * @param list<ServiceLevelAgreement> $values
     */
    private static function validateServiceLevelAgreements(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ServiceLevelAgreement) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ServiceLevelAgreement, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
