<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Digital Collaboration. Details
 *  A class to describe a digital trade collaboration.
 *  Digital Collaboration
 *  Business Collaboration
 */
#[XmlType(localName: 'DigitalCollaborationType', namespace: Ns::CAC)]
final class DigitalCollaboration
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'SendingDigitalService', namespace: Ns::CAC)]
    private ?DigitalService $sendingDigitalService = null;

    #[XmlElement(name: 'ReceivingDigitalService', namespace: Ns::CAC)]
    private ?DigitalService $receivingDigitalService = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getSendingDigitalService(): ?DigitalService
    {
        return $this->sendingDigitalService;
    }

    public function setSendingDigitalService(?DigitalService $sendingDigitalService = null): self
    {
        $this->sendingDigitalService = $sendingDigitalService;
        return $this;
    }

    public function getReceivingDigitalService(): ?DigitalService
    {
        return $this->receivingDigitalService;
    }

    public function setReceivingDigitalService(?DigitalService $receivingDigitalService = null): self
    {
        $this->receivingDigitalService = $receivingDigitalService;
        return $this;
    }
}
