<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Digital Service. Details
 *  A class to describe a specific digital trade service supported by an organization for either sending or receiving business documents on different formats (e.g. UBL, ISO20022, EDIFACT, ...).
 *  Digital Service
 *  Business Transaction
 */
#[XmlType(localName: 'DigitalServiceType', namespace: Ns::CAC)]
final class DigitalService
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'CustomizationID', namespace: Ns::CBC)]
    private ?Identifier $customizationID = null;

    /** @var list<DocumentMetadata> */
    #[XmlElement(name: 'DigitalDocumentMetadata', namespace: Ns::CAC, type: DocumentMetadata::class, required: true)]
    private array $digitalDocumentMetadatas = [];

    /** @var list<DeliveryChannel> */
    #[XmlElement(name: 'DigitalDeliveryChannel', namespace: Ns::CAC, type: DeliveryChannel::class)]
    private array $digitalDeliveryChannels = [];

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'CertificationDocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $certificationDocumentReferences = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getCustomizationID(): ?Identifier
    {
        return $this->customizationID;
    }

    public function setCustomizationID(?Identifier $customizationID = null): self
    {
        $this->customizationID = $customizationID;
        return $this;
    }

    /**
     * @return list<DocumentMetadata>
     */
    public function getDigitalDocumentMetadatas(): array
    {
        return $this->digitalDocumentMetadatas;
    }

    /**
     * @param list<DocumentMetadata> $digitalDocumentMetadatas
     */
    public function setDigitalDocumentMetadatas(array $digitalDocumentMetadatas): self
    {
        self::validateDigitalDocumentMetadatas($digitalDocumentMetadatas);
        $this->digitalDocumentMetadatas = $digitalDocumentMetadatas;
        return $this;
    }

    public function addToDigitalDocumentMetadatas(DocumentMetadata $item): self
    {
        $this->digitalDocumentMetadatas[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentMetadata> $values
     */
    private static function validateDigitalDocumentMetadatas(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentMetadata) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentMetadata, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<DeliveryChannel>
     */
    public function getDigitalDeliveryChannels(): array
    {
        return $this->digitalDeliveryChannels;
    }

    /**
     * @param list<DeliveryChannel> $digitalDeliveryChannels
     */
    public function setDigitalDeliveryChannels(array $digitalDeliveryChannels): self
    {
        self::validateDigitalDeliveryChannels($digitalDeliveryChannels);
        $this->digitalDeliveryChannels = $digitalDeliveryChannels;
        return $this;
    }

    public function addToDigitalDeliveryChannels(DeliveryChannel $item): self
    {
        $this->digitalDeliveryChannels[] = $item;
        return $this;
    }

    /**
     * @param list<DeliveryChannel> $values
     */
    private static function validateDigitalDeliveryChannels(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DeliveryChannel) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DeliveryChannel, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<DocumentReference>
     */
    public function getCertificationDocumentReferences(): array
    {
        return $this->certificationDocumentReferences;
    }

    /**
     * @param list<DocumentReference> $certificationDocumentReferences
     */
    public function setCertificationDocumentReferences(array $certificationDocumentReferences): self
    {
        self::validateCertificationDocumentReferences($certificationDocumentReferences);
        $this->certificationDocumentReferences = $certificationDocumentReferences;
        return $this;
    }

    public function addToCertificationDocumentReferences(DocumentReference $item): self
    {
        $this->certificationDocumentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateCertificationDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
