<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Numeric;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Document Distribution. Details
 *  A class to describe the distribution of a document to an interested party.
 *  Document Distribution
 */
#[XmlType(localName: 'DocumentDistributionType', namespace: Ns::CAC)]
final class DocumentDistribution
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'DocumentTypeCode', namespace: Ns::CBC)]
    private ?Code $documentTypeCode = null;

    #[XmlElement(name: 'DistributionTypeCode', namespace: Ns::CBC)]
    private ?Code $distributionTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'DistributionType', namespace: Ns::CBC, type: Text::class)]
    private array $distributionTypes = [];

    #[XmlElement(name: 'PrintQualifier', namespace: Ns::CBC)]
    private ?Text $printQualifier = null;

    #[XmlElement(name: 'CopyIndicator', namespace: Ns::CBC)]
    private ?bool $copyIndicator = null;

    #[XmlElement(name: 'MaximumCopiesNumeric', namespace: Ns::CBC)]
    private ?Numeric $maximumCopiesNumeric = null;

    #[XmlElement(name: 'MaximumOriginalsNumeric', namespace: Ns::CBC)]
    private ?Numeric $maximumOriginalsNumeric = null;

    #[XmlElement(name: 'Communication', namespace: Ns::CAC)]
    private ?Communication $communication = null;

    #[XmlElement(name: 'Party', namespace: Ns::CAC, required: true)]
    private Party $party;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getDocumentTypeCode(): ?Code
    {
        return $this->documentTypeCode;
    }

    public function setDocumentTypeCode(?Code $documentTypeCode = null): self
    {
        $this->documentTypeCode = $documentTypeCode;
        return $this;
    }

    public function getDistributionTypeCode(): ?Code
    {
        return $this->distributionTypeCode;
    }

    public function setDistributionTypeCode(?Code $distributionTypeCode = null): self
    {
        $this->distributionTypeCode = $distributionTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDistributionTypes(): array
    {
        return $this->distributionTypes;
    }

    /**
     * @param list<Text> $distributionTypes
     */
    public function setDistributionTypes(array $distributionTypes): self
    {
        self::validateDistributionTypes($distributionTypes);
        $this->distributionTypes = $distributionTypes;
        return $this;
    }

    public function addToDistributionTypes(Text $item): self
    {
        $this->distributionTypes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDistributionTypes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPrintQualifier(): ?Text
    {
        return $this->printQualifier;
    }

    public function setPrintQualifier(?Text $printQualifier = null): self
    {
        $this->printQualifier = $printQualifier;
        return $this;
    }

    public function getCopyIndicator(): ?bool
    {
        return $this->copyIndicator;
    }

    public function setCopyIndicator(?bool $copyIndicator = null): self
    {
        $this->copyIndicator = $copyIndicator;
        return $this;
    }

    public function getMaximumCopiesNumeric(): ?Numeric
    {
        return $this->maximumCopiesNumeric;
    }

    public function setMaximumCopiesNumeric(?Numeric $maximumCopiesNumeric = null): self
    {
        $this->maximumCopiesNumeric = $maximumCopiesNumeric;
        return $this;
    }

    public function getMaximumOriginalsNumeric(): ?Numeric
    {
        return $this->maximumOriginalsNumeric;
    }

    public function setMaximumOriginalsNumeric(?Numeric $maximumOriginalsNumeric = null): self
    {
        $this->maximumOriginalsNumeric = $maximumOriginalsNumeric;
        return $this;
    }

    public function getCommunication(): ?Communication
    {
        return $this->communication;
    }

    public function setCommunication(?Communication $communication = null): self
    {
        $this->communication = $communication;
        return $this;
    }

    public function getParty(): Party
    {
        return $this->party;
    }

    public function setParty(Party $party): self
    {
        $this->party = $party;
        return $this;
    }
}
