<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Encryption Certificate Path Chain. Details
 *  Details of a certificate path chain used in encryption.
 *  Encryption Certificate Path Chain
 */
#[XmlType(localName: 'EncryptionCertificatePathChainType', namespace: Ns::CAC)]
final class EncryptionCertificatePathChain
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'Value', namespace: Ns::CBC)]
    private ?Text $value = null;

    #[XmlElement(name: 'URI', namespace: Ns::CBC)]
    private ?Identifier $uri = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getValue(): ?Text
    {
        return $this->value;
    }

    public function setValue(?Text $value = null): self
    {
        $this->value = $value;
        return $this;
    }

    public function getUri(): ?Identifier
    {
        return $this->uri;
    }

    public function setUri(?Identifier $uri = null): self
    {
        $this->uri = $uri;
        return $this;
    }
}
