<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Numeric;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Event Line Item. Details
 *  A class to define a line item describing the expected impacts associated with a retail event involving a specific product at a specific location.
 *  Event Line Item
 */
#[XmlType(localName: 'EventLineItemType', namespace: Ns::CAC)]
final class EventLineItem
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'LineNumberNumeric', namespace: Ns::CBC)]
    private ?Numeric $lineNumberNumeric = null;

    #[XmlElement(name: 'ParticipatingLocationsLocation', namespace: Ns::CAC)]
    private ?Location $participatingLocationsLocation = null;

    /** @var list<RetailPlannedImpact> */
    #[XmlElement(name: 'RetailPlannedImpact', namespace: Ns::CAC, type: RetailPlannedImpact::class)]
    private array $retailPlannedImpacts = [];

    #[XmlElement(name: 'SupplyItem', namespace: Ns::CAC, required: true)]
    private Item $supplyItem;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getLineNumberNumeric(): ?Numeric
    {
        return $this->lineNumberNumeric;
    }

    public function setLineNumberNumeric(?Numeric $lineNumberNumeric = null): self
    {
        $this->lineNumberNumeric = $lineNumberNumeric;
        return $this;
    }

    public function getParticipatingLocationsLocation(): ?Location
    {
        return $this->participatingLocationsLocation;
    }

    public function setParticipatingLocationsLocation(?Location $participatingLocationsLocation = null): self
    {
        $this->participatingLocationsLocation = $participatingLocationsLocation;
        return $this;
    }

    /**
     * @return list<RetailPlannedImpact>
     */
    public function getRetailPlannedImpacts(): array
    {
        return $this->retailPlannedImpacts;
    }

    /**
     * @param list<RetailPlannedImpact> $retailPlannedImpacts
     */
    public function setRetailPlannedImpacts(array $retailPlannedImpacts): self
    {
        self::validateRetailPlannedImpacts($retailPlannedImpacts);
        $this->retailPlannedImpacts = $retailPlannedImpacts;
        return $this;
    }

    public function addToRetailPlannedImpacts(RetailPlannedImpact $item): self
    {
        $this->retailPlannedImpacts[] = $item;
        return $this;
    }

    /**
     * @param list<RetailPlannedImpact> $values
     */
    private static function validateRetailPlannedImpacts(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof RetailPlannedImpact) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of RetailPlannedImpact, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getSupplyItem(): Item
    {
        return $this->supplyItem;
    }

    public function setSupplyItem(Item $supplyItem): self
    {
        $this->supplyItem = $supplyItem;
        return $this;
    }
}
