<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Numeric;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Exchange Rate. Details
 *  A class to define an exchange rate.
 *  Exchange Rate
 */
#[XmlType(localName: 'ExchangeRateType', namespace: Ns::CAC)]
final class ExchangeRate
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'SourceCurrencyCode', namespace: Ns::CBC, required: true)]
    private Code $sourceCurrencyCode;

    #[XmlElement(name: 'SourceCurrencyBaseRate', namespace: Ns::CBC)]
    private ?Numeric $sourceCurrencyBaseRate = null;

    #[XmlElement(name: 'TargetCurrencyCode', namespace: Ns::CBC, required: true)]
    private Code $targetCurrencyCode;

    #[XmlElement(name: 'TargetCurrencyBaseRate', namespace: Ns::CBC)]
    private ?Numeric $targetCurrencyBaseRate = null;

    #[XmlElement(name: 'ExchangeMarketID', namespace: Ns::CBC)]
    private ?Identifier $exchangeMarketID = null;

    #[XmlElement(name: 'CalculationRate', namespace: Ns::CBC)]
    private ?Numeric $calculationRate = null;

    #[XmlElement(name: 'MathematicOperatorCode', namespace: Ns::CBC)]
    private ?Code $mathematicOperatorCode = null;

    #[XmlElement(name: 'Date', namespace: Ns::CBC)]
    private ?DateTimeImmutable $date = null;

    #[XmlElement(name: 'ForeignExchangeContract', namespace: Ns::CAC)]
    private ?Contract $foreignExchangeContract = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getSourceCurrencyCode(): Code
    {
        return $this->sourceCurrencyCode;
    }

    public function setSourceCurrencyCode(Code $sourceCurrencyCode): self
    {
        $this->sourceCurrencyCode = $sourceCurrencyCode;
        return $this;
    }

    public function getSourceCurrencyBaseRate(): ?Numeric
    {
        return $this->sourceCurrencyBaseRate;
    }

    public function setSourceCurrencyBaseRate(?Numeric $sourceCurrencyBaseRate = null): self
    {
        $this->sourceCurrencyBaseRate = $sourceCurrencyBaseRate;
        return $this;
    }

    public function getTargetCurrencyCode(): Code
    {
        return $this->targetCurrencyCode;
    }

    public function setTargetCurrencyCode(Code $targetCurrencyCode): self
    {
        $this->targetCurrencyCode = $targetCurrencyCode;
        return $this;
    }

    public function getTargetCurrencyBaseRate(): ?Numeric
    {
        return $this->targetCurrencyBaseRate;
    }

    public function setTargetCurrencyBaseRate(?Numeric $targetCurrencyBaseRate = null): self
    {
        $this->targetCurrencyBaseRate = $targetCurrencyBaseRate;
        return $this;
    }

    public function getExchangeMarketID(): ?Identifier
    {
        return $this->exchangeMarketID;
    }

    public function setExchangeMarketID(?Identifier $exchangeMarketID = null): self
    {
        $this->exchangeMarketID = $exchangeMarketID;
        return $this;
    }

    public function getCalculationRate(): ?Numeric
    {
        return $this->calculationRate;
    }

    public function setCalculationRate(?Numeric $calculationRate = null): self
    {
        $this->calculationRate = $calculationRate;
        return $this;
    }

    public function getMathematicOperatorCode(): ?Code
    {
        return $this->mathematicOperatorCode;
    }

    public function setMathematicOperatorCode(?Code $mathematicOperatorCode = null): self
    {
        $this->mathematicOperatorCode = $mathematicOperatorCode;
        return $this;
    }

    public function getDate(): ?DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(?DateTimeImmutable $date = null): self
    {
        $this->date = $date;
        return $this;
    }

    public function getForeignExchangeContract(): ?Contract
    {
        return $this->foreignExchangeContract;
    }

    public function setForeignExchangeContract(?Contract $foreignExchangeContract = null): self
    {
        $this->foreignExchangeContract = $foreignExchangeContract;
        return $this;
    }
}
