<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Financial Account. Details
 *  A class to describe a financial account.
 *  Financial Account
 */
#[XmlType(localName: 'FinancialAccountType', namespace: Ns::CAC)]
final class FinancialAccount
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'AliasName', namespace: Ns::CBC)]
    private ?Text $aliasName = null;

    #[XmlElement(name: 'AccountTypeCode', namespace: Ns::CBC)]
    private ?Code $accountTypeCode = null;

    #[XmlElement(name: 'AccountFormatCode', namespace: Ns::CBC)]
    private ?Code $accountFormatCode = null;

    #[XmlElement(name: 'CurrencyCode', namespace: Ns::CBC)]
    private ?Code $currencyCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'PaymentNote', namespace: Ns::CBC, type: Text::class)]
    private array $paymentNotes = [];

    #[XmlElement(name: 'FinancialInstitutionBranch', namespace: Ns::CAC)]
    private ?Branch $financialInstitutionBranch = null;

    #[XmlElement(name: 'Country', namespace: Ns::CAC)]
    private ?Country $country = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getAliasName(): ?Text
    {
        return $this->aliasName;
    }

    public function setAliasName(?Text $aliasName = null): self
    {
        $this->aliasName = $aliasName;
        return $this;
    }

    public function getAccountTypeCode(): ?Code
    {
        return $this->accountTypeCode;
    }

    public function setAccountTypeCode(?Code $accountTypeCode = null): self
    {
        $this->accountTypeCode = $accountTypeCode;
        return $this;
    }

    public function getAccountFormatCode(): ?Code
    {
        return $this->accountFormatCode;
    }

    public function setAccountFormatCode(?Code $accountFormatCode = null): self
    {
        $this->accountFormatCode = $accountFormatCode;
        return $this;
    }

    public function getCurrencyCode(): ?Code
    {
        return $this->currencyCode;
    }

    public function setCurrencyCode(?Code $currencyCode = null): self
    {
        $this->currencyCode = $currencyCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getPaymentNotes(): array
    {
        return $this->paymentNotes;
    }

    /**
     * @param list<Text> $paymentNotes
     */
    public function setPaymentNotes(array $paymentNotes): self
    {
        self::validatePaymentNotes($paymentNotes);
        $this->paymentNotes = $paymentNotes;
        return $this;
    }

    public function addToPaymentNotes(Text $item): self
    {
        $this->paymentNotes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validatePaymentNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getFinancialInstitutionBranch(): ?Branch
    {
        return $this->financialInstitutionBranch;
    }

    public function setFinancialInstitutionBranch(?Branch $financialInstitutionBranch = null): self
    {
        $this->financialInstitutionBranch = $financialInstitutionBranch;
        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country = null): self
    {
        $this->country = $country;
        return $this;
    }
}
