<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Forecast Exception. Details
 *  As explained in Exception Criteria Line: Three types of exception criteria can be defined, Operational, Metric or Forecast Exceptions. This class provides criteria for forecast exception type: the identification of the purpose of the forecast, the source of data and the time basis criteria for the exception.
 *  Forecast Exception
 */
#[XmlType(localName: 'ForecastExceptionType', namespace: Ns::CAC)]
final class ForecastException
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ForecastPurposeCode', namespace: Ns::CBC, required: true)]
    private Code $forecastPurposeCode;

    #[XmlElement(name: 'ForecastTypeCode', namespace: Ns::CBC, required: true)]
    private Code $forecastTypeCode;

    #[XmlElement(name: 'IssueDate', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $issueDate;

    #[XmlElement(name: 'IssueTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $issueTime = null;

    #[XmlElement(name: 'DataSourceCode', namespace: Ns::CBC, required: true)]
    private Code $dataSourceCode;

    #[XmlElement(name: 'ComparisonDataCode', namespace: Ns::CBC)]
    private ?Code $comparisonDataCode = null;

    #[XmlElement(name: 'ComparisonForecastIssueTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $comparisonForecastIssueTime = null;

    #[XmlElement(name: 'ComparisonForecastIssueDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $comparisonForecastIssueDate = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getForecastPurposeCode(): Code
    {
        return $this->forecastPurposeCode;
    }

    public function setForecastPurposeCode(Code $forecastPurposeCode): self
    {
        $this->forecastPurposeCode = $forecastPurposeCode;
        return $this;
    }

    public function getForecastTypeCode(): Code
    {
        return $this->forecastTypeCode;
    }

    public function setForecastTypeCode(Code $forecastTypeCode): self
    {
        $this->forecastTypeCode = $forecastTypeCode;
        return $this;
    }

    public function getIssueDate(): DateTimeImmutable
    {
        return $this->issueDate;
    }

    public function setIssueDate(DateTimeImmutable $issueDate): self
    {
        $this->issueDate = $issueDate;
        return $this;
    }

    public function getIssueTime(): ?DateTimeImmutable
    {
        return $this->issueTime;
    }

    public function setIssueTime(?DateTimeImmutable $issueTime = null): self
    {
        $this->issueTime = $issueTime;
        return $this;
    }

    public function getDataSourceCode(): Code
    {
        return $this->dataSourceCode;
    }

    public function setDataSourceCode(Code $dataSourceCode): self
    {
        $this->dataSourceCode = $dataSourceCode;
        return $this;
    }

    public function getComparisonDataCode(): ?Code
    {
        return $this->comparisonDataCode;
    }

    public function setComparisonDataCode(?Code $comparisonDataCode = null): self
    {
        $this->comparisonDataCode = $comparisonDataCode;
        return $this;
    }

    public function getComparisonForecastIssueTime(): ?DateTimeImmutable
    {
        return $this->comparisonForecastIssueTime;
    }

    public function setComparisonForecastIssueTime(?DateTimeImmutable $comparisonForecastIssueTime = null): self
    {
        $this->comparisonForecastIssueTime = $comparisonForecastIssueTime;
        return $this;
    }

    public function getComparisonForecastIssueDate(): ?DateTimeImmutable
    {
        return $this->comparisonForecastIssueDate;
    }

    public function setComparisonForecastIssueDate(?DateTimeImmutable $comparisonForecastIssueDate = null): self
    {
        $this->comparisonForecastIssueDate = $comparisonForecastIssueDate;
        return $this;
    }
}
