<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Hazardous Goods Transit. Details
 *  A class to describe hazardous goods in transit.
 *  Hazardous Goods Transit
 */
#[XmlType(localName: 'HazardousGoodsTransitType', namespace: Ns::CAC)]
final class HazardousGoodsTransit
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'TransportEmergencyCardCode', namespace: Ns::CBC)]
    private ?Code $transportEmergencyCardCode = null;

    #[XmlElement(name: 'PackingCriteriaCode', namespace: Ns::CBC)]
    private ?Code $packingCriteriaCode = null;

    #[XmlElement(name: 'HazardousRegulationCode', namespace: Ns::CBC)]
    private ?Code $hazardousRegulationCode = null;

    #[XmlElement(name: 'InhalationToxicityZoneCode', namespace: Ns::CBC)]
    private ?Code $inhalationToxicityZoneCode = null;

    #[XmlElement(name: 'TransportAuthorizationCode', namespace: Ns::CBC)]
    private ?Code $transportAuthorizationCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'TransitDescription', namespace: Ns::CBC, type: Text::class)]
    private array $transitDescriptions = [];

    #[XmlElement(name: 'MaximumTemperature', namespace: Ns::CAC)]
    private ?Temperature $maximumTemperature = null;

    #[XmlElement(name: 'MinimumTemperature', namespace: Ns::CAC)]
    private ?Temperature $minimumTemperature = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getTransportEmergencyCardCode(): ?Code
    {
        return $this->transportEmergencyCardCode;
    }

    public function setTransportEmergencyCardCode(?Code $transportEmergencyCardCode = null): self
    {
        $this->transportEmergencyCardCode = $transportEmergencyCardCode;
        return $this;
    }

    public function getPackingCriteriaCode(): ?Code
    {
        return $this->packingCriteriaCode;
    }

    public function setPackingCriteriaCode(?Code $packingCriteriaCode = null): self
    {
        $this->packingCriteriaCode = $packingCriteriaCode;
        return $this;
    }

    public function getHazardousRegulationCode(): ?Code
    {
        return $this->hazardousRegulationCode;
    }

    public function setHazardousRegulationCode(?Code $hazardousRegulationCode = null): self
    {
        $this->hazardousRegulationCode = $hazardousRegulationCode;
        return $this;
    }

    public function getInhalationToxicityZoneCode(): ?Code
    {
        return $this->inhalationToxicityZoneCode;
    }

    public function setInhalationToxicityZoneCode(?Code $inhalationToxicityZoneCode = null): self
    {
        $this->inhalationToxicityZoneCode = $inhalationToxicityZoneCode;
        return $this;
    }

    public function getTransportAuthorizationCode(): ?Code
    {
        return $this->transportAuthorizationCode;
    }

    public function setTransportAuthorizationCode(?Code $transportAuthorizationCode = null): self
    {
        $this->transportAuthorizationCode = $transportAuthorizationCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getTransitDescriptions(): array
    {
        return $this->transitDescriptions;
    }

    /**
     * @param list<Text> $transitDescriptions
     */
    public function setTransitDescriptions(array $transitDescriptions): self
    {
        self::validateTransitDescriptions($transitDescriptions);
        $this->transitDescriptions = $transitDescriptions;
        return $this;
    }

    public function addToTransitDescriptions(Text $item): self
    {
        $this->transitDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateTransitDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getMaximumTemperature(): ?Temperature
    {
        return $this->maximumTemperature;
    }

    public function setMaximumTemperature(?Temperature $maximumTemperature = null): self
    {
        $this->maximumTemperature = $maximumTemperature;
        return $this;
    }

    public function getMinimumTemperature(): ?Temperature
    {
        return $this->minimumTemperature;
    }

    public function setMinimumTemperature(?Temperature $minimumTemperature = null): self
    {
        $this->minimumTemperature = $minimumTemperature;
        return $this;
    }
}
