<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Measure;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Hazardous Item. Details
 *  A class to describe a hazardous item.
 *  Hazardous Item
 */
#[XmlType(localName: 'HazardousItemType', namespace: Ns::CAC)]
final class HazardousItem
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'PlacardNotation', namespace: Ns::CBC)]
    private ?Text $placardNotation = null;

    #[XmlElement(name: 'PlacardEndorsement', namespace: Ns::CBC)]
    private ?Text $placardEndorsement = null;

    /** @var list<Text> */
    #[XmlElement(name: 'AdditionalInformation', namespace: Ns::CBC, type: Text::class)]
    private array $additionalInformations = [];

    #[XmlElement(name: 'UNDGCode', namespace: Ns::CBC)]
    private ?Code $undgCode = null;

    #[XmlElement(name: 'UNPackingGroupCode', namespace: Ns::CBC)]
    private ?Code $unPackingGroupCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'UNPackingGroup', namespace: Ns::CBC, type: Text::class)]
    private array $unPackingGroups = [];

    #[XmlElement(name: 'EmergencyProceduresCode', namespace: Ns::CBC)]
    private ?Code $emergencyProceduresCode = null;

    #[XmlElement(name: 'MedicalFirstAidGuideCode', namespace: Ns::CBC)]
    private ?Code $medicalFirstAidGuideCode = null;

    #[XmlElement(name: 'TunnelRestrictionCode', namespace: Ns::CBC)]
    private ?Code $tunnelRestrictionCode = null;

    #[XmlElement(name: 'MaritimePollutantCode', namespace: Ns::CBC)]
    private ?Code $maritimePollutantCode = null;

    #[XmlElement(name: 'TechnicalName', namespace: Ns::CBC)]
    private ?Text $technicalName = null;

    #[XmlElement(name: 'CategoryName', namespace: Ns::CBC)]
    private ?Text $categoryName = null;

    #[XmlElement(name: 'HazardousCategoryCode', namespace: Ns::CBC)]
    private ?Code $hazardousCategoryCode = null;

    #[XmlElement(name: 'UpperOrangeHazardPlacardID', namespace: Ns::CBC)]
    private ?Identifier $upperOrangeHazardPlacardID = null;

    #[XmlElement(name: 'LowerOrangeHazardPlacardID', namespace: Ns::CBC)]
    private ?Identifier $lowerOrangeHazardPlacardID = null;

    #[XmlElement(name: 'MarkingID', namespace: Ns::CBC)]
    private ?Identifier $markingID = null;

    #[XmlElement(name: 'HazardClassID', namespace: Ns::CBC)]
    private ?Identifier $hazardClassID = null;

    #[XmlElement(name: 'NetWeightMeasure', namespace: Ns::CBC)]
    private ?Measure $netWeightMeasure = null;

    #[XmlElement(name: 'NetVolumeMeasure', namespace: Ns::CBC)]
    private ?Measure $netVolumeMeasure = null;

    #[XmlElement(name: 'Quantity', namespace: Ns::CBC)]
    private ?Quantity $quantity = null;

    #[XmlElement(name: 'ContactParty', namespace: Ns::CAC)]
    private ?Party $contactParty = null;

    /** @var list<SecondaryHazard> */
    #[XmlElement(name: 'SecondaryHazard', namespace: Ns::CAC, type: SecondaryHazard::class)]
    private array $secondaryHazards = [];

    /** @var list<HazardousGoodsTransit> */
    #[XmlElement(name: 'HazardousGoodsTransit', namespace: Ns::CAC, type: HazardousGoodsTransit::class)]
    private array $hazardousGoodsTransits = [];

    #[XmlElement(name: 'EmergencyTemperature', namespace: Ns::CAC)]
    private ?Temperature $emergencyTemperature = null;

    #[XmlElement(name: 'FlashpointTemperature', namespace: Ns::CAC)]
    private ?Temperature $flashpointTemperature = null;

    /** @var list<Temperature> */
    #[XmlElement(name: 'AdditionalTemperature', namespace: Ns::CAC, type: Temperature::class)]
    private array $additionalTemperatures = [];

    #[XmlElement(name: 'PositionOnBoardStowage', namespace: Ns::CAC)]
    private ?Stowage $positionOnBoardStowage = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getPlacardNotation(): ?Text
    {
        return $this->placardNotation;
    }

    public function setPlacardNotation(?Text $placardNotation = null): self
    {
        $this->placardNotation = $placardNotation;
        return $this;
    }

    public function getPlacardEndorsement(): ?Text
    {
        return $this->placardEndorsement;
    }

    public function setPlacardEndorsement(?Text $placardEndorsement = null): self
    {
        $this->placardEndorsement = $placardEndorsement;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getAdditionalInformations(): array
    {
        return $this->additionalInformations;
    }

    /**
     * @param list<Text> $additionalInformations
     */
    public function setAdditionalInformations(array $additionalInformations): self
    {
        self::validateAdditionalInformations($additionalInformations);
        $this->additionalInformations = $additionalInformations;
        return $this;
    }

    public function addToAdditionalInformations(Text $item): self
    {
        $this->additionalInformations[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateAdditionalInformations(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getUndgCode(): ?Code
    {
        return $this->undgCode;
    }

    public function setUndgCode(?Code $undgCode = null): self
    {
        $this->undgCode = $undgCode;
        return $this;
    }

    public function getUnPackingGroupCode(): ?Code
    {
        return $this->unPackingGroupCode;
    }

    public function setUnPackingGroupCode(?Code $unPackingGroupCode = null): self
    {
        $this->unPackingGroupCode = $unPackingGroupCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getUnPackingGroups(): array
    {
        return $this->unPackingGroups;
    }

    /**
     * @param list<Text> $unPackingGroups
     */
    public function setUnPackingGroups(array $unPackingGroups): self
    {
        self::validateUnPackingGroups($unPackingGroups);
        $this->unPackingGroups = $unPackingGroups;
        return $this;
    }

    public function addToUnPackingGroups(Text $item): self
    {
        $this->unPackingGroups[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateUnPackingGroups(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getEmergencyProceduresCode(): ?Code
    {
        return $this->emergencyProceduresCode;
    }

    public function setEmergencyProceduresCode(?Code $emergencyProceduresCode = null): self
    {
        $this->emergencyProceduresCode = $emergencyProceduresCode;
        return $this;
    }

    public function getMedicalFirstAidGuideCode(): ?Code
    {
        return $this->medicalFirstAidGuideCode;
    }

    public function setMedicalFirstAidGuideCode(?Code $medicalFirstAidGuideCode = null): self
    {
        $this->medicalFirstAidGuideCode = $medicalFirstAidGuideCode;
        return $this;
    }

    public function getTunnelRestrictionCode(): ?Code
    {
        return $this->tunnelRestrictionCode;
    }

    public function setTunnelRestrictionCode(?Code $tunnelRestrictionCode = null): self
    {
        $this->tunnelRestrictionCode = $tunnelRestrictionCode;
        return $this;
    }

    public function getMaritimePollutantCode(): ?Code
    {
        return $this->maritimePollutantCode;
    }

    public function setMaritimePollutantCode(?Code $maritimePollutantCode = null): self
    {
        $this->maritimePollutantCode = $maritimePollutantCode;
        return $this;
    }

    public function getTechnicalName(): ?Text
    {
        return $this->technicalName;
    }

    public function setTechnicalName(?Text $technicalName = null): self
    {
        $this->technicalName = $technicalName;
        return $this;
    }

    public function getCategoryName(): ?Text
    {
        return $this->categoryName;
    }

    public function setCategoryName(?Text $categoryName = null): self
    {
        $this->categoryName = $categoryName;
        return $this;
    }

    public function getHazardousCategoryCode(): ?Code
    {
        return $this->hazardousCategoryCode;
    }

    public function setHazardousCategoryCode(?Code $hazardousCategoryCode = null): self
    {
        $this->hazardousCategoryCode = $hazardousCategoryCode;
        return $this;
    }

    public function getUpperOrangeHazardPlacardID(): ?Identifier
    {
        return $this->upperOrangeHazardPlacardID;
    }

    public function setUpperOrangeHazardPlacardID(?Identifier $upperOrangeHazardPlacardID = null): self
    {
        $this->upperOrangeHazardPlacardID = $upperOrangeHazardPlacardID;
        return $this;
    }

    public function getLowerOrangeHazardPlacardID(): ?Identifier
    {
        return $this->lowerOrangeHazardPlacardID;
    }

    public function setLowerOrangeHazardPlacardID(?Identifier $lowerOrangeHazardPlacardID = null): self
    {
        $this->lowerOrangeHazardPlacardID = $lowerOrangeHazardPlacardID;
        return $this;
    }

    public function getMarkingID(): ?Identifier
    {
        return $this->markingID;
    }

    public function setMarkingID(?Identifier $markingID = null): self
    {
        $this->markingID = $markingID;
        return $this;
    }

    public function getHazardClassID(): ?Identifier
    {
        return $this->hazardClassID;
    }

    public function setHazardClassID(?Identifier $hazardClassID = null): self
    {
        $this->hazardClassID = $hazardClassID;
        return $this;
    }

    public function getNetWeightMeasure(): ?Measure
    {
        return $this->netWeightMeasure;
    }

    public function setNetWeightMeasure(?Measure $netWeightMeasure = null): self
    {
        $this->netWeightMeasure = $netWeightMeasure;
        return $this;
    }

    public function getNetVolumeMeasure(): ?Measure
    {
        return $this->netVolumeMeasure;
    }

    public function setNetVolumeMeasure(?Measure $netVolumeMeasure = null): self
    {
        $this->netVolumeMeasure = $netVolumeMeasure;
        return $this;
    }

    public function getQuantity(): ?Quantity
    {
        return $this->quantity;
    }

    public function setQuantity(?Quantity $quantity = null): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getContactParty(): ?Party
    {
        return $this->contactParty;
    }

    public function setContactParty(?Party $contactParty = null): self
    {
        $this->contactParty = $contactParty;
        return $this;
    }

    /**
     * @return list<SecondaryHazard>
     */
    public function getSecondaryHazards(): array
    {
        return $this->secondaryHazards;
    }

    /**
     * @param list<SecondaryHazard> $secondaryHazards
     */
    public function setSecondaryHazards(array $secondaryHazards): self
    {
        self::validateSecondaryHazards($secondaryHazards);
        $this->secondaryHazards = $secondaryHazards;
        return $this;
    }

    public function addToSecondaryHazards(SecondaryHazard $item): self
    {
        $this->secondaryHazards[] = $item;
        return $this;
    }

    /**
     * @param list<SecondaryHazard> $values
     */
    private static function validateSecondaryHazards(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof SecondaryHazard) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of SecondaryHazard, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<HazardousGoodsTransit>
     */
    public function getHazardousGoodsTransits(): array
    {
        return $this->hazardousGoodsTransits;
    }

    /**
     * @param list<HazardousGoodsTransit> $hazardousGoodsTransits
     */
    public function setHazardousGoodsTransits(array $hazardousGoodsTransits): self
    {
        self::validateHazardousGoodsTransits($hazardousGoodsTransits);
        $this->hazardousGoodsTransits = $hazardousGoodsTransits;
        return $this;
    }

    public function addToHazardousGoodsTransits(HazardousGoodsTransit $item): self
    {
        $this->hazardousGoodsTransits[] = $item;
        return $this;
    }

    /**
     * @param list<HazardousGoodsTransit> $values
     */
    private static function validateHazardousGoodsTransits(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof HazardousGoodsTransit) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of HazardousGoodsTransit, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getEmergencyTemperature(): ?Temperature
    {
        return $this->emergencyTemperature;
    }

    public function setEmergencyTemperature(?Temperature $emergencyTemperature = null): self
    {
        $this->emergencyTemperature = $emergencyTemperature;
        return $this;
    }

    public function getFlashpointTemperature(): ?Temperature
    {
        return $this->flashpointTemperature;
    }

    public function setFlashpointTemperature(?Temperature $flashpointTemperature = null): self
    {
        $this->flashpointTemperature = $flashpointTemperature;
        return $this;
    }

    /**
     * @return list<Temperature>
     */
    public function getAdditionalTemperatures(): array
    {
        return $this->additionalTemperatures;
    }

    /**
     * @param list<Temperature> $additionalTemperatures
     */
    public function setAdditionalTemperatures(array $additionalTemperatures): self
    {
        self::validateAdditionalTemperatures($additionalTemperatures);
        $this->additionalTemperatures = $additionalTemperatures;
        return $this;
    }

    public function addToAdditionalTemperatures(Temperature $item): self
    {
        $this->additionalTemperatures[] = $item;
        return $this;
    }

    /**
     * @param list<Temperature> $values
     */
    private static function validateAdditionalTemperatures(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Temperature) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Temperature, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPositionOnBoardStowage(): ?Stowage
    {
        return $this->positionOnBoardStowage;
    }

    public function setPositionOnBoardStowage(?Stowage $positionOnBoardStowage = null): self
    {
        $this->positionOnBoardStowage = $positionOnBoardStowage;
        return $this;
    }
}
