<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Item Instance. Details
 *  A class to describe a specific, trackable instance of an item.
 *  Item Instance
 */
#[XmlType(localName: 'ItemInstanceType', namespace: Ns::CAC)]
final class ItemInstance
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ProductTraceID', namespace: Ns::CBC)]
    private ?Identifier $productTraceID = null;

    #[XmlElement(name: 'ManufactureDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $manufactureDate = null;

    #[XmlElement(name: 'ManufactureTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $manufactureTime = null;

    #[XmlElement(name: 'BestBeforeDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $bestBeforeDate = null;

    #[XmlElement(name: 'RegistrationID', namespace: Ns::CBC)]
    private ?Identifier $registrationID = null;

    #[XmlElement(name: 'SerialID', namespace: Ns::CBC)]
    private ?Identifier $serialID = null;

    /** @var list<ItemProperty> */
    #[XmlElement(name: 'AdditionalItemProperty', namespace: Ns::CAC, type: ItemProperty::class)]
    private array $additionalItemProperties = [];

    #[XmlElement(name: 'LotIdentification', namespace: Ns::CAC)]
    private ?LotIdentification $lotIdentification = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getProductTraceID(): ?Identifier
    {
        return $this->productTraceID;
    }

    public function setProductTraceID(?Identifier $productTraceID = null): self
    {
        $this->productTraceID = $productTraceID;
        return $this;
    }

    public function getManufactureDate(): ?DateTimeImmutable
    {
        return $this->manufactureDate;
    }

    public function setManufactureDate(?DateTimeImmutable $manufactureDate = null): self
    {
        $this->manufactureDate = $manufactureDate;
        return $this;
    }

    public function getManufactureTime(): ?DateTimeImmutable
    {
        return $this->manufactureTime;
    }

    public function setManufactureTime(?DateTimeImmutable $manufactureTime = null): self
    {
        $this->manufactureTime = $manufactureTime;
        return $this;
    }

    public function getBestBeforeDate(): ?DateTimeImmutable
    {
        return $this->bestBeforeDate;
    }

    public function setBestBeforeDate(?DateTimeImmutable $bestBeforeDate = null): self
    {
        $this->bestBeforeDate = $bestBeforeDate;
        return $this;
    }

    public function getRegistrationID(): ?Identifier
    {
        return $this->registrationID;
    }

    public function setRegistrationID(?Identifier $registrationID = null): self
    {
        $this->registrationID = $registrationID;
        return $this;
    }

    public function getSerialID(): ?Identifier
    {
        return $this->serialID;
    }

    public function setSerialID(?Identifier $serialID = null): self
    {
        $this->serialID = $serialID;
        return $this;
    }

    /**
     * @return list<ItemProperty>
     */
    public function getAdditionalItemProperties(): array
    {
        return $this->additionalItemProperties;
    }

    /**
     * @param list<ItemProperty> $additionalItemProperties
     */
    public function setAdditionalItemProperties(array $additionalItemProperties): self
    {
        self::validateAdditionalItemProperties($additionalItemProperties);
        $this->additionalItemProperties = $additionalItemProperties;
        return $this;
    }

    public function addToAdditionalItemProperties(ItemProperty $item): self
    {
        $this->additionalItemProperties[] = $item;
        return $this;
    }

    /**
     * @param list<ItemProperty> $values
     */
    private static function validateAdditionalItemProperties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ItemProperty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ItemProperty, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getLotIdentification(): ?LotIdentification
    {
        return $this->lotIdentification;
    }

    public function setLotIdentification(?LotIdentification $lotIdentification = null): self
    {
        $this->lotIdentification = $lotIdentification;
        return $this;
    }
}
