<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Amount;
use Xterr\Espd\Cbc\Quantity;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Item Comparison. Details
 *  A class to provide information about price and quantity of an item for use in price comparisons based on price, quantity, or measurements.
 *  Item Comparison
 */
#[XmlType(localName: 'ItemComparisonType', namespace: Ns::CAC)]
final class ItemComparison
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'PriceAmount', namespace: Ns::CBC)]
    private ?Amount $priceAmount = null;

    #[XmlElement(name: 'Quantity', namespace: Ns::CBC)]
    private ?Quantity $quantity = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getPriceAmount(): ?Amount
    {
        return $this->priceAmount;
    }

    public function setPriceAmount(?Amount $priceAmount = null): self
    {
        $this->priceAmount = $priceAmount;
        return $this;
    }

    public function getQuantity(): ?Quantity
    {
        return $this->quantity;
    }

    public function setQuantity(?Quantity $quantity = null): self
    {
        $this->quantity = $quantity;
        return $this;
    }
}
