<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Numeric;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Item. Details
 *  A class to describe an item of trade. It includes a generic description applicable to all examples of the item together with optional subsidiary descriptions of any number of actual instances of the type.
 *  Item
 *  article, product, goods item
 */
#[XmlType(localName: 'ItemType', namespace: Ns::CAC)]
final class Item
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'PackQuantity', namespace: Ns::CBC)]
    private ?Quantity $packQuantity = null;

    #[XmlElement(name: 'PackSizeNumeric', namespace: Ns::CBC)]
    private ?Numeric $packSizeNumeric = null;

    #[XmlElement(name: 'CatalogueIndicator', namespace: Ns::CBC)]
    private ?bool $catalogueIndicator = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'HazardousRiskIndicator', namespace: Ns::CBC)]
    private ?bool $hazardousRiskIndicator = null;

    /** @var list<Text> */
    #[XmlElement(name: 'AdditionalInformation', namespace: Ns::CBC, type: Text::class)]
    private array $additionalInformations = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Keyword', namespace: Ns::CBC, type: Text::class)]
    private array $keywords = [];

    /** @var list<Text> */
    #[XmlElement(name: 'BrandName', namespace: Ns::CBC, type: Text::class)]
    private array $brandNames = [];

    /** @var list<Text> */
    #[XmlElement(name: 'ModelName', namespace: Ns::CBC, type: Text::class)]
    private array $modelNames = [];

    #[XmlElement(name: 'BuyersItemIdentification', namespace: Ns::CAC)]
    private ?ItemIdentification $buyersItemIdentification = null;

    #[XmlElement(name: 'SellersItemIdentification', namespace: Ns::CAC)]
    private ?ItemIdentification $sellersItemIdentification = null;

    /** @var list<ItemIdentification> */
    #[XmlElement(name: 'ManufacturersItemIdentification', namespace: Ns::CAC, type: ItemIdentification::class)]
    private array $manufacturersItemIdentifications = [];

    #[XmlElement(name: 'StandardItemIdentification', namespace: Ns::CAC)]
    private ?ItemIdentification $standardItemIdentification = null;

    #[XmlElement(name: 'CatalogueItemIdentification', namespace: Ns::CAC)]
    private ?ItemIdentification $catalogueItemIdentification = null;

    /** @var list<ItemIdentification> */
    #[XmlElement(name: 'AdditionalItemIdentification', namespace: Ns::CAC, type: ItemIdentification::class)]
    private array $additionalItemIdentifications = [];

    #[XmlElement(name: 'CatalogueDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $catalogueDocumentReference = null;

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'ItemSpecificationDocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $itemSpecificationDocumentReferences = [];

    #[XmlElement(name: 'OriginCountry', namespace: Ns::CAC)]
    private ?Country $originCountry = null;

    /** @var list<CommodityClassification> */
    #[XmlElement(name: 'CommodityClassification', namespace: Ns::CAC, type: CommodityClassification::class)]
    private array $commodityClassifications = [];

    /** @var list<TransactionConditions> */
    #[XmlElement(name: 'TransactionConditions', namespace: Ns::CAC, type: TransactionConditions::class)]
    private array $transactionConditionses = [];

    /** @var list<HazardousItem> */
    #[XmlElement(name: 'HazardousItem', namespace: Ns::CAC, type: HazardousItem::class)]
    private array $hazardousItems = [];

    /** @var list<TaxCategory> */
    #[XmlElement(name: 'ClassifiedTaxCategory', namespace: Ns::CAC, type: TaxCategory::class)]
    private array $classifiedTaxCategories = [];

    /** @var list<ItemProperty> */
    #[XmlElement(name: 'AdditionalItemProperty', namespace: Ns::CAC, type: ItemProperty::class)]
    private array $additionalItemProperties = [];

    /** @var list<Party> */
    #[XmlElement(name: 'ManufacturerParty', namespace: Ns::CAC, type: Party::class)]
    private array $manufacturerParties = [];

    #[XmlElement(name: 'InformationContentProviderParty', namespace: Ns::CAC)]
    private ?Party $informationContentProviderParty = null;

    /** @var list<Address> */
    #[XmlElement(name: 'OriginAddress', namespace: Ns::CAC, type: Address::class)]
    private array $originAddresses = [];

    /** @var list<ItemInstance> */
    #[XmlElement(name: 'ItemInstance', namespace: Ns::CAC, type: ItemInstance::class)]
    private array $itemInstances = [];

    /** @var list<Certificate> */
    #[XmlElement(name: 'Certificate', namespace: Ns::CAC, type: Certificate::class)]
    private array $certificates = [];

    /** @var list<Dimension> */
    #[XmlElement(name: 'Dimension', namespace: Ns::CAC, type: Dimension::class)]
    private array $dimensions = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPackQuantity(): ?Quantity
    {
        return $this->packQuantity;
    }

    public function setPackQuantity(?Quantity $packQuantity = null): self
    {
        $this->packQuantity = $packQuantity;
        return $this;
    }

    public function getPackSizeNumeric(): ?Numeric
    {
        return $this->packSizeNumeric;
    }

    public function setPackSizeNumeric(?Numeric $packSizeNumeric = null): self
    {
        $this->packSizeNumeric = $packSizeNumeric;
        return $this;
    }

    public function getCatalogueIndicator(): ?bool
    {
        return $this->catalogueIndicator;
    }

    public function setCatalogueIndicator(?bool $catalogueIndicator = null): self
    {
        $this->catalogueIndicator = $catalogueIndicator;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getHazardousRiskIndicator(): ?bool
    {
        return $this->hazardousRiskIndicator;
    }

    public function setHazardousRiskIndicator(?bool $hazardousRiskIndicator = null): self
    {
        $this->hazardousRiskIndicator = $hazardousRiskIndicator;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getAdditionalInformations(): array
    {
        return $this->additionalInformations;
    }

    /**
     * @param list<Text> $additionalInformations
     */
    public function setAdditionalInformations(array $additionalInformations): self
    {
        self::validateAdditionalInformations($additionalInformations);
        $this->additionalInformations = $additionalInformations;
        return $this;
    }

    public function addToAdditionalInformations(Text $item): self
    {
        $this->additionalInformations[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateAdditionalInformations(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getKeywords(): array
    {
        return $this->keywords;
    }

    /**
     * @param list<Text> $keywords
     */
    public function setKeywords(array $keywords): self
    {
        self::validateKeywords($keywords);
        $this->keywords = $keywords;
        return $this;
    }

    public function addToKeywords(Text $item): self
    {
        $this->keywords[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateKeywords(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getBrandNames(): array
    {
        return $this->brandNames;
    }

    /**
     * @param list<Text> $brandNames
     */
    public function setBrandNames(array $brandNames): self
    {
        self::validateBrandNames($brandNames);
        $this->brandNames = $brandNames;
        return $this;
    }

    public function addToBrandNames(Text $item): self
    {
        $this->brandNames[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateBrandNames(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getModelNames(): array
    {
        return $this->modelNames;
    }

    /**
     * @param list<Text> $modelNames
     */
    public function setModelNames(array $modelNames): self
    {
        self::validateModelNames($modelNames);
        $this->modelNames = $modelNames;
        return $this;
    }

    public function addToModelNames(Text $item): self
    {
        $this->modelNames[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateModelNames(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getBuyersItemIdentification(): ?ItemIdentification
    {
        return $this->buyersItemIdentification;
    }

    public function setBuyersItemIdentification(?ItemIdentification $buyersItemIdentification = null): self
    {
        $this->buyersItemIdentification = $buyersItemIdentification;
        return $this;
    }

    public function getSellersItemIdentification(): ?ItemIdentification
    {
        return $this->sellersItemIdentification;
    }

    public function setSellersItemIdentification(?ItemIdentification $sellersItemIdentification = null): self
    {
        $this->sellersItemIdentification = $sellersItemIdentification;
        return $this;
    }

    /**
     * @return list<ItemIdentification>
     */
    public function getManufacturersItemIdentifications(): array
    {
        return $this->manufacturersItemIdentifications;
    }

    /**
     * @param list<ItemIdentification> $manufacturersItemIdentifications
     */
    public function setManufacturersItemIdentifications(array $manufacturersItemIdentifications): self
    {
        self::validateManufacturersItemIdentifications($manufacturersItemIdentifications);
        $this->manufacturersItemIdentifications = $manufacturersItemIdentifications;
        return $this;
    }

    public function addToManufacturersItemIdentifications(ItemIdentification $item): self
    {
        $this->manufacturersItemIdentifications[] = $item;
        return $this;
    }

    /**
     * @param list<ItemIdentification> $values
     */
    private static function validateManufacturersItemIdentifications(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ItemIdentification) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ItemIdentification, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getStandardItemIdentification(): ?ItemIdentification
    {
        return $this->standardItemIdentification;
    }

    public function setStandardItemIdentification(?ItemIdentification $standardItemIdentification = null): self
    {
        $this->standardItemIdentification = $standardItemIdentification;
        return $this;
    }

    public function getCatalogueItemIdentification(): ?ItemIdentification
    {
        return $this->catalogueItemIdentification;
    }

    public function setCatalogueItemIdentification(?ItemIdentification $catalogueItemIdentification = null): self
    {
        $this->catalogueItemIdentification = $catalogueItemIdentification;
        return $this;
    }

    /**
     * @return list<ItemIdentification>
     */
    public function getAdditionalItemIdentifications(): array
    {
        return $this->additionalItemIdentifications;
    }

    /**
     * @param list<ItemIdentification> $additionalItemIdentifications
     */
    public function setAdditionalItemIdentifications(array $additionalItemIdentifications): self
    {
        self::validateAdditionalItemIdentifications($additionalItemIdentifications);
        $this->additionalItemIdentifications = $additionalItemIdentifications;
        return $this;
    }

    public function addToAdditionalItemIdentifications(ItemIdentification $item): self
    {
        $this->additionalItemIdentifications[] = $item;
        return $this;
    }

    /**
     * @param list<ItemIdentification> $values
     */
    private static function validateAdditionalItemIdentifications(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ItemIdentification) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ItemIdentification, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getCatalogueDocumentReference(): ?DocumentReference
    {
        return $this->catalogueDocumentReference;
    }

    public function setCatalogueDocumentReference(?DocumentReference $catalogueDocumentReference = null): self
    {
        $this->catalogueDocumentReference = $catalogueDocumentReference;
        return $this;
    }

    /**
     * @return list<DocumentReference>
     */
    public function getItemSpecificationDocumentReferences(): array
    {
        return $this->itemSpecificationDocumentReferences;
    }

    /**
     * @param list<DocumentReference> $itemSpecificationDocumentReferences
     */
    public function setItemSpecificationDocumentReferences(array $itemSpecificationDocumentReferences): self
    {
        self::validateItemSpecificationDocumentReferences($itemSpecificationDocumentReferences);
        $this->itemSpecificationDocumentReferences = $itemSpecificationDocumentReferences;
        return $this;
    }

    public function addToItemSpecificationDocumentReferences(DocumentReference $item): self
    {
        $this->itemSpecificationDocumentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateItemSpecificationDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getOriginCountry(): ?Country
    {
        return $this->originCountry;
    }

    public function setOriginCountry(?Country $originCountry = null): self
    {
        $this->originCountry = $originCountry;
        return $this;
    }

    /**
     * @return list<CommodityClassification>
     */
    public function getCommodityClassifications(): array
    {
        return $this->commodityClassifications;
    }

    /**
     * @param list<CommodityClassification> $commodityClassifications
     */
    public function setCommodityClassifications(array $commodityClassifications): self
    {
        self::validateCommodityClassifications($commodityClassifications);
        $this->commodityClassifications = $commodityClassifications;
        return $this;
    }

    public function addToCommodityClassifications(CommodityClassification $item): self
    {
        $this->commodityClassifications[] = $item;
        return $this;
    }

    /**
     * @param list<CommodityClassification> $values
     */
    private static function validateCommodityClassifications(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof CommodityClassification) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of CommodityClassification, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<TransactionConditions>
     */
    public function getTransactionConditionses(): array
    {
        return $this->transactionConditionses;
    }

    /**
     * @param list<TransactionConditions> $transactionConditionses
     */
    public function setTransactionConditionses(array $transactionConditionses): self
    {
        self::validateTransactionConditionses($transactionConditionses);
        $this->transactionConditionses = $transactionConditionses;
        return $this;
    }

    public function addToTransactionConditionses(TransactionConditions $item): self
    {
        $this->transactionConditionses[] = $item;
        return $this;
    }

    /**
     * @param list<TransactionConditions> $values
     */
    private static function validateTransactionConditionses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TransactionConditions) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TransactionConditions, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<HazardousItem>
     */
    public function getHazardousItems(): array
    {
        return $this->hazardousItems;
    }

    /**
     * @param list<HazardousItem> $hazardousItems
     */
    public function setHazardousItems(array $hazardousItems): self
    {
        self::validateHazardousItems($hazardousItems);
        $this->hazardousItems = $hazardousItems;
        return $this;
    }

    public function addToHazardousItems(HazardousItem $item): self
    {
        $this->hazardousItems[] = $item;
        return $this;
    }

    /**
     * @param list<HazardousItem> $values
     */
    private static function validateHazardousItems(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof HazardousItem) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of HazardousItem, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<TaxCategory>
     */
    public function getClassifiedTaxCategories(): array
    {
        return $this->classifiedTaxCategories;
    }

    /**
     * @param list<TaxCategory> $classifiedTaxCategories
     */
    public function setClassifiedTaxCategories(array $classifiedTaxCategories): self
    {
        self::validateClassifiedTaxCategories($classifiedTaxCategories);
        $this->classifiedTaxCategories = $classifiedTaxCategories;
        return $this;
    }

    public function addToClassifiedTaxCategories(TaxCategory $item): self
    {
        $this->classifiedTaxCategories[] = $item;
        return $this;
    }

    /**
     * @param list<TaxCategory> $values
     */
    private static function validateClassifiedTaxCategories(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TaxCategory) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TaxCategory, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ItemProperty>
     */
    public function getAdditionalItemProperties(): array
    {
        return $this->additionalItemProperties;
    }

    /**
     * @param list<ItemProperty> $additionalItemProperties
     */
    public function setAdditionalItemProperties(array $additionalItemProperties): self
    {
        self::validateAdditionalItemProperties($additionalItemProperties);
        $this->additionalItemProperties = $additionalItemProperties;
        return $this;
    }

    public function addToAdditionalItemProperties(ItemProperty $item): self
    {
        $this->additionalItemProperties[] = $item;
        return $this;
    }

    /**
     * @param list<ItemProperty> $values
     */
    private static function validateAdditionalItemProperties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ItemProperty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ItemProperty, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Party>
     */
    public function getManufacturerParties(): array
    {
        return $this->manufacturerParties;
    }

    /**
     * @param list<Party> $manufacturerParties
     */
    public function setManufacturerParties(array $manufacturerParties): self
    {
        self::validateManufacturerParties($manufacturerParties);
        $this->manufacturerParties = $manufacturerParties;
        return $this;
    }

    public function addToManufacturerParties(Party $item): self
    {
        $this->manufacturerParties[] = $item;
        return $this;
    }

    /**
     * @param list<Party> $values
     */
    private static function validateManufacturerParties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Party) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Party, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getInformationContentProviderParty(): ?Party
    {
        return $this->informationContentProviderParty;
    }

    public function setInformationContentProviderParty(?Party $informationContentProviderParty = null): self
    {
        $this->informationContentProviderParty = $informationContentProviderParty;
        return $this;
    }

    /**
     * @return list<Address>
     */
    public function getOriginAddresses(): array
    {
        return $this->originAddresses;
    }

    /**
     * @param list<Address> $originAddresses
     */
    public function setOriginAddresses(array $originAddresses): self
    {
        self::validateOriginAddresses($originAddresses);
        $this->originAddresses = $originAddresses;
        return $this;
    }

    public function addToOriginAddresses(Address $item): self
    {
        $this->originAddresses[] = $item;
        return $this;
    }

    /**
     * @param list<Address> $values
     */
    private static function validateOriginAddresses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Address) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Address, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ItemInstance>
     */
    public function getItemInstances(): array
    {
        return $this->itemInstances;
    }

    /**
     * @param list<ItemInstance> $itemInstances
     */
    public function setItemInstances(array $itemInstances): self
    {
        self::validateItemInstances($itemInstances);
        $this->itemInstances = $itemInstances;
        return $this;
    }

    public function addToItemInstances(ItemInstance $item): self
    {
        $this->itemInstances[] = $item;
        return $this;
    }

    /**
     * @param list<ItemInstance> $values
     */
    private static function validateItemInstances(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ItemInstance) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ItemInstance, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Certificate>
     */
    public function getCertificates(): array
    {
        return $this->certificates;
    }

    /**
     * @param list<Certificate> $certificates
     */
    public function setCertificates(array $certificates): self
    {
        self::validateCertificates($certificates);
        $this->certificates = $certificates;
        return $this;
    }

    public function addToCertificates(Certificate $item): self
    {
        $this->certificates[] = $item;
        return $this;
    }

    /**
     * @param list<Certificate> $values
     */
    private static function validateCertificates(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Certificate) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Certificate, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Dimension>
     */
    public function getDimensions(): array
    {
        return $this->dimensions;
    }

    /**
     * @param list<Dimension> $dimensions
     */
    public function setDimensions(array $dimensions): self
    {
        self::validateDimensions($dimensions);
        $this->dimensions = $dimensions;
        return $this;
    }

    public function addToDimensions(Dimension $item): self
    {
        $this->dimensions[] = $item;
        return $this;
    }

    /**
     * @param list<Dimension> $values
     */
    private static function validateDimensions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Dimension) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Dimension, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
