<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Meter Reading. Details
 *  A class to describe a meter reading.
 *  Meter Reading
 */
#[XmlType(localName: 'MeterReadingType', namespace: Ns::CAC)]
final class MeterReading
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'MeterReadingType', namespace: Ns::CBC)]
    private ?Text $meterReadingType = null;

    #[XmlElement(name: 'MeterReadingTypeCode', namespace: Ns::CBC)]
    private ?Code $meterReadingTypeCode = null;

    #[XmlElement(name: 'PreviousMeterReadingDate', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $previousMeterReadingDate;

    #[XmlElement(name: 'PreviousMeterQuantity', namespace: Ns::CBC, required: true)]
    private Quantity $previousMeterQuantity;

    #[XmlElement(name: 'LatestMeterReadingDate', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $latestMeterReadingDate;

    #[XmlElement(name: 'LatestMeterQuantity', namespace: Ns::CBC, required: true)]
    private Quantity $latestMeterQuantity;

    #[XmlElement(name: 'PreviousMeterReadingMethod', namespace: Ns::CBC)]
    private ?Text $previousMeterReadingMethod = null;

    #[XmlElement(name: 'PreviousMeterReadingMethodCode', namespace: Ns::CBC)]
    private ?Code $previousMeterReadingMethodCode = null;

    #[XmlElement(name: 'LatestMeterReadingMethod', namespace: Ns::CBC)]
    private ?Text $latestMeterReadingMethod = null;

    #[XmlElement(name: 'LatestMeterReadingMethodCode', namespace: Ns::CBC)]
    private ?Code $latestMeterReadingMethodCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'MeterReadingComments', namespace: Ns::CBC, type: Text::class)]
    private array $meterReadingCommentses = [];

    #[XmlElement(name: 'DeliveredQuantity', namespace: Ns::CBC, required: true)]
    private Quantity $deliveredQuantity;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getMeterReadingType(): ?Text
    {
        return $this->meterReadingType;
    }

    public function setMeterReadingType(?Text $meterReadingType = null): self
    {
        $this->meterReadingType = $meterReadingType;
        return $this;
    }

    public function getMeterReadingTypeCode(): ?Code
    {
        return $this->meterReadingTypeCode;
    }

    public function setMeterReadingTypeCode(?Code $meterReadingTypeCode = null): self
    {
        $this->meterReadingTypeCode = $meterReadingTypeCode;
        return $this;
    }

    public function getPreviousMeterReadingDate(): DateTimeImmutable
    {
        return $this->previousMeterReadingDate;
    }

    public function setPreviousMeterReadingDate(DateTimeImmutable $previousMeterReadingDate): self
    {
        $this->previousMeterReadingDate = $previousMeterReadingDate;
        return $this;
    }

    public function getPreviousMeterQuantity(): Quantity
    {
        return $this->previousMeterQuantity;
    }

    public function setPreviousMeterQuantity(Quantity $previousMeterQuantity): self
    {
        $this->previousMeterQuantity = $previousMeterQuantity;
        return $this;
    }

    public function getLatestMeterReadingDate(): DateTimeImmutable
    {
        return $this->latestMeterReadingDate;
    }

    public function setLatestMeterReadingDate(DateTimeImmutable $latestMeterReadingDate): self
    {
        $this->latestMeterReadingDate = $latestMeterReadingDate;
        return $this;
    }

    public function getLatestMeterQuantity(): Quantity
    {
        return $this->latestMeterQuantity;
    }

    public function setLatestMeterQuantity(Quantity $latestMeterQuantity): self
    {
        $this->latestMeterQuantity = $latestMeterQuantity;
        return $this;
    }

    public function getPreviousMeterReadingMethod(): ?Text
    {
        return $this->previousMeterReadingMethod;
    }

    public function setPreviousMeterReadingMethod(?Text $previousMeterReadingMethod = null): self
    {
        $this->previousMeterReadingMethod = $previousMeterReadingMethod;
        return $this;
    }

    public function getPreviousMeterReadingMethodCode(): ?Code
    {
        return $this->previousMeterReadingMethodCode;
    }

    public function setPreviousMeterReadingMethodCode(?Code $previousMeterReadingMethodCode = null): self
    {
        $this->previousMeterReadingMethodCode = $previousMeterReadingMethodCode;
        return $this;
    }

    public function getLatestMeterReadingMethod(): ?Text
    {
        return $this->latestMeterReadingMethod;
    }

    public function setLatestMeterReadingMethod(?Text $latestMeterReadingMethod = null): self
    {
        $this->latestMeterReadingMethod = $latestMeterReadingMethod;
        return $this;
    }

    public function getLatestMeterReadingMethodCode(): ?Code
    {
        return $this->latestMeterReadingMethodCode;
    }

    public function setLatestMeterReadingMethodCode(?Code $latestMeterReadingMethodCode = null): self
    {
        $this->latestMeterReadingMethodCode = $latestMeterReadingMethodCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getMeterReadingCommentses(): array
    {
        return $this->meterReadingCommentses;
    }

    /**
     * @param list<Text> $meterReadingCommentses
     */
    public function setMeterReadingCommentses(array $meterReadingCommentses): self
    {
        self::validateMeterReadingCommentses($meterReadingCommentses);
        $this->meterReadingCommentses = $meterReadingCommentses;
        return $this;
    }

    public function addToMeterReadingCommentses(Text $item): self
    {
        $this->meterReadingCommentses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateMeterReadingCommentses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getDeliveredQuantity(): Quantity
    {
        return $this->deliveredQuantity;
    }

    public function setDeliveredQuantity(Quantity $deliveredQuantity): self
    {
        $this->deliveredQuantity = $deliveredQuantity;
        return $this;
    }
}
