<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Meter Property. Details
 *  The name of this meter property.
 *  Meter Property
 */
#[XmlType(localName: 'MeterPropertyType', namespace: Ns::CAC)]
final class MeterProperty
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'NameCode', namespace: Ns::CBC)]
    private ?Code $nameCode = null;

    #[XmlElement(name: 'Value', namespace: Ns::CBC)]
    private ?Text $value = null;

    #[XmlElement(name: 'ValueQuantity', namespace: Ns::CBC)]
    private ?Quantity $valueQuantity = null;

    /** @var list<Text> */
    #[XmlElement(name: 'ValueQualifier', namespace: Ns::CBC, type: Text::class)]
    private array $valueQualifiers = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getNameCode(): ?Code
    {
        return $this->nameCode;
    }

    public function setNameCode(?Code $nameCode = null): self
    {
        $this->nameCode = $nameCode;
        return $this;
    }

    public function getValue(): ?Text
    {
        return $this->value;
    }

    public function setValue(?Text $value = null): self
    {
        $this->value = $value;
        return $this;
    }

    public function getValueQuantity(): ?Quantity
    {
        return $this->valueQuantity;
    }

    public function setValueQuantity(?Quantity $valueQuantity = null): self
    {
        $this->valueQuantity = $valueQuantity;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getValueQualifiers(): array
    {
        return $this->valueQualifiers;
    }

    /**
     * @param list<Text> $valueQualifiers
     */
    public function setValueQualifiers(array $valueQualifiers): self
    {
        self::validateValueQualifiers($valueQualifiers);
        $this->valueQualifiers = $valueQualifiers;
        return $this;
    }

    public function addToValueQualifiers(Text $item): self
    {
        $this->valueQualifiers[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateValueQualifiers(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
