<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Order Reference. Details
 *  A class to define a reference to an Order.
 *  Order Reference
 */
#[XmlType(localName: 'OrderReferenceType', namespace: Ns::CAC)]
final class OrderReference
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'SalesOrderID', namespace: Ns::CBC)]
    private ?Identifier $salesOrderID = null;

    #[XmlElement(name: 'CopyIndicator', namespace: Ns::CBC)]
    private ?bool $copyIndicator = null;

    #[XmlElement(name: 'UUID', namespace: Ns::CBC)]
    private ?Identifier $uuid = null;

    #[XmlElement(name: 'IssueDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $issueDate = null;

    #[XmlElement(name: 'IssueTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $issueTime = null;

    #[XmlElement(name: 'CustomerReference', namespace: Ns::CBC)]
    private ?Text $customerReference = null;

    #[XmlElement(name: 'OrderTypeCode', namespace: Ns::CBC)]
    private ?Code $orderTypeCode = null;

    #[XmlElement(name: 'DocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $documentReference = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getSalesOrderID(): ?Identifier
    {
        return $this->salesOrderID;
    }

    public function setSalesOrderID(?Identifier $salesOrderID = null): self
    {
        $this->salesOrderID = $salesOrderID;
        return $this;
    }

    public function getCopyIndicator(): ?bool
    {
        return $this->copyIndicator;
    }

    public function setCopyIndicator(?bool $copyIndicator = null): self
    {
        $this->copyIndicator = $copyIndicator;
        return $this;
    }

    public function getUuid(): ?Identifier
    {
        return $this->uuid;
    }

    public function setUuid(?Identifier $uuid = null): self
    {
        $this->uuid = $uuid;
        return $this;
    }

    public function getIssueDate(): ?DateTimeImmutable
    {
        return $this->issueDate;
    }

    public function setIssueDate(?DateTimeImmutable $issueDate = null): self
    {
        $this->issueDate = $issueDate;
        return $this;
    }

    public function getIssueTime(): ?DateTimeImmutable
    {
        return $this->issueTime;
    }

    public function setIssueTime(?DateTimeImmutable $issueTime = null): self
    {
        $this->issueTime = $issueTime;
        return $this;
    }

    public function getCustomerReference(): ?Text
    {
        return $this->customerReference;
    }

    public function setCustomerReference(?Text $customerReference = null): self
    {
        $this->customerReference = $customerReference;
        return $this;
    }

    public function getOrderTypeCode(): ?Code
    {
        return $this->orderTypeCode;
    }

    public function setOrderTypeCode(?Code $orderTypeCode = null): self
    {
        $this->orderTypeCode = $orderTypeCode;
        return $this;
    }

    public function getDocumentReference(): ?DocumentReference
    {
        return $this->documentReference;
    }

    public function setDocumentReference(?DocumentReference $documentReference = null): self
    {
        $this->documentReference = $documentReference;
        return $this;
    }
}
