<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Order Line Reference. Details
 *  A class to define a reference to an order line.
 *  Order Line Reference
 */
#[XmlType(localName: 'OrderLineReferenceType', namespace: Ns::CAC)]
final class OrderLineReference
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'LineID', namespace: Ns::CBC, required: true)]
    private Identifier $lineID;

    #[XmlElement(name: 'SalesOrderLineID', namespace: Ns::CBC)]
    private ?Identifier $salesOrderLineID = null;

    #[XmlElement(name: 'UUID', namespace: Ns::CBC)]
    private ?Identifier $uuid = null;

    #[XmlElement(name: 'LineStatusCode', namespace: Ns::CBC)]
    private ?Code $lineStatusCode = null;

    #[XmlElement(name: 'OrderReference', namespace: Ns::CAC)]
    private ?OrderReference $orderReference = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getLineID(): Identifier
    {
        return $this->lineID;
    }

    public function setLineID(Identifier $lineID): self
    {
        $this->lineID = $lineID;
        return $this;
    }

    public function getSalesOrderLineID(): ?Identifier
    {
        return $this->salesOrderLineID;
    }

    public function setSalesOrderLineID(?Identifier $salesOrderLineID = null): self
    {
        $this->salesOrderLineID = $salesOrderLineID;
        return $this;
    }

    public function getUuid(): ?Identifier
    {
        return $this->uuid;
    }

    public function setUuid(?Identifier $uuid = null): self
    {
        $this->uuid = $uuid;
        return $this;
    }

    public function getLineStatusCode(): ?Code
    {
        return $this->lineStatusCode;
    }

    public function setLineStatusCode(?Code $lineStatusCode = null): self
    {
        $this->lineStatusCode = $lineStatusCode;
        return $this;
    }

    public function getOrderReference(): ?OrderReference
    {
        return $this->orderReference;
    }

    public function setOrderReference(?OrderReference $orderReference = null): self
    {
        $this->orderReference = $orderReference;
        return $this;
    }
}
