<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Party. Details
 *  A class to describe an organization, sub-organization, or individual fulfilling a role in a business process.
 *  Party
 */
#[XmlType(localName: 'PartyType', namespace: Ns::CAC)]
final class Party
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'MarkCareIndicator', namespace: Ns::CBC)]
    private ?bool $markCareIndicator = null;

    #[XmlElement(name: 'MarkAttentionIndicator', namespace: Ns::CBC)]
    private ?bool $markAttentionIndicator = null;

    #[XmlElement(name: 'WebsiteURI', namespace: Ns::CBC)]
    private ?Identifier $websiteURI = null;

    #[XmlElement(name: 'LogoReferenceID', namespace: Ns::CBC)]
    private ?Identifier $logoReferenceID = null;

    #[XmlElement(name: 'EndpointID', namespace: Ns::CBC)]
    private ?Identifier $endpointID = null;

    #[XmlElement(name: 'IndustryClassificationCode', namespace: Ns::CBC)]
    private ?Code $industryClassificationCode = null;

    /** @var list<PartyIdentification> */
    #[XmlElement(name: 'PartyIdentification', namespace: Ns::CAC, type: PartyIdentification::class)]
    private array $partyIdentifications = [];

    /** @var list<PartyName> */
    #[XmlElement(name: 'PartyName', namespace: Ns::CAC, type: PartyName::class)]
    private array $partyNames = [];

    #[XmlElement(name: 'Language', namespace: Ns::CAC)]
    private ?Language $language = null;

    #[XmlElement(name: 'PostalAddress', namespace: Ns::CAC)]
    private ?Address $postalAddress = null;

    #[XmlElement(name: 'PhysicalLocation', namespace: Ns::CAC)]
    private ?Location $physicalLocation = null;

    /** @var list<PartyTaxScheme> */
    #[XmlElement(name: 'PartyTaxScheme', namespace: Ns::CAC, type: PartyTaxScheme::class)]
    private array $partyTaxSchemes = [];

    /** @var list<PartyLegalEntity> */
    #[XmlElement(name: 'PartyLegalEntity', namespace: Ns::CAC, type: PartyLegalEntity::class)]
    private array $partyLegalEntities = [];

    #[XmlElement(name: 'Contact', namespace: Ns::CAC)]
    private ?Contact $contact = null;

    /** @var list<Person> */
    #[XmlElement(name: 'Person', namespace: Ns::CAC, type: Person::class)]
    private array $persons = [];

    #[XmlElement(name: 'AgentParty', namespace: Ns::CAC)]
    private ?Party $agentParty = null;

    /** @var list<ServiceProviderParty> */
    #[XmlElement(name: 'ServiceProviderParty', namespace: Ns::CAC, type: ServiceProviderParty::class)]
    private array $serviceProviderParties = [];

    /** @var list<PowerOfAttorney> */
    #[XmlElement(name: 'PowerOfAttorney', namespace: Ns::CAC, type: PowerOfAttorney::class)]
    private array $powerOfAttorneys = [];

    /** @var list<Authorization> */
    #[XmlElement(name: 'PartyAuthorization', namespace: Ns::CAC, type: Authorization::class)]
    private array $partyAuthorizations = [];

    #[XmlElement(name: 'FinancialAccount', namespace: Ns::CAC)]
    private ?FinancialAccount $financialAccount = null;

    /** @var list<WebSite> */
    #[XmlElement(name: 'AdditionalWebSite', namespace: Ns::CAC, type: WebSite::class)]
    private array $additionalWebSites = [];

    /** @var list<SocialMediaProfile> */
    #[XmlElement(name: 'SocialMediaProfile', namespace: Ns::CAC, type: SocialMediaProfile::class)]
    private array $socialMediaProfiles = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getMarkCareIndicator(): ?bool
    {
        return $this->markCareIndicator;
    }

    public function setMarkCareIndicator(?bool $markCareIndicator = null): self
    {
        $this->markCareIndicator = $markCareIndicator;
        return $this;
    }

    public function getMarkAttentionIndicator(): ?bool
    {
        return $this->markAttentionIndicator;
    }

    public function setMarkAttentionIndicator(?bool $markAttentionIndicator = null): self
    {
        $this->markAttentionIndicator = $markAttentionIndicator;
        return $this;
    }

    public function getWebsiteURI(): ?Identifier
    {
        return $this->websiteURI;
    }

    public function setWebsiteURI(?Identifier $websiteURI = null): self
    {
        $this->websiteURI = $websiteURI;
        return $this;
    }

    public function getLogoReferenceID(): ?Identifier
    {
        return $this->logoReferenceID;
    }

    public function setLogoReferenceID(?Identifier $logoReferenceID = null): self
    {
        $this->logoReferenceID = $logoReferenceID;
        return $this;
    }

    public function getEndpointID(): ?Identifier
    {
        return $this->endpointID;
    }

    public function setEndpointID(?Identifier $endpointID = null): self
    {
        $this->endpointID = $endpointID;
        return $this;
    }

    public function getIndustryClassificationCode(): ?Code
    {
        return $this->industryClassificationCode;
    }

    public function setIndustryClassificationCode(?Code $industryClassificationCode = null): self
    {
        $this->industryClassificationCode = $industryClassificationCode;
        return $this;
    }

    /**
     * @return list<PartyIdentification>
     */
    public function getPartyIdentifications(): array
    {
        return $this->partyIdentifications;
    }

    /**
     * @param list<PartyIdentification> $partyIdentifications
     */
    public function setPartyIdentifications(array $partyIdentifications): self
    {
        self::validatePartyIdentifications($partyIdentifications);
        $this->partyIdentifications = $partyIdentifications;
        return $this;
    }

    public function addToPartyIdentifications(PartyIdentification $item): self
    {
        $this->partyIdentifications[] = $item;
        return $this;
    }

    /**
     * @param list<PartyIdentification> $values
     */
    private static function validatePartyIdentifications(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PartyIdentification) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PartyIdentification, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<PartyName>
     */
    public function getPartyNames(): array
    {
        return $this->partyNames;
    }

    /**
     * @param list<PartyName> $partyNames
     */
    public function setPartyNames(array $partyNames): self
    {
        self::validatePartyNames($partyNames);
        $this->partyNames = $partyNames;
        return $this;
    }

    public function addToPartyNames(PartyName $item): self
    {
        $this->partyNames[] = $item;
        return $this;
    }

    /**
     * @param list<PartyName> $values
     */
    private static function validatePartyNames(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PartyName) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PartyName, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language = null): self
    {
        $this->language = $language;
        return $this;
    }

    public function getPostalAddress(): ?Address
    {
        return $this->postalAddress;
    }

    public function setPostalAddress(?Address $postalAddress = null): self
    {
        $this->postalAddress = $postalAddress;
        return $this;
    }

    public function getPhysicalLocation(): ?Location
    {
        return $this->physicalLocation;
    }

    public function setPhysicalLocation(?Location $physicalLocation = null): self
    {
        $this->physicalLocation = $physicalLocation;
        return $this;
    }

    /**
     * @return list<PartyTaxScheme>
     */
    public function getPartyTaxSchemes(): array
    {
        return $this->partyTaxSchemes;
    }

    /**
     * @param list<PartyTaxScheme> $partyTaxSchemes
     */
    public function setPartyTaxSchemes(array $partyTaxSchemes): self
    {
        self::validatePartyTaxSchemes($partyTaxSchemes);
        $this->partyTaxSchemes = $partyTaxSchemes;
        return $this;
    }

    public function addToPartyTaxSchemes(PartyTaxScheme $item): self
    {
        $this->partyTaxSchemes[] = $item;
        return $this;
    }

    /**
     * @param list<PartyTaxScheme> $values
     */
    private static function validatePartyTaxSchemes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PartyTaxScheme) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PartyTaxScheme, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<PartyLegalEntity>
     */
    public function getPartyLegalEntities(): array
    {
        return $this->partyLegalEntities;
    }

    /**
     * @param list<PartyLegalEntity> $partyLegalEntities
     */
    public function setPartyLegalEntities(array $partyLegalEntities): self
    {
        self::validatePartyLegalEntities($partyLegalEntities);
        $this->partyLegalEntities = $partyLegalEntities;
        return $this;
    }

    public function addToPartyLegalEntities(PartyLegalEntity $item): self
    {
        $this->partyLegalEntities[] = $item;
        return $this;
    }

    /**
     * @param list<PartyLegalEntity> $values
     */
    private static function validatePartyLegalEntities(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PartyLegalEntity) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PartyLegalEntity, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    public function setContact(?Contact $contact = null): self
    {
        $this->contact = $contact;
        return $this;
    }

    /**
     * @return list<Person>
     */
    public function getPersons(): array
    {
        return $this->persons;
    }

    /**
     * @param list<Person> $persons
     */
    public function setPersons(array $persons): self
    {
        self::validatePersons($persons);
        $this->persons = $persons;
        return $this;
    }

    public function addToPersons(Person $item): self
    {
        $this->persons[] = $item;
        return $this;
    }

    /**
     * @param list<Person> $values
     */
    private static function validatePersons(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Person) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Person, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getAgentParty(): ?Party
    {
        return $this->agentParty;
    }

    public function setAgentParty(?Party $agentParty = null): self
    {
        $this->agentParty = $agentParty;
        return $this;
    }

    /**
     * @return list<ServiceProviderParty>
     */
    public function getServiceProviderParties(): array
    {
        return $this->serviceProviderParties;
    }

    /**
     * @param list<ServiceProviderParty> $serviceProviderParties
     */
    public function setServiceProviderParties(array $serviceProviderParties): self
    {
        self::validateServiceProviderParties($serviceProviderParties);
        $this->serviceProviderParties = $serviceProviderParties;
        return $this;
    }

    public function addToServiceProviderParties(ServiceProviderParty $item): self
    {
        $this->serviceProviderParties[] = $item;
        return $this;
    }

    /**
     * @param list<ServiceProviderParty> $values
     */
    private static function validateServiceProviderParties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ServiceProviderParty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ServiceProviderParty, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<PowerOfAttorney>
     */
    public function getPowerOfAttorneys(): array
    {
        return $this->powerOfAttorneys;
    }

    /**
     * @param list<PowerOfAttorney> $powerOfAttorneys
     */
    public function setPowerOfAttorneys(array $powerOfAttorneys): self
    {
        self::validatePowerOfAttorneys($powerOfAttorneys);
        $this->powerOfAttorneys = $powerOfAttorneys;
        return $this;
    }

    public function addToPowerOfAttorneys(PowerOfAttorney $item): self
    {
        $this->powerOfAttorneys[] = $item;
        return $this;
    }

    /**
     * @param list<PowerOfAttorney> $values
     */
    private static function validatePowerOfAttorneys(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PowerOfAttorney) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PowerOfAttorney, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Authorization>
     */
    public function getPartyAuthorizations(): array
    {
        return $this->partyAuthorizations;
    }

    /**
     * @param list<Authorization> $partyAuthorizations
     */
    public function setPartyAuthorizations(array $partyAuthorizations): self
    {
        self::validatePartyAuthorizations($partyAuthorizations);
        $this->partyAuthorizations = $partyAuthorizations;
        return $this;
    }

    public function addToPartyAuthorizations(Authorization $item): self
    {
        $this->partyAuthorizations[] = $item;
        return $this;
    }

    /**
     * @param list<Authorization> $values
     */
    private static function validatePartyAuthorizations(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Authorization) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Authorization, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getFinancialAccount(): ?FinancialAccount
    {
        return $this->financialAccount;
    }

    public function setFinancialAccount(?FinancialAccount $financialAccount = null): self
    {
        $this->financialAccount = $financialAccount;
        return $this;
    }

    /**
     * @return list<WebSite>
     */
    public function getAdditionalWebSites(): array
    {
        return $this->additionalWebSites;
    }

    /**
     * @param list<WebSite> $additionalWebSites
     */
    public function setAdditionalWebSites(array $additionalWebSites): self
    {
        self::validateAdditionalWebSites($additionalWebSites);
        $this->additionalWebSites = $additionalWebSites;
        return $this;
    }

    public function addToAdditionalWebSites(WebSite $item): self
    {
        $this->additionalWebSites[] = $item;
        return $this;
    }

    /**
     * @param list<WebSite> $values
     */
    private static function validateAdditionalWebSites(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof WebSite) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of WebSite, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<SocialMediaProfile>
     */
    public function getSocialMediaProfiles(): array
    {
        return $this->socialMediaProfiles;
    }

    /**
     * @param list<SocialMediaProfile> $socialMediaProfiles
     */
    public function setSocialMediaProfiles(array $socialMediaProfiles): self
    {
        self::validateSocialMediaProfiles($socialMediaProfiles);
        $this->socialMediaProfiles = $socialMediaProfiles;
        return $this;
    }

    public function addToSocialMediaProfiles(SocialMediaProfile $item): self
    {
        $this->socialMediaProfiles[] = $item;
        return $this;
    }

    /**
     * @param list<SocialMediaProfile> $values
     */
    private static function validateSocialMediaProfiles(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof SocialMediaProfile) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of SocialMediaProfile, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
