<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Payment Means. Details
 *  A class to describe a means of payment.
 *  Payment Means
 */
#[XmlType(localName: 'PaymentMeansType', namespace: Ns::CAC)]
final class PaymentMeans
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'PaymentMeansCode', namespace: Ns::CBC, required: true)]
    private Code $paymentMeansCode;

    #[XmlElement(name: 'PaymentDueDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $paymentDueDate = null;

    #[XmlElement(name: 'PaymentChannelCode', namespace: Ns::CBC)]
    private ?Code $paymentChannelCode = null;

    #[XmlElement(name: 'InstructionID', namespace: Ns::CBC)]
    private ?Identifier $instructionID = null;

    /** @var list<Text> */
    #[XmlElement(name: 'InstructionNote', namespace: Ns::CBC, type: Text::class)]
    private array $instructionNotes = [];

    /** @var list<Identifier> */
    #[XmlElement(name: 'PaymentID', namespace: Ns::CBC, type: Identifier::class)]
    private array $paymentIDs = [];

    #[XmlElement(name: 'ChargeBearerCode', namespace: Ns::CBC)]
    private ?Code $chargeBearerCode = null;

    #[XmlElement(name: 'ServiceLevelCode', namespace: Ns::CBC)]
    private ?Code $serviceLevelCode = null;

    /** @var list<CardAccount> */
    #[XmlElement(name: 'CardAccount', namespace: Ns::CAC, type: CardAccount::class)]
    private array $cardAccounts = [];

    #[XmlElement(name: 'PayerFinancialAccount', namespace: Ns::CAC)]
    private ?FinancialAccount $payerFinancialAccount = null;

    #[XmlElement(name: 'PayeeFinancialAccount', namespace: Ns::CAC)]
    private ?FinancialAccount $payeeFinancialAccount = null;

    #[XmlElement(name: 'CreditAccount', namespace: Ns::CAC)]
    private ?CreditAccount $creditAccount = null;

    #[XmlElement(name: 'PaymentMandate', namespace: Ns::CAC)]
    private ?PaymentMandate $paymentMandate = null;

    #[XmlElement(name: 'TradeFinancing', namespace: Ns::CAC)]
    private ?TradeFinancing $tradeFinancing = null;

    /** @var list<DocumentDistribution> */
    #[XmlElement(name: 'RemittanceDocumentDistribution', namespace: Ns::CAC, type: DocumentDistribution::class)]
    private array $remittanceDocumentDistributions = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getPaymentMeansCode(): Code
    {
        return $this->paymentMeansCode;
    }

    public function setPaymentMeansCode(Code $paymentMeansCode): self
    {
        $this->paymentMeansCode = $paymentMeansCode;
        return $this;
    }

    public function getPaymentDueDate(): ?DateTimeImmutable
    {
        return $this->paymentDueDate;
    }

    public function setPaymentDueDate(?DateTimeImmutable $paymentDueDate = null): self
    {
        $this->paymentDueDate = $paymentDueDate;
        return $this;
    }

    public function getPaymentChannelCode(): ?Code
    {
        return $this->paymentChannelCode;
    }

    public function setPaymentChannelCode(?Code $paymentChannelCode = null): self
    {
        $this->paymentChannelCode = $paymentChannelCode;
        return $this;
    }

    public function getInstructionID(): ?Identifier
    {
        return $this->instructionID;
    }

    public function setInstructionID(?Identifier $instructionID = null): self
    {
        $this->instructionID = $instructionID;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getInstructionNotes(): array
    {
        return $this->instructionNotes;
    }

    /**
     * @param list<Text> $instructionNotes
     */
    public function setInstructionNotes(array $instructionNotes): self
    {
        self::validateInstructionNotes($instructionNotes);
        $this->instructionNotes = $instructionNotes;
        return $this;
    }

    public function addToInstructionNotes(Text $item): self
    {
        $this->instructionNotes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateInstructionNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Identifier>
     */
    public function getPaymentIDs(): array
    {
        return $this->paymentIDs;
    }

    /**
     * @param list<Identifier> $paymentIDs
     */
    public function setPaymentIDs(array $paymentIDs): self
    {
        self::validatePaymentIDs($paymentIDs);
        $this->paymentIDs = $paymentIDs;
        return $this;
    }

    public function addToPaymentIDs(Identifier $item): self
    {
        $this->paymentIDs[] = $item;
        return $this;
    }

    /**
     * @param list<Identifier> $values
     */
    private static function validatePaymentIDs(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Identifier) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Identifier, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getChargeBearerCode(): ?Code
    {
        return $this->chargeBearerCode;
    }

    public function setChargeBearerCode(?Code $chargeBearerCode = null): self
    {
        $this->chargeBearerCode = $chargeBearerCode;
        return $this;
    }

    public function getServiceLevelCode(): ?Code
    {
        return $this->serviceLevelCode;
    }

    public function setServiceLevelCode(?Code $serviceLevelCode = null): self
    {
        $this->serviceLevelCode = $serviceLevelCode;
        return $this;
    }

    /**
     * @return list<CardAccount>
     */
    public function getCardAccounts(): array
    {
        return $this->cardAccounts;
    }

    /**
     * @param list<CardAccount> $cardAccounts
     */
    public function setCardAccounts(array $cardAccounts): self
    {
        self::validateCardAccounts($cardAccounts);
        $this->cardAccounts = $cardAccounts;
        return $this;
    }

    public function addToCardAccounts(CardAccount $item): self
    {
        $this->cardAccounts[] = $item;
        return $this;
    }

    /**
     * @param list<CardAccount> $values
     */
    private static function validateCardAccounts(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof CardAccount) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of CardAccount, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPayerFinancialAccount(): ?FinancialAccount
    {
        return $this->payerFinancialAccount;
    }

    public function setPayerFinancialAccount(?FinancialAccount $payerFinancialAccount = null): self
    {
        $this->payerFinancialAccount = $payerFinancialAccount;
        return $this;
    }

    public function getPayeeFinancialAccount(): ?FinancialAccount
    {
        return $this->payeeFinancialAccount;
    }

    public function setPayeeFinancialAccount(?FinancialAccount $payeeFinancialAccount = null): self
    {
        $this->payeeFinancialAccount = $payeeFinancialAccount;
        return $this;
    }

    public function getCreditAccount(): ?CreditAccount
    {
        return $this->creditAccount;
    }

    public function setCreditAccount(?CreditAccount $creditAccount = null): self
    {
        $this->creditAccount = $creditAccount;
        return $this;
    }

    public function getPaymentMandate(): ?PaymentMandate
    {
        return $this->paymentMandate;
    }

    public function setPaymentMandate(?PaymentMandate $paymentMandate = null): self
    {
        $this->paymentMandate = $paymentMandate;
        return $this;
    }

    public function getTradeFinancing(): ?TradeFinancing
    {
        return $this->tradeFinancing;
    }

    public function setTradeFinancing(?TradeFinancing $tradeFinancing = null): self
    {
        $this->tradeFinancing = $tradeFinancing;
        return $this;
    }

    /**
     * @return list<DocumentDistribution>
     */
    public function getRemittanceDocumentDistributions(): array
    {
        return $this->remittanceDocumentDistributions;
    }

    /**
     * @param list<DocumentDistribution> $remittanceDocumentDistributions
     */
    public function setRemittanceDocumentDistributions(array $remittanceDocumentDistributions): self
    {
        self::validateRemittanceDocumentDistributions($remittanceDocumentDistributions);
        $this->remittanceDocumentDistributions = $remittanceDocumentDistributions;
        return $this;
    }

    public function addToRemittanceDocumentDistributions(DocumentDistribution $item): self
    {
        $this->remittanceDocumentDistributions[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentDistribution> $values
     */
    private static function validateRemittanceDocumentDistributions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentDistribution) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentDistribution, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
