<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Amount;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Numeric;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Payment Terms. Details
 *  A class to describe a set of payment terms.
 *  Payment Terms
 */
#[XmlType(localName: 'PaymentTermsType', namespace: Ns::CAC)]
final class PaymentTerms
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    /** @var list<Identifier> */
    #[XmlElement(name: 'PaymentMeansID', namespace: Ns::CBC, type: Identifier::class)]
    private array $paymentMeansIDs = [];

    #[XmlElement(name: 'PrepaidPaymentReferenceID', namespace: Ns::CBC)]
    private ?Identifier $prepaidPaymentReferenceID = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Note', namespace: Ns::CBC, type: Text::class)]
    private array $notes = [];

    #[XmlElement(name: 'ReferenceEventCode', namespace: Ns::CBC)]
    private ?Code $referenceEventCode = null;

    #[XmlElement(name: 'SettlementDiscountPercent', namespace: Ns::CBC)]
    private ?Numeric $settlementDiscountPercent = null;

    #[XmlElement(name: 'PenaltySurchargePercent', namespace: Ns::CBC)]
    private ?Numeric $penaltySurchargePercent = null;

    #[XmlElement(name: 'PaymentPercent', namespace: Ns::CBC)]
    private ?Numeric $paymentPercent = null;

    #[XmlElement(name: 'Amount', namespace: Ns::CBC)]
    private ?Amount $amount = null;

    #[XmlElement(name: 'SettlementDiscountAmount', namespace: Ns::CBC)]
    private ?Amount $settlementDiscountAmount = null;

    #[XmlElement(name: 'PenaltyAmount', namespace: Ns::CBC)]
    private ?Amount $penaltyAmount = null;

    #[XmlElement(name: 'PaymentTermsDetailsURI', namespace: Ns::CBC)]
    private ?Identifier $paymentTermsDetailsURI = null;

    #[XmlElement(name: 'PaymentDueDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $paymentDueDate = null;

    #[XmlElement(name: 'InstallmentDueDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $installmentDueDate = null;

    #[XmlElement(name: 'InvoicingPartyReference', namespace: Ns::CBC)]
    private ?Text $invoicingPartyReference = null;

    #[XmlElement(name: 'SettlementPeriod', namespace: Ns::CAC)]
    private ?Period $settlementPeriod = null;

    #[XmlElement(name: 'PenaltyPeriod', namespace: Ns::CAC)]
    private ?Period $penaltyPeriod = null;

    #[XmlElement(name: 'ExchangeRate', namespace: Ns::CAC)]
    private ?ExchangeRate $exchangeRate = null;

    #[XmlElement(name: 'ValidityPeriod', namespace: Ns::CAC)]
    private ?Period $validityPeriod = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return list<Identifier>
     */
    public function getPaymentMeansIDs(): array
    {
        return $this->paymentMeansIDs;
    }

    /**
     * @param list<Identifier> $paymentMeansIDs
     */
    public function setPaymentMeansIDs(array $paymentMeansIDs): self
    {
        self::validatePaymentMeansIDs($paymentMeansIDs);
        $this->paymentMeansIDs = $paymentMeansIDs;
        return $this;
    }

    public function addToPaymentMeansIDs(Identifier $item): self
    {
        $this->paymentMeansIDs[] = $item;
        return $this;
    }

    /**
     * @param list<Identifier> $values
     */
    private static function validatePaymentMeansIDs(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Identifier) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Identifier, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPrepaidPaymentReferenceID(): ?Identifier
    {
        return $this->prepaidPaymentReferenceID;
    }

    public function setPrepaidPaymentReferenceID(?Identifier $prepaidPaymentReferenceID = null): self
    {
        $this->prepaidPaymentReferenceID = $prepaidPaymentReferenceID;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getNotes(): array
    {
        return $this->notes;
    }

    /**
     * @param list<Text> $notes
     */
    public function setNotes(array $notes): self
    {
        self::validateNotes($notes);
        $this->notes = $notes;
        return $this;
    }

    public function addToNotes(Text $item): self
    {
        $this->notes[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNotes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getReferenceEventCode(): ?Code
    {
        return $this->referenceEventCode;
    }

    public function setReferenceEventCode(?Code $referenceEventCode = null): self
    {
        $this->referenceEventCode = $referenceEventCode;
        return $this;
    }

    public function getSettlementDiscountPercent(): ?Numeric
    {
        return $this->settlementDiscountPercent;
    }

    public function setSettlementDiscountPercent(?Numeric $settlementDiscountPercent = null): self
    {
        $this->settlementDiscountPercent = $settlementDiscountPercent;
        return $this;
    }

    public function getPenaltySurchargePercent(): ?Numeric
    {
        return $this->penaltySurchargePercent;
    }

    public function setPenaltySurchargePercent(?Numeric $penaltySurchargePercent = null): self
    {
        $this->penaltySurchargePercent = $penaltySurchargePercent;
        return $this;
    }

    public function getPaymentPercent(): ?Numeric
    {
        return $this->paymentPercent;
    }

    public function setPaymentPercent(?Numeric $paymentPercent = null): self
    {
        $this->paymentPercent = $paymentPercent;
        return $this;
    }

    public function getAmount(): ?Amount
    {
        return $this->amount;
    }

    public function setAmount(?Amount $amount = null): self
    {
        $this->amount = $amount;
        return $this;
    }

    public function getSettlementDiscountAmount(): ?Amount
    {
        return $this->settlementDiscountAmount;
    }

    public function setSettlementDiscountAmount(?Amount $settlementDiscountAmount = null): self
    {
        $this->settlementDiscountAmount = $settlementDiscountAmount;
        return $this;
    }

    public function getPenaltyAmount(): ?Amount
    {
        return $this->penaltyAmount;
    }

    public function setPenaltyAmount(?Amount $penaltyAmount = null): self
    {
        $this->penaltyAmount = $penaltyAmount;
        return $this;
    }

    public function getPaymentTermsDetailsURI(): ?Identifier
    {
        return $this->paymentTermsDetailsURI;
    }

    public function setPaymentTermsDetailsURI(?Identifier $paymentTermsDetailsURI = null): self
    {
        $this->paymentTermsDetailsURI = $paymentTermsDetailsURI;
        return $this;
    }

    public function getPaymentDueDate(): ?DateTimeImmutable
    {
        return $this->paymentDueDate;
    }

    public function setPaymentDueDate(?DateTimeImmutable $paymentDueDate = null): self
    {
        $this->paymentDueDate = $paymentDueDate;
        return $this;
    }

    public function getInstallmentDueDate(): ?DateTimeImmutable
    {
        return $this->installmentDueDate;
    }

    public function setInstallmentDueDate(?DateTimeImmutable $installmentDueDate = null): self
    {
        $this->installmentDueDate = $installmentDueDate;
        return $this;
    }

    public function getInvoicingPartyReference(): ?Text
    {
        return $this->invoicingPartyReference;
    }

    public function setInvoicingPartyReference(?Text $invoicingPartyReference = null): self
    {
        $this->invoicingPartyReference = $invoicingPartyReference;
        return $this;
    }

    public function getSettlementPeriod(): ?Period
    {
        return $this->settlementPeriod;
    }

    public function setSettlementPeriod(?Period $settlementPeriod = null): self
    {
        $this->settlementPeriod = $settlementPeriod;
        return $this;
    }

    public function getPenaltyPeriod(): ?Period
    {
        return $this->penaltyPeriod;
    }

    public function setPenaltyPeriod(?Period $penaltyPeriod = null): self
    {
        $this->penaltyPeriod = $penaltyPeriod;
        return $this;
    }

    public function getExchangeRate(): ?ExchangeRate
    {
        return $this->exchangeRate;
    }

    public function setExchangeRate(?ExchangeRate $exchangeRate = null): self
    {
        $this->exchangeRate = $exchangeRate;
        return $this;
    }

    public function getValidityPeriod(): ?Period
    {
        return $this->validityPeriod;
    }

    public function setValidityPeriod(?Period $validityPeriod = null): self
    {
        $this->validityPeriod = $validityPeriod;
        return $this;
    }
}
