<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Port Call. Details
 *  A class to describe a call to a port.
 *  Port Call
 */
#[XmlType(localName: 'PortCallType', namespace: Ns::CAC)]
final class PortCall
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    /** @var list<Text> */
    #[XmlElement(name: 'PlannedOperationsDescription', namespace: Ns::CBC, type: Text::class)]
    private array $plannedOperationsDescriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'PlannedWorksDescription', namespace: Ns::CBC, type: Text::class)]
    private array $plannedWorksDescriptions = [];

    /** @var list<Text> */
    #[XmlElement(name: 'PlannedInspectionsDescription', namespace: Ns::CBC, type: Text::class)]
    private array $plannedInspectionsDescriptions = [];

    #[XmlElement(name: 'ExpectedAnchorageIndicator', namespace: Ns::CBC)]
    private ?bool $expectedAnchorageIndicator = null;

    #[XmlElement(name: 'PositionInPortID', namespace: Ns::CBC)]
    private ?Identifier $positionInPortID = null;

    /** @var list<Text> */
    #[XmlElement(name: 'CargoAndBallastTankConditionDescription', namespace: Ns::CBC, type: Text::class)]
    private array $cargoAndBallastTankConditionDescriptions = [];

    /** @var list<ShipRequirement> */
    #[XmlElement(name: 'ShipRequirement', namespace: Ns::CAC, type: ShipRequirement::class)]
    private array $shipRequirements = [];

    #[XmlElement(name: 'PrimaryPortCallPurpose', namespace: Ns::CAC)]
    private ?PortCallPurpose $primaryPortCallPurpose = null;

    /** @var list<PortCallPurpose> */
    #[XmlElement(name: 'AdditionalPortCallPurpose', namespace: Ns::CAC, type: PortCallPurpose::class)]
    private array $additionalPortCallPurposes = [];

    #[XmlElement(name: 'RequestedArrivalEvent', namespace: Ns::CAC)]
    private ?Event $requestedArrivalEvent = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getPlannedOperationsDescriptions(): array
    {
        return $this->plannedOperationsDescriptions;
    }

    /**
     * @param list<Text> $plannedOperationsDescriptions
     */
    public function setPlannedOperationsDescriptions(array $plannedOperationsDescriptions): self
    {
        self::validatePlannedOperationsDescriptions($plannedOperationsDescriptions);
        $this->plannedOperationsDescriptions = $plannedOperationsDescriptions;
        return $this;
    }

    public function addToPlannedOperationsDescriptions(Text $item): self
    {
        $this->plannedOperationsDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validatePlannedOperationsDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getPlannedWorksDescriptions(): array
    {
        return $this->plannedWorksDescriptions;
    }

    /**
     * @param list<Text> $plannedWorksDescriptions
     */
    public function setPlannedWorksDescriptions(array $plannedWorksDescriptions): self
    {
        self::validatePlannedWorksDescriptions($plannedWorksDescriptions);
        $this->plannedWorksDescriptions = $plannedWorksDescriptions;
        return $this;
    }

    public function addToPlannedWorksDescriptions(Text $item): self
    {
        $this->plannedWorksDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validatePlannedWorksDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getPlannedInspectionsDescriptions(): array
    {
        return $this->plannedInspectionsDescriptions;
    }

    /**
     * @param list<Text> $plannedInspectionsDescriptions
     */
    public function setPlannedInspectionsDescriptions(array $plannedInspectionsDescriptions): self
    {
        self::validatePlannedInspectionsDescriptions($plannedInspectionsDescriptions);
        $this->plannedInspectionsDescriptions = $plannedInspectionsDescriptions;
        return $this;
    }

    public function addToPlannedInspectionsDescriptions(Text $item): self
    {
        $this->plannedInspectionsDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validatePlannedInspectionsDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getExpectedAnchorageIndicator(): ?bool
    {
        return $this->expectedAnchorageIndicator;
    }

    public function setExpectedAnchorageIndicator(?bool $expectedAnchorageIndicator = null): self
    {
        $this->expectedAnchorageIndicator = $expectedAnchorageIndicator;
        return $this;
    }

    public function getPositionInPortID(): ?Identifier
    {
        return $this->positionInPortID;
    }

    public function setPositionInPortID(?Identifier $positionInPortID = null): self
    {
        $this->positionInPortID = $positionInPortID;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getCargoAndBallastTankConditionDescriptions(): array
    {
        return $this->cargoAndBallastTankConditionDescriptions;
    }

    /**
     * @param list<Text> $cargoAndBallastTankConditionDescriptions
     */
    public function setCargoAndBallastTankConditionDescriptions(array $cargoAndBallastTankConditionDescriptions): self
    {
        self::validateCargoAndBallastTankConditionDescriptions($cargoAndBallastTankConditionDescriptions);
        $this->cargoAndBallastTankConditionDescriptions = $cargoAndBallastTankConditionDescriptions;
        return $this;
    }

    public function addToCargoAndBallastTankConditionDescriptions(Text $item): self
    {
        $this->cargoAndBallastTankConditionDescriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateCargoAndBallastTankConditionDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ShipRequirement>
     */
    public function getShipRequirements(): array
    {
        return $this->shipRequirements;
    }

    /**
     * @param list<ShipRequirement> $shipRequirements
     */
    public function setShipRequirements(array $shipRequirements): self
    {
        self::validateShipRequirements($shipRequirements);
        $this->shipRequirements = $shipRequirements;
        return $this;
    }

    public function addToShipRequirements(ShipRequirement $item): self
    {
        $this->shipRequirements[] = $item;
        return $this;
    }

    /**
     * @param list<ShipRequirement> $values
     */
    private static function validateShipRequirements(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ShipRequirement) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ShipRequirement, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPrimaryPortCallPurpose(): ?PortCallPurpose
    {
        return $this->primaryPortCallPurpose;
    }

    public function setPrimaryPortCallPurpose(?PortCallPurpose $primaryPortCallPurpose = null): self
    {
        $this->primaryPortCallPurpose = $primaryPortCallPurpose;
        return $this;
    }

    /**
     * @return list<PortCallPurpose>
     */
    public function getAdditionalPortCallPurposes(): array
    {
        return $this->additionalPortCallPurposes;
    }

    /**
     * @param list<PortCallPurpose> $additionalPortCallPurposes
     */
    public function setAdditionalPortCallPurposes(array $additionalPortCallPurposes): self
    {
        self::validateAdditionalPortCallPurposes($additionalPortCallPurposes);
        $this->additionalPortCallPurposes = $additionalPortCallPurposes;
        return $this;
    }

    public function addToAdditionalPortCallPurposes(PortCallPurpose $item): self
    {
        $this->additionalPortCallPurposes[] = $item;
        return $this;
    }

    /**
     * @param list<PortCallPurpose> $values
     */
    private static function validateAdditionalPortCallPurposes(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PortCallPurpose) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PortCallPurpose, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getRequestedArrivalEvent(): ?Event
    {
        return $this->requestedArrivalEvent;
    }

    public function setRequestedArrivalEvent(?Event $requestedArrivalEvent = null): self
    {
        $this->requestedArrivalEvent = $requestedArrivalEvent;
        return $this;
    }
}
