<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Price List. Details
 *  A class to describe a price list.
 *  Price List
 */
#[XmlType(localName: 'PriceListType', namespace: Ns::CAC)]
final class PriceList
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'StatusCode', namespace: Ns::CBC)]
    private ?Code $statusCode = null;

    /** @var list<Period> */
    #[XmlElement(name: 'ValidityPeriod', namespace: Ns::CAC, type: Period::class)]
    private array $validityPeriods = [];

    #[XmlElement(name: 'PreviousPriceList', namespace: Ns::CAC)]
    private ?PriceList $previousPriceList = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getStatusCode(): ?Code
    {
        return $this->statusCode;
    }

    public function setStatusCode(?Code $statusCode = null): self
    {
        $this->statusCode = $statusCode;
        return $this;
    }

    /**
     * @return list<Period>
     */
    public function getValidityPeriods(): array
    {
        return $this->validityPeriods;
    }

    /**
     * @param list<Period> $validityPeriods
     */
    public function setValidityPeriods(array $validityPeriods): self
    {
        self::validateValidityPeriods($validityPeriods);
        $this->validityPeriods = $validityPeriods;
        return $this;
    }

    public function addToValidityPeriods(Period $item): self
    {
        $this->validityPeriods[] = $item;
        return $this;
    }

    /**
     * @param list<Period> $values
     */
    private static function validateValidityPeriods(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Period) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Period, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getPreviousPriceList(): ?PriceList
    {
        return $this->previousPriceList;
    }

    public function setPreviousPriceList(?PriceList $previousPriceList = null): self
    {
        $this->previousPriceList = $previousPriceList;
        return $this;
    }
}
