<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Process Justification. Details
 *  A class to describe a justification for the choice of tendering process.
 *  Process Justification
 */
#[XmlType(localName: 'ProcessJustificationType', namespace: Ns::CAC)]
final class ProcessJustification
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'PreviousCancellationReasonCode', namespace: Ns::CBC)]
    private ?Code $previousCancellationReasonCode = null;

    #[XmlElement(name: 'ProcessReasonCode', namespace: Ns::CBC)]
    private ?Code $processReasonCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'ProcessReason', namespace: Ns::CBC, type: Text::class)]
    private array $processReasons = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getPreviousCancellationReasonCode(): ?Code
    {
        return $this->previousCancellationReasonCode;
    }

    public function setPreviousCancellationReasonCode(?Code $previousCancellationReasonCode = null): self
    {
        $this->previousCancellationReasonCode = $previousCancellationReasonCode;
        return $this;
    }

    public function getProcessReasonCode(): ?Code
    {
        return $this->processReasonCode;
    }

    public function setProcessReasonCode(?Code $processReasonCode = null): self
    {
        $this->processReasonCode = $processReasonCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getProcessReasons(): array
    {
        return $this->processReasons;
    }

    /**
     * @param list<Text> $processReasons
     */
    public function setProcessReasons(array $processReasons): self
    {
        self::validateProcessReasons($processReasons);
        $this->processReasons = $processReasons;
        return $this;
    }

    public function addToProcessReasons(Text $item): self
    {
        $this->processReasons[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateProcessReasons(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
