<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Promotional Specification. Details
 *  A class to describe a promotional event as a set of item locations that share a set of promotional tactics.
 *  Promotional Specification
 */
#[XmlType(localName: 'PromotionalSpecificationType', namespace: Ns::CAC)]
final class PromotionalSpecification
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'SpecificationID', namespace: Ns::CBC)]
    private ?Identifier $specificationID = null;

    /** @var list<PromotionalEventLineItem> */
    #[XmlElement(name: 'PromotionalEventLineItem', namespace: Ns::CAC, type: PromotionalEventLineItem::class, required: true)]
    private array $promotionalEventLineItems = [];

    /** @var list<EventTactic> */
    #[XmlElement(name: 'EventTactic', namespace: Ns::CAC, type: EventTactic::class)]
    private array $eventTactics = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getSpecificationID(): ?Identifier
    {
        return $this->specificationID;
    }

    public function setSpecificationID(?Identifier $specificationID = null): self
    {
        $this->specificationID = $specificationID;
        return $this;
    }

    /**
     * @return list<PromotionalEventLineItem>
     */
    public function getPromotionalEventLineItems(): array
    {
        return $this->promotionalEventLineItems;
    }

    /**
     * @param list<PromotionalEventLineItem> $promotionalEventLineItems
     */
    public function setPromotionalEventLineItems(array $promotionalEventLineItems): self
    {
        self::validatePromotionalEventLineItems($promotionalEventLineItems);
        $this->promotionalEventLineItems = $promotionalEventLineItems;
        return $this;
    }

    public function addToPromotionalEventLineItems(PromotionalEventLineItem $item): self
    {
        $this->promotionalEventLineItems[] = $item;
        return $this;
    }

    /**
     * @param list<PromotionalEventLineItem> $values
     */
    private static function validatePromotionalEventLineItems(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof PromotionalEventLineItem) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of PromotionalEventLineItem, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<EventTactic>
     */
    public function getEventTactics(): array
    {
        return $this->eventTactics;
    }

    /**
     * @param list<EventTactic> $eventTactics
     */
    public function setEventTactics(array $eventTactics): self
    {
        self::validateEventTactics($eventTactics);
        $this->eventTactics = $eventTactics;
        return $this;
    }

    public function addToEventTactics(EventTactic $item): self
    {
        $this->eventTactics[] = $item;
        return $this;
    }

    /**
     * @param list<EventTactic> $values
     */
    private static function validateEventTactics(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof EventTactic) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of EventTactic, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
