<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Rail Transport. Details
 *  A class defining details about a train wagon used as a means of transport.
 *  Rail Transport
 */
#[XmlType(localName: 'RailTransportType', namespace: Ns::CAC)]
final class RailTransport
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'TrainID', namespace: Ns::CBC, required: true)]
    private Identifier $trainID;

    #[XmlElement(name: 'RailCarID', namespace: Ns::CBC)]
    private ?Identifier $railCarID = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getTrainID(): Identifier
    {
        return $this->trainID;
    }

    public function setTrainID(Identifier $trainID): self
    {
        $this->trainID = $trainID;
        return $this;
    }

    public function getRailCarID(): ?Identifier
    {
        return $this->railCarID;
    }

    public function setRailCarID(?Identifier $railCarID = null): self
    {
        $this->railCarID = $railCarID;
        return $this;
    }
}
