<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Regulation. Details
 *  A class to describe a regulation.
 *  Regulation
 *  Points to regulation at atomic level
 */
#[XmlType(localName: 'RegulationType', namespace: Ns::CAC)]
final class Regulation
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Name', namespace: Ns::CBC, type: Text::class, required: true)]
    private array $names = [];

    #[XmlElement(name: 'LegalReference', namespace: Ns::CBC)]
    private ?Text $legalReference = null;

    #[XmlElement(name: 'OntologyURI', namespace: Ns::CBC)]
    private ?Identifier $ontologyURI = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getNames(): array
    {
        return $this->names;
    }

    /**
     * @param list<Text> $names
     */
    public function setNames(array $names): self
    {
        self::validateNames($names);
        $this->names = $names;
        return $this;
    }

    public function addToNames(Text $item): self
    {
        $this->names[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNames(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getLegalReference(): ?Text
    {
        return $this->legalReference;
    }

    public function setLegalReference(?Text $legalReference = null): self
    {
        $this->legalReference = $legalReference;
        return $this;
    }

    public function getOntologyURI(): ?Identifier
    {
        return $this->ontologyURI;
    }

    public function setOntologyURI(?Identifier $ontologyURI = null): self
    {
        $this->ontologyURI = $ontologyURI;
        return $this;
    }
}
