<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Response. Details
 *  A class to describe an application-level response to a document.
 *  Response
 */
#[XmlType(localName: 'ResponseType', namespace: Ns::CAC)]
final class Response
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ReferenceID', namespace: Ns::CBC)]
    private ?Identifier $referenceID = null;

    #[XmlElement(name: 'ResponseCode', namespace: Ns::CBC)]
    private ?Code $responseCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'EffectiveDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $effectiveDate = null;

    #[XmlElement(name: 'EffectiveTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $effectiveTime = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Status', namespace: Ns::CAC, type: Text::class)]
    private array $statuses = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getReferenceID(): ?Identifier
    {
        return $this->referenceID;
    }

    public function setReferenceID(?Identifier $referenceID = null): self
    {
        $this->referenceID = $referenceID;
        return $this;
    }

    public function getResponseCode(): ?Code
    {
        return $this->responseCode;
    }

    public function setResponseCode(?Code $responseCode = null): self
    {
        $this->responseCode = $responseCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getEffectiveDate(): ?DateTimeImmutable
    {
        return $this->effectiveDate;
    }

    public function setEffectiveDate(?DateTimeImmutable $effectiveDate = null): self
    {
        $this->effectiveDate = $effectiveDate;
        return $this;
    }

    public function getEffectiveTime(): ?DateTimeImmutable
    {
        return $this->effectiveTime;
    }

    public function setEffectiveTime(?DateTimeImmutable $effectiveTime = null): self
    {
        $this->effectiveTime = $effectiveTime;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getStatuses(): array
    {
        return $this->statuses;
    }

    /**
     * @param list<Text> $statuses
     */
    public function setStatuses(array $statuses): self
    {
        self::validateStatuses($statuses);
        $this->statuses = $statuses;
        return $this;
    }

    public function addToStatuses(Text $item): self
    {
        $this->statuses[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateStatuses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
