<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Sanitary Measure. Details
 *  A class describing a plan, action or meassure that has been implemented for sanitary reasons.
 *  Sanitary Measure
 */
#[XmlType(localName: 'SanitaryMeasureType', namespace: Ns::CAC)]
final class SanitaryMeasure
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'SanitaryMeasureTypeCode', namespace: Ns::CBC, required: true)]
    private Code $sanitaryMeasureTypeCode;

    #[XmlElement(name: 'ApplicationDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $applicationDate = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getSanitaryMeasureTypeCode(): Code
    {
        return $this->sanitaryMeasureTypeCode;
    }

    public function setSanitaryMeasureTypeCode(Code $sanitaryMeasureTypeCode): self
    {
        $this->sanitaryMeasureTypeCode = $sanitaryMeasureTypeCode;
        return $this;
    }

    public function getApplicationDate(): ?DateTimeImmutable
    {
        return $this->applicationDate;
    }

    public function setApplicationDate(?DateTimeImmutable $applicationDate = null): self
    {
        $this->applicationDate = $applicationDate;
        return $this;
    }
}
