<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Secondary Hazard. Details
 *  A class to describe a secondary hazard associated with a hazardous item.
 *  Secondary Hazard
 */
#[XmlType(localName: 'SecondaryHazardType', namespace: Ns::CAC)]
final class SecondaryHazard
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'PlacardNotation', namespace: Ns::CBC)]
    private ?Text $placardNotation = null;

    #[XmlElement(name: 'PlacardEndorsement', namespace: Ns::CBC)]
    private ?Text $placardEndorsement = null;

    #[XmlElement(name: 'EmergencyProceduresCode', namespace: Ns::CBC)]
    private ?Code $emergencyProceduresCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Extension', namespace: Ns::CBC, type: Text::class)]
    private array $extensions = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getPlacardNotation(): ?Text
    {
        return $this->placardNotation;
    }

    public function setPlacardNotation(?Text $placardNotation = null): self
    {
        $this->placardNotation = $placardNotation;
        return $this;
    }

    public function getPlacardEndorsement(): ?Text
    {
        return $this->placardEndorsement;
    }

    public function setPlacardEndorsement(?Text $placardEndorsement = null): self
    {
        $this->placardEndorsement = $placardEndorsement;
        return $this;
    }

    public function getEmergencyProceduresCode(): ?Code
    {
        return $this->emergencyProceduresCode;
    }

    public function setEmergencyProceduresCode(?Code $emergencyProceduresCode = null): self
    {
        $this->emergencyProceduresCode = $emergencyProceduresCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getExtensions(): array
    {
        return $this->extensions;
    }

    /**
     * @param list<Text> $extensions
     */
    public function setExtensions(array $extensions): self
    {
        self::validateExtensions($extensions);
        $this->extensions = $extensions;
        return $this;
    }

    public function addToExtensions(Text $item): self
    {
        $this->extensions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateExtensions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
