<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Service Frequency. Details
 *  A class to specify which day of the week a transport service is operational.
 *  Service Frequency
 */
#[XmlType(localName: 'ServiceFrequencyType', namespace: Ns::CAC)]
final class ServiceFrequency
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'WeekDayCode', namespace: Ns::CBC, required: true)]
    private Code $weekDayCode;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getWeekDayCode(): Code
    {
        return $this->weekDayCode;
    }

    public function setWeekDayCode(Code $weekDayCode): self
    {
        $this->weekDayCode = $weekDayCode;
        return $this;
    }
}
