<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Numeric;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Shareholder Party. Details
 *  A class to describe a shareholder party.
 *  Shareholder Party
 */
#[XmlType(localName: 'ShareholderPartyType', namespace: Ns::CAC)]
final class ShareholderParty
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'PartecipationPercent', namespace: Ns::CBC)]
    private ?Numeric $partecipationPercent = null;

    #[XmlElement(name: 'Party', namespace: Ns::CAC)]
    private ?Party $party = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getPartecipationPercent(): ?Numeric
    {
        return $this->partecipationPercent;
    }

    public function setPartecipationPercent(?Numeric $partecipationPercent = null): self
    {
        $this->partecipationPercent = $partecipationPercent;
        return $this;
    }

    public function getParty(): ?Party
    {
        return $this->party;
    }

    public function setParty(?Party $party = null): self
    {
        $this->party = $party;
        return $this;
    }
}
