<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Social Media Profile. Details
 *  A class to describe a social media profile.
 *  Social Media Profile
 */
#[XmlType(localName: 'SocialMediaProfileType', namespace: Ns::CAC)]
final class SocialMediaProfile
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    #[XmlElement(name: 'SocialMediaTypeCode', namespace: Ns::CBC)]
    private ?Code $socialMediaTypeCode = null;

    #[XmlElement(name: 'URI', namespace: Ns::CBC, required: true)]
    private Identifier $uri;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    public function getSocialMediaTypeCode(): ?Code
    {
        return $this->socialMediaTypeCode;
    }

    public function setSocialMediaTypeCode(?Code $socialMediaTypeCode = null): self
    {
        $this->socialMediaTypeCode = $socialMediaTypeCode;
        return $this;
    }

    public function getUri(): Identifier
    {
        return $this->uri;
    }

    public function setUri(Identifier $uri): self
    {
        $this->uri = $uri;
        return $this;
    }
}
