<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Supplier Party. Details
 *  A class to describe a supplier party.
 *  Supplier Party
 */
#[XmlType(localName: 'SupplierPartyType', namespace: Ns::CAC)]
final class SupplierParty
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'CustomerAssignedAccountID', namespace: Ns::CBC)]
    private ?Identifier $customerAssignedAccountID = null;

    /** @var list<Identifier> */
    #[XmlElement(name: 'AdditionalAccountID', namespace: Ns::CBC, type: Identifier::class)]
    private array $additionalAccountIDs = [];

    #[XmlElement(name: 'DataSendingCapability', namespace: Ns::CBC)]
    private ?Text $dataSendingCapability = null;

    #[XmlElement(name: 'Party', namespace: Ns::CAC)]
    private ?Party $party = null;

    #[XmlElement(name: 'DespatchContact', namespace: Ns::CAC)]
    private ?Contact $despatchContact = null;

    #[XmlElement(name: 'AccountingContact', namespace: Ns::CAC)]
    private ?Contact $accountingContact = null;

    #[XmlElement(name: 'SellerContact', namespace: Ns::CAC)]
    private ?Contact $sellerContact = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getCustomerAssignedAccountID(): ?Identifier
    {
        return $this->customerAssignedAccountID;
    }

    public function setCustomerAssignedAccountID(?Identifier $customerAssignedAccountID = null): self
    {
        $this->customerAssignedAccountID = $customerAssignedAccountID;
        return $this;
    }

    /**
     * @return list<Identifier>
     */
    public function getAdditionalAccountIDs(): array
    {
        return $this->additionalAccountIDs;
    }

    /**
     * @param list<Identifier> $additionalAccountIDs
     */
    public function setAdditionalAccountIDs(array $additionalAccountIDs): self
    {
        self::validateAdditionalAccountIDs($additionalAccountIDs);
        $this->additionalAccountIDs = $additionalAccountIDs;
        return $this;
    }

    public function addToAdditionalAccountIDs(Identifier $item): self
    {
        $this->additionalAccountIDs[] = $item;
        return $this;
    }

    /**
     * @param list<Identifier> $values
     */
    private static function validateAdditionalAccountIDs(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Identifier) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Identifier, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getDataSendingCapability(): ?Text
    {
        return $this->dataSendingCapability;
    }

    public function setDataSendingCapability(?Text $dataSendingCapability = null): self
    {
        $this->dataSendingCapability = $dataSendingCapability;
        return $this;
    }

    public function getParty(): ?Party
    {
        return $this->party;
    }

    public function setParty(?Party $party = null): self
    {
        $this->party = $party;
        return $this;
    }

    public function getDespatchContact(): ?Contact
    {
        return $this->despatchContact;
    }

    public function setDespatchContact(?Contact $despatchContact = null): self
    {
        $this->despatchContact = $despatchContact;
        return $this;
    }

    public function getAccountingContact(): ?Contact
    {
        return $this->accountingContact;
    }

    public function setAccountingContact(?Contact $accountingContact = null): self
    {
        $this->accountingContact = $accountingContact;
        return $this;
    }

    public function getSellerContact(): ?Contact
    {
        return $this->sellerContact;
    }

    public function setSellerContact(?Contact $sellerContact = null): self
    {
        $this->sellerContact = $sellerContact;
        return $this;
    }
}
