<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Amount;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Quantity;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Telecommunications Service. Details
 *  A class to describe a telecommunications service (e.g., a telephone call or a video on demand service).
 *  Telecommunications Service
 */
#[XmlType(localName: 'TelecommunicationsServiceType', namespace: Ns::CAC)]
final class TelecommunicationsService
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'CallDate', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $callDate;

    #[XmlElement(name: 'CallTime', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $callTime;

    #[XmlElement(name: 'ServiceNumberCalled', namespace: Ns::CBC, required: true)]
    private Text $serviceNumberCalled;

    #[XmlElement(name: 'TelecommunicationsServiceCategory', namespace: Ns::CBC)]
    private ?Text $telecommunicationsServiceCategory = null;

    #[XmlElement(name: 'TelecommunicationsServiceCategoryCode', namespace: Ns::CBC)]
    private ?Code $telecommunicationsServiceCategoryCode = null;

    #[XmlElement(name: 'MovieTitle', namespace: Ns::CBC)]
    private ?Text $movieTitle = null;

    #[XmlElement(name: 'RoamingPartnerName', namespace: Ns::CBC)]
    private ?Text $roamingPartnerName = null;

    #[XmlElement(name: 'PayPerView', namespace: Ns::CBC)]
    private ?Text $payPerView = null;

    #[XmlElement(name: 'Quantity', namespace: Ns::CBC)]
    private ?Quantity $quantity = null;

    #[XmlElement(name: 'TelecommunicationsServiceCall', namespace: Ns::CBC)]
    private ?Text $telecommunicationsServiceCall = null;

    #[XmlElement(name: 'TelecommunicationsServiceCallCode', namespace: Ns::CBC)]
    private ?Code $telecommunicationsServiceCallCode = null;

    #[XmlElement(name: 'CallBaseAmount', namespace: Ns::CBC)]
    private ?Amount $callBaseAmount = null;

    #[XmlElement(name: 'CallExtensionAmount', namespace: Ns::CBC)]
    private ?Amount $callExtensionAmount = null;

    #[XmlElement(name: 'Price', namespace: Ns::CAC)]
    private ?Price $price = null;

    #[XmlElement(name: 'Country', namespace: Ns::CAC)]
    private ?Country $country = null;

    /** @var list<ExchangeRate> */
    #[XmlElement(name: 'ExchangeRate', namespace: Ns::CAC, type: ExchangeRate::class)]
    private array $exchangeRates = [];

    /** @var list<AllowanceCharge> */
    #[XmlElement(name: 'AllowanceCharge', namespace: Ns::CAC, type: AllowanceCharge::class)]
    private array $allowanceCharges = [];

    /** @var list<TaxTotal> */
    #[XmlElement(name: 'TaxTotal', namespace: Ns::CAC, type: TaxTotal::class)]
    private array $taxTotals = [];

    /** @var list<Duty> */
    #[XmlElement(name: 'CallDuty', namespace: Ns::CAC, type: Duty::class)]
    private array $callDuties = [];

    /** @var list<Duty> */
    #[XmlElement(name: 'TimeDuty', namespace: Ns::CAC, type: Duty::class)]
    private array $timeDuties = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getCallDate(): DateTimeImmutable
    {
        return $this->callDate;
    }

    public function setCallDate(DateTimeImmutable $callDate): self
    {
        $this->callDate = $callDate;
        return $this;
    }

    public function getCallTime(): DateTimeImmutable
    {
        return $this->callTime;
    }

    public function setCallTime(DateTimeImmutable $callTime): self
    {
        $this->callTime = $callTime;
        return $this;
    }

    public function getServiceNumberCalled(): Text
    {
        return $this->serviceNumberCalled;
    }

    public function setServiceNumberCalled(Text $serviceNumberCalled): self
    {
        $this->serviceNumberCalled = $serviceNumberCalled;
        return $this;
    }

    public function getTelecommunicationsServiceCategory(): ?Text
    {
        return $this->telecommunicationsServiceCategory;
    }

    public function setTelecommunicationsServiceCategory(?Text $telecommunicationsServiceCategory = null): self
    {
        $this->telecommunicationsServiceCategory = $telecommunicationsServiceCategory;
        return $this;
    }

    public function getTelecommunicationsServiceCategoryCode(): ?Code
    {
        return $this->telecommunicationsServiceCategoryCode;
    }

    public function setTelecommunicationsServiceCategoryCode(
        ?Code $telecommunicationsServiceCategoryCode = null,
    ): self {
        $this->telecommunicationsServiceCategoryCode = $telecommunicationsServiceCategoryCode;
        return $this;
    }

    public function getMovieTitle(): ?Text
    {
        return $this->movieTitle;
    }

    public function setMovieTitle(?Text $movieTitle = null): self
    {
        $this->movieTitle = $movieTitle;
        return $this;
    }

    public function getRoamingPartnerName(): ?Text
    {
        return $this->roamingPartnerName;
    }

    public function setRoamingPartnerName(?Text $roamingPartnerName = null): self
    {
        $this->roamingPartnerName = $roamingPartnerName;
        return $this;
    }

    public function getPayPerView(): ?Text
    {
        return $this->payPerView;
    }

    public function setPayPerView(?Text $payPerView = null): self
    {
        $this->payPerView = $payPerView;
        return $this;
    }

    public function getQuantity(): ?Quantity
    {
        return $this->quantity;
    }

    public function setQuantity(?Quantity $quantity = null): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getTelecommunicationsServiceCall(): ?Text
    {
        return $this->telecommunicationsServiceCall;
    }

    public function setTelecommunicationsServiceCall(?Text $telecommunicationsServiceCall = null): self
    {
        $this->telecommunicationsServiceCall = $telecommunicationsServiceCall;
        return $this;
    }

    public function getTelecommunicationsServiceCallCode(): ?Code
    {
        return $this->telecommunicationsServiceCallCode;
    }

    public function setTelecommunicationsServiceCallCode(?Code $telecommunicationsServiceCallCode = null): self
    {
        $this->telecommunicationsServiceCallCode = $telecommunicationsServiceCallCode;
        return $this;
    }

    public function getCallBaseAmount(): ?Amount
    {
        return $this->callBaseAmount;
    }

    public function setCallBaseAmount(?Amount $callBaseAmount = null): self
    {
        $this->callBaseAmount = $callBaseAmount;
        return $this;
    }

    public function getCallExtensionAmount(): ?Amount
    {
        return $this->callExtensionAmount;
    }

    public function setCallExtensionAmount(?Amount $callExtensionAmount = null): self
    {
        $this->callExtensionAmount = $callExtensionAmount;
        return $this;
    }

    public function getPrice(): ?Price
    {
        return $this->price;
    }

    public function setPrice(?Price $price = null): self
    {
        $this->price = $price;
        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country = null): self
    {
        $this->country = $country;
        return $this;
    }

    /**
     * @return list<ExchangeRate>
     */
    public function getExchangeRates(): array
    {
        return $this->exchangeRates;
    }

    /**
     * @param list<ExchangeRate> $exchangeRates
     */
    public function setExchangeRates(array $exchangeRates): self
    {
        self::validateExchangeRates($exchangeRates);
        $this->exchangeRates = $exchangeRates;
        return $this;
    }

    public function addToExchangeRates(ExchangeRate $item): self
    {
        $this->exchangeRates[] = $item;
        return $this;
    }

    /**
     * @param list<ExchangeRate> $values
     */
    private static function validateExchangeRates(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ExchangeRate) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ExchangeRate, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<AllowanceCharge>
     */
    public function getAllowanceCharges(): array
    {
        return $this->allowanceCharges;
    }

    /**
     * @param list<AllowanceCharge> $allowanceCharges
     */
    public function setAllowanceCharges(array $allowanceCharges): self
    {
        self::validateAllowanceCharges($allowanceCharges);
        $this->allowanceCharges = $allowanceCharges;
        return $this;
    }

    public function addToAllowanceCharges(AllowanceCharge $item): self
    {
        $this->allowanceCharges[] = $item;
        return $this;
    }

    /**
     * @param list<AllowanceCharge> $values
     */
    private static function validateAllowanceCharges(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof AllowanceCharge) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of AllowanceCharge, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<TaxTotal>
     */
    public function getTaxTotals(): array
    {
        return $this->taxTotals;
    }

    /**
     * @param list<TaxTotal> $taxTotals
     */
    public function setTaxTotals(array $taxTotals): self
    {
        self::validateTaxTotals($taxTotals);
        $this->taxTotals = $taxTotals;
        return $this;
    }

    public function addToTaxTotals(TaxTotal $item): self
    {
        $this->taxTotals[] = $item;
        return $this;
    }

    /**
     * @param list<TaxTotal> $values
     */
    private static function validateTaxTotals(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof TaxTotal) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of TaxTotal, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Duty>
     */
    public function getCallDuties(): array
    {
        return $this->callDuties;
    }

    /**
     * @param list<Duty> $callDuties
     */
    public function setCallDuties(array $callDuties): self
    {
        self::validateCallDuties($callDuties);
        $this->callDuties = $callDuties;
        return $this;
    }

    public function addToCallDuties(Duty $item): self
    {
        $this->callDuties[] = $item;
        return $this;
    }

    /**
     * @param list<Duty> $values
     */
    private static function validateCallDuties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Duty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Duty, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Duty>
     */
    public function getTimeDuties(): array
    {
        return $this->timeDuties;
    }

    /**
     * @param list<Duty> $timeDuties
     */
    public function setTimeDuties(array $timeDuties): self
    {
        self::validateTimeDuties($timeDuties);
        $this->timeDuties = $timeDuties;
        return $this;
    }

    public function addToTimeDuties(Duty $item): self
    {
        $this->timeDuties[] = $item;
        return $this;
    }

    /**
     * @param list<Duty> $values
     */
    private static function validateTimeDuties(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Duty) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Duty, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
