<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Tender Requirement. Details
 *  A template for a required document in a tendering process.
 *  Tender Requirement
 */
#[XmlType(localName: 'TenderRequirementType', namespace: Ns::CAC)]
final class TenderRequirement
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Name', namespace: Ns::CBC, type: Text::class, required: true)]
    private array $names = [];

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'TemplateDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $templateDocumentReference = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getNames(): array
    {
        return $this->names;
    }

    /**
     * @param list<Text> $names
     */
    public function setNames(array $names): self
    {
        self::validateNames($names);
        $this->names = $names;
        return $this;
    }

    public function addToNames(Text $item): self
    {
        $this->names[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateNames(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getTemplateDocumentReference(): ?DocumentReference
    {
        return $this->templateDocumentReference;
    }

    public function setTemplateDocumentReference(?DocumentReference $templateDocumentReference = null): self
    {
        $this->templateDocumentReference = $templateDocumentReference;
        return $this;
    }
}
