<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Tendering Criterion Response. Details
 *  A class to describe a response to a criterion property.
 *  Tendering Criterion Response
 */
#[XmlType(localName: 'TenderingCriterionResponseType', namespace: Ns::CAC)]
final class TenderingCriterionResponse
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'Name', namespace: Ns::CBC)]
    private ?Text $name = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'ValidatedCriterionPropertyID', namespace: Ns::CBC)]
    private ?Identifier $validatedCriterionPropertyID = null;

    #[XmlElement(name: 'ConfidentialityLevelCode', namespace: Ns::CBC)]
    private ?Code $confidentialityLevelCode = null;

    /** @var list<ResponseValue> */
    #[XmlElement(name: 'ResponseValue', namespace: Ns::CAC, type: ResponseValue::class)]
    private array $responseValues = [];

    /** @var list<Period> */
    #[XmlElement(name: 'ApplicablePeriod', namespace: Ns::CAC, type: Period::class)]
    private array $applicablePeriods = [];

    /** @var list<EvidenceSupplied> */
    #[XmlElement(name: 'EvidenceSupplied', namespace: Ns::CAC, type: EvidenceSupplied::class)]
    private array $evidenceSupplieds = [];

    /** @var list<ProcurementProjectLotReference> */
    #[XmlElement(name: 'ProcurementProjectLotReference', namespace: Ns::CAC, type: ProcurementProjectLotReference::class)]
    private array $procurementProjectLotReferences = [];

    /** @var list<CommodityClassification> */
    #[XmlElement(name: 'CommodityClassification', namespace: Ns::CAC, type: CommodityClassification::class)]
    private array $commodityClassifications = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getName(): ?Text
    {
        return $this->name;
    }

    public function setName(?Text $name = null): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getValidatedCriterionPropertyID(): ?Identifier
    {
        return $this->validatedCriterionPropertyID;
    }

    public function setValidatedCriterionPropertyID(?Identifier $validatedCriterionPropertyID = null): self
    {
        $this->validatedCriterionPropertyID = $validatedCriterionPropertyID;
        return $this;
    }

    public function getConfidentialityLevelCode(): ?Code
    {
        return $this->confidentialityLevelCode;
    }

    public function setConfidentialityLevelCode(?Code $confidentialityLevelCode = null): self
    {
        $this->confidentialityLevelCode = $confidentialityLevelCode;
        return $this;
    }

    /**
     * @return list<ResponseValue>
     */
    public function getResponseValues(): array
    {
        return $this->responseValues;
    }

    /**
     * @param list<ResponseValue> $responseValues
     */
    public function setResponseValues(array $responseValues): self
    {
        self::validateResponseValues($responseValues);
        $this->responseValues = $responseValues;
        return $this;
    }

    public function addToResponseValues(ResponseValue $item): self
    {
        $this->responseValues[] = $item;
        return $this;
    }

    /**
     * @param list<ResponseValue> $values
     */
    private static function validateResponseValues(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ResponseValue) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ResponseValue, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Period>
     */
    public function getApplicablePeriods(): array
    {
        return $this->applicablePeriods;
    }

    /**
     * @param list<Period> $applicablePeriods
     */
    public function setApplicablePeriods(array $applicablePeriods): self
    {
        self::validateApplicablePeriods($applicablePeriods);
        $this->applicablePeriods = $applicablePeriods;
        return $this;
    }

    public function addToApplicablePeriods(Period $item): self
    {
        $this->applicablePeriods[] = $item;
        return $this;
    }

    /**
     * @param list<Period> $values
     */
    private static function validateApplicablePeriods(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Period) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Period, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<EvidenceSupplied>
     */
    public function getEvidenceSupplieds(): array
    {
        return $this->evidenceSupplieds;
    }

    /**
     * @param list<EvidenceSupplied> $evidenceSupplieds
     */
    public function setEvidenceSupplieds(array $evidenceSupplieds): self
    {
        self::validateEvidenceSupplieds($evidenceSupplieds);
        $this->evidenceSupplieds = $evidenceSupplieds;
        return $this;
    }

    public function addToEvidenceSupplieds(EvidenceSupplied $item): self
    {
        $this->evidenceSupplieds[] = $item;
        return $this;
    }

    /**
     * @param list<EvidenceSupplied> $values
     */
    private static function validateEvidenceSupplieds(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof EvidenceSupplied) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of EvidenceSupplied, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<ProcurementProjectLotReference>
     */
    public function getProcurementProjectLotReferences(): array
    {
        return $this->procurementProjectLotReferences;
    }

    /**
     * @param list<ProcurementProjectLotReference> $procurementProjectLotReferences
     */
    public function setProcurementProjectLotReferences(array $procurementProjectLotReferences): self
    {
        self::validateProcurementProjectLotReferences($procurementProjectLotReferences);
        $this->procurementProjectLotReferences = $procurementProjectLotReferences;
        return $this;
    }

    public function addToProcurementProjectLotReferences(ProcurementProjectLotReference $item): self
    {
        $this->procurementProjectLotReferences[] = $item;
        return $this;
    }

    /**
     * @param list<ProcurementProjectLotReference> $values
     */
    private static function validateProcurementProjectLotReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof ProcurementProjectLotReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of ProcurementProjectLotReference, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<CommodityClassification>
     */
    public function getCommodityClassifications(): array
    {
        return $this->commodityClassifications;
    }

    /**
     * @param list<CommodityClassification> $commodityClassifications
     */
    public function setCommodityClassifications(array $commodityClassifications): self
    {
        self::validateCommodityClassifications($commodityClassifications);
        $this->commodityClassifications = $commodityClassifications;
        return $this;
    }

    public function addToCommodityClassifications(CommodityClassification $item): self
    {
        $this->commodityClassifications[] = $item;
        return $this;
    }

    /**
     * @param list<CommodityClassification> $values
     */
    private static function validateCommodityClassifications(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof CommodityClassification) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of CommodityClassification, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
