<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Trading Terms. Details
 *  A class for describing the terms of a trade agreement.
 *  Trading Terms
 */
#[XmlType(localName: 'TradingTermsType', namespace: Ns::CAC)]
final class TradingTerms
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Information', namespace: Ns::CBC, type: Text::class)]
    private array $informations = [];

    #[XmlElement(name: 'Reference', namespace: Ns::CBC)]
    private ?Text $reference = null;

    #[XmlElement(name: 'ApplicableAddress', namespace: Ns::CAC)]
    private ?Address $applicableAddress = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getInformations(): array
    {
        return $this->informations;
    }

    /**
     * @param list<Text> $informations
     */
    public function setInformations(array $informations): self
    {
        self::validateInformations($informations);
        $this->informations = $informations;
        return $this;
    }

    public function addToInformations(Text $item): self
    {
        $this->informations[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateInformations(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getReference(): ?Text
    {
        return $this->reference;
    }

    public function setReference(?Text $reference = null): self
    {
        $this->reference = $reference;
        return $this;
    }

    public function getApplicableAddress(): ?Address
    {
        return $this->applicableAddress;
    }

    public function setApplicableAddress(?Address $applicableAddress = null): self
    {
        $this->applicableAddress = $applicableAddress;
        return $this;
    }
}
