<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Trade Financing. Details
 *  A class to describe a trade financing instrument.
 *  Trade Financing
 */
#[XmlType(localName: 'TradeFinancingType', namespace: Ns::CAC)]
final class TradeFinancing
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'FinancingInstrumentCode', namespace: Ns::CBC)]
    private ?Code $financingInstrumentCode = null;

    #[XmlElement(name: 'ContractDocumentReference', namespace: Ns::CAC)]
    private ?DocumentReference $contractDocumentReference = null;

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'DocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $documentReferences = [];

    #[XmlElement(name: 'FinancingParty', namespace: Ns::CAC, required: true)]
    private Party $financingParty;

    #[XmlElement(name: 'FinancingFinancialAccount', namespace: Ns::CAC)]
    private ?FinancialAccount $financingFinancialAccount = null;

    /** @var list<Clause> */
    #[XmlElement(name: 'Clause', namespace: Ns::CAC, type: Clause::class)]
    private array $clauses = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getFinancingInstrumentCode(): ?Code
    {
        return $this->financingInstrumentCode;
    }

    public function setFinancingInstrumentCode(?Code $financingInstrumentCode = null): self
    {
        $this->financingInstrumentCode = $financingInstrumentCode;
        return $this;
    }

    public function getContractDocumentReference(): ?DocumentReference
    {
        return $this->contractDocumentReference;
    }

    public function setContractDocumentReference(?DocumentReference $contractDocumentReference = null): self
    {
        $this->contractDocumentReference = $contractDocumentReference;
        return $this;
    }

    /**
     * @return list<DocumentReference>
     */
    public function getDocumentReferences(): array
    {
        return $this->documentReferences;
    }

    /**
     * @param list<DocumentReference> $documentReferences
     */
    public function setDocumentReferences(array $documentReferences): self
    {
        self::validateDocumentReferences($documentReferences);
        $this->documentReferences = $documentReferences;
        return $this;
    }

    public function addToDocumentReferences(DocumentReference $item): self
    {
        $this->documentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getFinancingParty(): Party
    {
        return $this->financingParty;
    }

    public function setFinancingParty(Party $financingParty): self
    {
        $this->financingParty = $financingParty;
        return $this;
    }

    public function getFinancingFinancialAccount(): ?FinancialAccount
    {
        return $this->financingFinancialAccount;
    }

    public function setFinancingFinancialAccount(?FinancialAccount $financingFinancialAccount = null): self
    {
        $this->financingFinancialAccount = $financingFinancialAccount;
        return $this;
    }

    /**
     * @return list<Clause>
     */
    public function getClauses(): array
    {
        return $this->clauses;
    }

    /**
     * @param list<Clause> $clauses
     */
    public function setClauses(array $clauses): self
    {
        self::validateClauses($clauses);
        $this->clauses = $clauses;
        return $this;
    }

    public function addToClauses(Clause $item): self
    {
        $this->clauses[] = $item;
        return $this;
    }

    /**
     * @param list<Clause> $values
     */
    private static function validateClauses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Clause) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Clause, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
