<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Transport Means. Details
 *  A class to describe a particular vehicle or vessel used for the conveyance of goods or persons.
 *  Transport Means
 *  Conveyance
 */
#[XmlType(localName: 'TransportMeansType', namespace: Ns::CAC)]
final class TransportMeans
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'JourneyID', namespace: Ns::CBC)]
    private ?Identifier $journeyID = null;

    #[XmlElement(name: 'RegistrationNationalityID', namespace: Ns::CBC)]
    private ?Identifier $registrationNationalityID = null;

    /** @var list<Text> */
    #[XmlElement(name: 'RegistrationNationality', namespace: Ns::CBC, type: Text::class)]
    private array $registrationNationalities = [];

    #[XmlElement(name: 'DirectionCode', namespace: Ns::CBC)]
    private ?Code $directionCode = null;

    #[XmlElement(name: 'TransportMeansTypeCode', namespace: Ns::CBC)]
    private ?Code $transportMeansTypeCode = null;

    #[XmlElement(name: 'TradeServiceCode', namespace: Ns::CBC)]
    private ?Code $tradeServiceCode = null;

    #[XmlElement(name: 'Stowage', namespace: Ns::CAC)]
    private ?Stowage $stowage = null;

    #[XmlElement(name: 'AirTransport', namespace: Ns::CAC)]
    private ?AirTransport $airTransport = null;

    #[XmlElement(name: 'RoadTransport', namespace: Ns::CAC)]
    private ?RoadTransport $roadTransport = null;

    #[XmlElement(name: 'RailTransport', namespace: Ns::CAC)]
    private ?RailTransport $railTransport = null;

    #[XmlElement(name: 'MaritimeTransport', namespace: Ns::CAC)]
    private ?MaritimeTransport $maritimeTransport = null;

    #[XmlElement(name: 'OwnerParty', namespace: Ns::CAC)]
    private ?Party $ownerParty = null;

    /** @var list<Dimension> */
    #[XmlElement(name: 'MeasurementDimension', namespace: Ns::CAC, type: Dimension::class)]
    private array $measurementDimensions = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getJourneyID(): ?Identifier
    {
        return $this->journeyID;
    }

    public function setJourneyID(?Identifier $journeyID = null): self
    {
        $this->journeyID = $journeyID;
        return $this;
    }

    public function getRegistrationNationalityID(): ?Identifier
    {
        return $this->registrationNationalityID;
    }

    public function setRegistrationNationalityID(?Identifier $registrationNationalityID = null): self
    {
        $this->registrationNationalityID = $registrationNationalityID;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getRegistrationNationalities(): array
    {
        return $this->registrationNationalities;
    }

    /**
     * @param list<Text> $registrationNationalities
     */
    public function setRegistrationNationalities(array $registrationNationalities): self
    {
        self::validateRegistrationNationalities($registrationNationalities);
        $this->registrationNationalities = $registrationNationalities;
        return $this;
    }

    public function addToRegistrationNationalities(Text $item): self
    {
        $this->registrationNationalities[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateRegistrationNationalities(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getDirectionCode(): ?Code
    {
        return $this->directionCode;
    }

    public function setDirectionCode(?Code $directionCode = null): self
    {
        $this->directionCode = $directionCode;
        return $this;
    }

    public function getTransportMeansTypeCode(): ?Code
    {
        return $this->transportMeansTypeCode;
    }

    public function setTransportMeansTypeCode(?Code $transportMeansTypeCode = null): self
    {
        $this->transportMeansTypeCode = $transportMeansTypeCode;
        return $this;
    }

    public function getTradeServiceCode(): ?Code
    {
        return $this->tradeServiceCode;
    }

    public function setTradeServiceCode(?Code $tradeServiceCode = null): self
    {
        $this->tradeServiceCode = $tradeServiceCode;
        return $this;
    }

    public function getStowage(): ?Stowage
    {
        return $this->stowage;
    }

    public function setStowage(?Stowage $stowage = null): self
    {
        $this->stowage = $stowage;
        return $this;
    }

    public function getAirTransport(): ?AirTransport
    {
        return $this->airTransport;
    }

    public function setAirTransport(?AirTransport $airTransport = null): self
    {
        $this->airTransport = $airTransport;
        return $this;
    }

    public function getRoadTransport(): ?RoadTransport
    {
        return $this->roadTransport;
    }

    public function setRoadTransport(?RoadTransport $roadTransport = null): self
    {
        $this->roadTransport = $roadTransport;
        return $this;
    }

    public function getRailTransport(): ?RailTransport
    {
        return $this->railTransport;
    }

    public function setRailTransport(?RailTransport $railTransport = null): self
    {
        $this->railTransport = $railTransport;
        return $this;
    }

    public function getMaritimeTransport(): ?MaritimeTransport
    {
        return $this->maritimeTransport;
    }

    public function setMaritimeTransport(?MaritimeTransport $maritimeTransport = null): self
    {
        $this->maritimeTransport = $maritimeTransport;
        return $this;
    }

    public function getOwnerParty(): ?Party
    {
        return $this->ownerParty;
    }

    public function setOwnerParty(?Party $ownerParty = null): self
    {
        $this->ownerParty = $ownerParty;
        return $this;
    }

    /**
     * @return list<Dimension>
     */
    public function getMeasurementDimensions(): array
    {
        return $this->measurementDimensions;
    }

    /**
     * @param list<Dimension> $measurementDimensions
     */
    public function setMeasurementDimensions(array $measurementDimensions): self
    {
        self::validateMeasurementDimensions($measurementDimensions);
        $this->measurementDimensions = $measurementDimensions;
        return $this;
    }

    public function addToMeasurementDimensions(Dimension $item): self
    {
        $this->measurementDimensions[] = $item;
        return $this;
    }

    /**
     * @param list<Dimension> $values
     */
    private static function validateMeasurementDimensions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Dimension) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Dimension, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
