<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Transport Event. Details
 *  A class to describe a significant occurrence or happening related to the transportation of goods.
 *  Transport Event
 */
#[XmlType(localName: 'TransportEventType', namespace: Ns::CAC)]
final class TransportEvent
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'IdentificationID', namespace: Ns::CBC)]
    private ?Identifier $identificationID = null;

    #[XmlElement(name: 'OccurrenceDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $occurrenceDate = null;

    #[XmlElement(name: 'OccurrenceTime', namespace: Ns::CBC)]
    private ?DateTimeImmutable $occurrenceTime = null;

    #[XmlElement(name: 'TransportEventTypeCode', namespace: Ns::CBC)]
    private ?Code $transportEventTypeCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'Description', namespace: Ns::CBC, type: Text::class)]
    private array $descriptions = [];

    #[XmlElement(name: 'CompletionIndicator', namespace: Ns::CBC)]
    private ?bool $completionIndicator = null;

    #[XmlElement(name: 'ReportedShipment', namespace: Ns::CAC)]
    private ?Shipment $reportedShipment = null;

    /** @var list<Status> */
    #[XmlElement(name: 'CurrentStatus', namespace: Ns::CAC, type: Status::class)]
    private array $currentStatuses = [];

    /** @var list<Contact> */
    #[XmlElement(name: 'Contact', namespace: Ns::CAC, type: Contact::class)]
    private array $contacts = [];

    #[XmlElement(name: 'Location', namespace: Ns::CAC)]
    private ?Text $location = null;

    #[XmlElement(name: 'Signature', namespace: Ns::CAC)]
    private ?Signature $signature = null;

    /** @var list<Period> */
    #[XmlElement(name: 'Period', namespace: Ns::CAC, type: Period::class)]
    private array $periods = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getIdentificationID(): ?Identifier
    {
        return $this->identificationID;
    }

    public function setIdentificationID(?Identifier $identificationID = null): self
    {
        $this->identificationID = $identificationID;
        return $this;
    }

    public function getOccurrenceDate(): ?DateTimeImmutable
    {
        return $this->occurrenceDate;
    }

    public function setOccurrenceDate(?DateTimeImmutable $occurrenceDate = null): self
    {
        $this->occurrenceDate = $occurrenceDate;
        return $this;
    }

    public function getOccurrenceTime(): ?DateTimeImmutable
    {
        return $this->occurrenceTime;
    }

    public function setOccurrenceTime(?DateTimeImmutable $occurrenceTime = null): self
    {
        $this->occurrenceTime = $occurrenceTime;
        return $this;
    }

    public function getTransportEventTypeCode(): ?Code
    {
        return $this->transportEventTypeCode;
    }

    public function setTransportEventTypeCode(?Code $transportEventTypeCode = null): self
    {
        $this->transportEventTypeCode = $transportEventTypeCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getDescriptions(): array
    {
        return $this->descriptions;
    }

    /**
     * @param list<Text> $descriptions
     */
    public function setDescriptions(array $descriptions): self
    {
        self::validateDescriptions($descriptions);
        $this->descriptions = $descriptions;
        return $this;
    }

    public function addToDescriptions(Text $item): self
    {
        $this->descriptions[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateDescriptions(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getCompletionIndicator(): ?bool
    {
        return $this->completionIndicator;
    }

    public function setCompletionIndicator(?bool $completionIndicator = null): self
    {
        $this->completionIndicator = $completionIndicator;
        return $this;
    }

    public function getReportedShipment(): ?Shipment
    {
        return $this->reportedShipment;
    }

    public function setReportedShipment(?Shipment $reportedShipment = null): self
    {
        $this->reportedShipment = $reportedShipment;
        return $this;
    }

    /**
     * @return list<Status>
     */
    public function getCurrentStatuses(): array
    {
        return $this->currentStatuses;
    }

    /**
     * @param list<Status> $currentStatuses
     */
    public function setCurrentStatuses(array $currentStatuses): self
    {
        self::validateCurrentStatuses($currentStatuses);
        $this->currentStatuses = $currentStatuses;
        return $this;
    }

    public function addToCurrentStatuses(Status $item): self
    {
        $this->currentStatuses[] = $item;
        return $this;
    }

    /**
     * @param list<Status> $values
     */
    private static function validateCurrentStatuses(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Status) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Status, got %s', get_debug_type($value)),
                );
            }
        }
    }

    /**
     * @return list<Contact>
     */
    public function getContacts(): array
    {
        return $this->contacts;
    }

    /**
     * @param list<Contact> $contacts
     */
    public function setContacts(array $contacts): self
    {
        self::validateContacts($contacts);
        $this->contacts = $contacts;
        return $this;
    }

    public function addToContacts(Contact $item): self
    {
        $this->contacts[] = $item;
        return $this;
    }

    /**
     * @param list<Contact> $values
     */
    private static function validateContacts(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Contact) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Contact, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getLocation(): ?Text
    {
        return $this->location;
    }

    public function setLocation(?Text $location = null): self
    {
        $this->location = $location;
        return $this;
    }

    public function getSignature(): ?Signature
    {
        return $this->signature;
    }

    public function setSignature(?Signature $signature = null): self
    {
        $this->signature = $signature;
        return $this;
    }

    /**
     * @return list<Period>
     */
    public function getPeriods(): array
    {
        return $this->periods;
    }

    /**
     * @param list<Period> $periods
     */
    public function setPeriods(array $periods): self
    {
        self::validatePeriods($periods);
        $this->periods = $periods;
        return $this;
    }

    public function addToPeriods(Period $item): self
    {
        $this->periods[] = $item;
        return $this;
    }

    /**
     * @param list<Period> $values
     */
    private static function validatePeriods(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Period) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Period, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
