<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Transport Equipment Seal. Details
 *  A class to describe a device (a transport equipment seal) for securing the doors of a shipping container.
 *  Transport Equipment Seal
 *  Container Seal
 */
#[XmlType(localName: 'TransportEquipmentSealType', namespace: Ns::CAC)]
final class TransportEquipmentSeal
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC, required: true)]
    private Identifier $id;

    #[XmlElement(name: 'SealIssuerTypeCode', namespace: Ns::CBC)]
    private ?Code $sealIssuerTypeCode = null;

    #[XmlElement(name: 'Condition', namespace: Ns::CBC)]
    private ?Text $condition = null;

    #[XmlElement(name: 'SealStatusCode', namespace: Ns::CBC)]
    private ?Code $sealStatusCode = null;

    #[XmlElement(name: 'SealingPartyType', namespace: Ns::CBC)]
    private ?Text $sealingPartyType = null;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): Identifier
    {
        return $this->id;
    }

    public function setId(Identifier $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getSealIssuerTypeCode(): ?Code
    {
        return $this->sealIssuerTypeCode;
    }

    public function setSealIssuerTypeCode(?Code $sealIssuerTypeCode = null): self
    {
        $this->sealIssuerTypeCode = $sealIssuerTypeCode;
        return $this;
    }

    public function getCondition(): ?Text
    {
        return $this->condition;
    }

    public function setCondition(?Text $condition = null): self
    {
        $this->condition = $condition;
        return $this;
    }

    public function getSealStatusCode(): ?Code
    {
        return $this->sealStatusCode;
    }

    public function setSealStatusCode(?Code $sealStatusCode = null): self
    {
        $this->sealStatusCode = $sealStatusCode;
        return $this;
    }

    public function getSealingPartyType(): ?Text
    {
        return $this->sealingPartyType;
    }

    public function setSealingPartyType(?Text $sealingPartyType = null): self
    {
        $this->sealingPartyType = $sealingPartyType;
        return $this;
    }
}
