<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  WHO Affected Area Visit. Details
 *  A class to describe a visit to a port located in a geographical area considered an “affected area” by the World Health Organization (WHO).
 *  WHO Affected Area Visit
 */
#[XmlType(localName: 'WHOAffectedAreaVisitType', namespace: Ns::CAC)]
final class WHOAffectedAreaVisit
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'VisitDate', namespace: Ns::CBC, required: true)]
    private DateTimeImmutable $visitDate;

    #[XmlElement(name: 'WHOAffectedAreaPortLocation', namespace: Ns::CAC, required: true)]
    private Location $whoAffectedAreaPortLocation;

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getVisitDate(): DateTimeImmutable
    {
        return $this->visitDate;
    }

    public function setVisitDate(DateTimeImmutable $visitDate): self
    {
        $this->visitDate = $visitDate;
        return $this;
    }

    public function getWhoAffectedAreaPortLocation(): Location
    {
        return $this->whoAffectedAreaPortLocation;
    }

    public function setWhoAffectedAreaPortLocation(Location $whoAffectedAreaPortLocation): self
    {
        $this->whoAffectedAreaPortLocation = $whoAffectedAreaPortLocation;
        return $this;
    }
}
