<?php

declare(strict_types=1);

namespace Xterr\Espd\Cac;

use DateTimeImmutable;
use Xterr\Espd\Cbc\Code;
use Xterr\Espd\Cbc\Identifier;
use Xterr\Espd\Cbc\Numeric;
use Xterr\Espd\Cbc\Text;
use Xterr\UBL\Xml\Mapping\XmlElement;
use Xterr\UBL\Xml\Mapping\XmlNamespace as Ns;
use Xterr\UBL\Xml\Mapping\XmlType;

/**
 * @generated by php-ubl code generator — do not edit
 *
 * ABIE
 *  Work Phase Reference. Details
 *  A class that refers to a phase of work. Used for instance to specify what part of the contract the billing is referring to.
 *  Work Phase Reference
 */
#[XmlType(localName: 'WorkPhaseReferenceType', namespace: Ns::CAC)]
final class WorkPhaseReference
{
    #[XmlElement(name: 'UBLExtensions', namespace: Ns::EXT)]
    private ?UBLExtensions $ublExtensions = null;

    #[XmlElement(name: 'ID', namespace: Ns::CBC)]
    private ?Identifier $id = null;

    #[XmlElement(name: 'WorkPhaseCode', namespace: Ns::CBC)]
    private ?Code $workPhaseCode = null;

    /** @var list<Text> */
    #[XmlElement(name: 'WorkPhase', namespace: Ns::CBC, type: Text::class)]
    private array $workPhases = [];

    #[XmlElement(name: 'ProgressPercent', namespace: Ns::CBC)]
    private ?Numeric $progressPercent = null;

    #[XmlElement(name: 'StartDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $startDate = null;

    #[XmlElement(name: 'EndDate', namespace: Ns::CBC)]
    private ?DateTimeImmutable $endDate = null;

    /** @var list<DocumentReference> */
    #[XmlElement(name: 'WorkOrderDocumentReference', namespace: Ns::CAC, type: DocumentReference::class)]
    private array $workOrderDocumentReferences = [];

    public function getUblExtensions(): ?UBLExtensions
    {
        return $this->ublExtensions;
    }

    public function setUblExtensions(?UBLExtensions $ublExtensions = null): self
    {
        $this->ublExtensions = $ublExtensions;
        return $this;
    }

    public function getId(): ?Identifier
    {
        return $this->id;
    }

    public function setId(?Identifier $id = null): self
    {
        $this->id = $id;
        return $this;
    }

    public function getWorkPhaseCode(): ?Code
    {
        return $this->workPhaseCode;
    }

    public function setWorkPhaseCode(?Code $workPhaseCode = null): self
    {
        $this->workPhaseCode = $workPhaseCode;
        return $this;
    }

    /**
     * @return list<Text>
     */
    public function getWorkPhases(): array
    {
        return $this->workPhases;
    }

    /**
     * @param list<Text> $workPhases
     */
    public function setWorkPhases(array $workPhases): self
    {
        self::validateWorkPhases($workPhases);
        $this->workPhases = $workPhases;
        return $this;
    }

    public function addToWorkPhases(Text $item): self
    {
        $this->workPhases[] = $item;
        return $this;
    }

    /**
     * @param list<Text> $values
     */
    private static function validateWorkPhases(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof Text) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of Text, got %s', get_debug_type($value)),
                );
            }
        }
    }

    public function getProgressPercent(): ?Numeric
    {
        return $this->progressPercent;
    }

    public function setProgressPercent(?Numeric $progressPercent = null): self
    {
        $this->progressPercent = $progressPercent;
        return $this;
    }

    public function getStartDate(): ?DateTimeImmutable
    {
        return $this->startDate;
    }

    public function setStartDate(?DateTimeImmutable $startDate = null): self
    {
        $this->startDate = $startDate;
        return $this;
    }

    public function getEndDate(): ?DateTimeImmutable
    {
        return $this->endDate;
    }

    public function setEndDate(?DateTimeImmutable $endDate = null): self
    {
        $this->endDate = $endDate;
        return $this;
    }

    /**
     * @return list<DocumentReference>
     */
    public function getWorkOrderDocumentReferences(): array
    {
        return $this->workOrderDocumentReferences;
    }

    /**
     * @param list<DocumentReference> $workOrderDocumentReferences
     */
    public function setWorkOrderDocumentReferences(array $workOrderDocumentReferences): self
    {
        self::validateWorkOrderDocumentReferences($workOrderDocumentReferences);
        $this->workOrderDocumentReferences = $workOrderDocumentReferences;
        return $this;
    }

    public function addToWorkOrderDocumentReferences(DocumentReference $item): self
    {
        $this->workOrderDocumentReferences[] = $item;
        return $this;
    }

    /**
     * @param list<DocumentReference> $values
     */
    private static function validateWorkOrderDocumentReferences(array $values): void
    {
        foreach ($values as $value) {
            if (!$value instanceof DocumentReference) {
                throw new \InvalidArgumentException(
                    sprintf('Expected instance of DocumentReference, got %s', get_debug_type($value)),
                );
            }
        }
    }
}
